fix stickyness for ack
centreon-archive/centreon-archived pull request #10028
Opened 2021-07-27 08:11 UTC by tanguyvda

## Description

resource status page uses the api/beta/monitoring/resources/acknowledge  endpoint
this endpoint set the sticky value to 1 or 0 instead of 2 or 0 according to this https://assets.nagios.com/downloads/nagioscore/docs/externalcmds/cmdinfo.php?command_id=40

Meaning that if you set the stickyness in your default configuration, it will not work at all and set the ack like it wasn't sticky

## Type of change

- [x] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [x] 20.04.x
- [x] 20.10.x
- [x] 21.04.x
- [x] 21.10.x (master)

<h2> How this pull request can be tested ? </h2>

without this PR,
- go in administration -> parameters -> monitoring menu and tick the sticky checkbox  (meaning ack are going to be sticky)
-  go in the monitoring -> resources status page and put an ack on a service or a host, put the following comment "default sticky value: 1)
- wait for your ack to be displayed in the monitoring (yellow background on the service or host row)
- when ack is displayed, in your central database, run the following query : 
`select sticky,comment_data from centreon_storage.acknowledgements;` 
- you should have the following result: `|      0 | default sticky 1`

with this PR,
- repeat the above steps
- you should have the following result: `|      1 | default sticky 1`

## Checklist

- [ ] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have made corresponding changes to the **documentation**.
- [ ] I have **rebased** my development branch on the base branch (master, maintenance).

2021-07-29 07:03 UTC, jeremyjaouen requested changes

2021-07-29 07:03 UTC, jeremyjaouen commented on src/Centreon/Domain/Engine/EngineService.php
> +        if ((int) $acknowledgement->isSticky() === 1) {
```suggestion
        if ($acknowledgement->isSticky() === true) {
```

2021-07-29 07:03 UTC, jeremyjaouen commented on src/Centreon/Domain/Engine/EngineService.php
> +        if ((int) $acknowledgement->isSticky() === 1) {
```suggestion
        if ($acknowledgement->isSticky() === true) {
```

2021-07-30 14:34 UTC, sc979 approved these changes, later dismissed

2021-08-03 07:26 UTC, jeremyjaouen approved these changes, later dismissed

2021-11-22 13:21 UTC, omercier commented
Internal reference: MON-11757

2021-11-22 13:21 UTC, callapa requested changes

2021-11-22 13:21 UTC, callapa commented on src/Centreon/Domain/Engine/EngineService.php
> +
```suggestion
```

2021-11-22 13:21 UTC, callapa commented on src/Centreon/Domain/Engine/EngineService.php
> +            $sticky,
```suggestion
            $acknowledgement->isSticky() ? 2 : 0,
```

2021-11-22 13:21 UTC, callapa commented on src/Centreon/Domain/Engine/EngineService.php
> +            $sticky,
```suggestion
            $acknowledgement->isSticky() ? 2 : 0,
```

2021-11-22 13:21 UTC, callapa commented on src/Centreon/Domain/Engine/EngineService.php
> +
```suggestion
```

2021-11-22 13:30 UTC, callapa approved these changes

2021-11-22 13:31 UTC, a-launois approved these changes

2021-11-23 13:13 UTC, callapa commented
Already fixed in the develop branch. Must be cherry-picked in the others.

2021-11-24 16:29 UTC, closed without merging

2021-11-24 16:29 UTC, callapa commented
https://github.com/centreon/centreon/pull/10432