feat(conf/poller): Added APIs to generate and reload monitoring server configuration
centreon-archive/centreon-archived pull request #10087
Opened 2021-09-01 12:27 UTC by callapa

## Description

Added 6 new APIs to generate and reload monitoring server configuration.

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [x] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [ ] 20.04.x
- [ ] 20.10.x
- [ ] 21.04.x
- [x] 21.10.x (master)

<h2> How this pull request can be tested ? </h2>

See the API documentation in the **Monitoring Server** section

## Checklist

- [x] I have followed the **coding style guidelines** provided by Centreon
- [x] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [x] I have commented my code, especially **hard-to-understand areas** of the PR.
- [x] I have made corresponding changes to the **documentation**.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2021-09-14 11:21 UTC, adr-mo approved these changes, later dismissed

2021-09-14 12:04 UTC, jeremyjaouen requested changes

2021-09-14 14:52 UTC, jeremyjaouen approved these changes, later dismissed

2021-09-20 07:17 UTC, kduret commented on composer.json
> +        "symfony/serializer": "4.4.*"
could you use alphabetical order ? It will be easier to read

2021-09-20 07:17 UTC, kduret commented on lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "Erreur sur le serveur de supervision #%d : %s"
```suggestion
msgstr "Erreur sur le serveur de supervision #%d: %s"
```

2021-09-20 07:17 UTC, kduret commented on src/Centreon/Application/Controller/Configuration/MonitoringServerController.php
>          $server = $this->monitoringServerService->findServers();
`findServers` should be renamed to `findServer` ?

2021-09-20 07:17 UTC, kduret commented on src/Centreon/Domain/MonitoringServer/UseCase/GenerateConfiguration.php
> +    private $repository;
may need to be renamed to more explicit name

2021-09-20 07:17 UTC, kduret commented on src/Centreon/Domain/MonitoringServer/UseCase/ReloadAllConfigurations.php
> +    private $repository;
may need to be renamed to more explicit name

2021-09-20 07:17 UTC, kduret commented on src/Centreon/Domain/MonitoringServer/UseCase/ReloadConfiguration.php
> +    private $repository;
may need to be renamed to more explicit name

2021-09-20 07:17 UTC, kduret commented on lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "La requête a échoué"
```suggestion
msgid "Request failed (%d)"
msgstr "La requête a échoué (%d)"
```

2021-09-27 07:59 UTC, kduret approved these changes, later dismissed

2021-09-27 09:25 UTC, adr-mo submitted a review, later dismissed

2021-09-30 09:48 UTC, kduret approved these changes, later dismissed

2021-10-01 11:59 UTC, kduret approved these changes

2021-10-01 13:09 UTC, adr-mo approved these changes

2021-10-01 20:07 UTC, merged