feat(Product Adoption): add user consent option to send plain or anonymised platform informations.
centreon-archive/centreon-archived pull request #10094
Opened 2021-09-07 02:08 UTC by jeremyjaouen

## Description
This PR add an option into "My Account" and Users > Additional Informations to let the user decide if they want or not send platform data, anonymized or not.

**Fixes** # MON-10927

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [x] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [ ] 20.04.x
- [ ] 20.10.x
- [ ] 21.04.x
- [x] 21.10.x (master)

<h2> How this pull request can be tested ? </h2>

Given a platform without licenses
When the user go to “Administration > Parameters > My Account > Preferences”
He can select a value for “Activate contextual assistance and associated data sending” field between: No / Anonymized / Contact Details

Given a platform without licenses
When the user go to “Configuration > Users > Contacts / Users  > Additional Information”
He can select a value for “Activate contextual assistance and associated data sending” field between: No / Anonymized / Contact Details

Given a platform with a valid license
When the user go to “Administration > Parameters > My Account > Preferences”
He can select a value for “Activate contextual assistance and associated data sending” field between: Anonymized / Contact Details

Given a platform with a valid license
When the user go to “Configuration > Users > Contacts / Users  > Additional Information”
He can select a value for “Activate contextual assistance and associated data sending” field between: Anonymized / Contact Details

## Checklist

- [x] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have made corresponding changes to the **documentation**.
- [ ] I have **rebased** my development branch on the base branch (master, maintenance).

2021-09-08 12:33 UTC, a-launois submitted a review, later dismissed

2021-09-08 15:16 UTC, lpinsivy requested changes

2021-09-08 15:16 UTC, lpinsivy commented on lang/fr_FR.UTF-8/LC_MESSAGES/help.po
> +"les informations de votre plateforme, mais votre alias et votre email seront anonymisé."
anonymisés

2021-09-09 06:46 UTC, a-launois approved these changes

2021-09-09 06:50 UTC, adr-mo approved these changes

2021-09-09 07:09 UTC, lpinsivy approved these changes

2021-09-09 07:10 UTC, merged