feat(Product Adoption): revert commit
centreon-archive/centreon-archived pull request #10138
Opened 2021-09-15 20:11 UTC by jeremyjaouen

## Description

Revert PR of user consent

**Fixes** #MON-10927

## Target serie

- [ ] 20.04.x
- [x] 20.10.x
- [ ] 21.04.x
- [ ] 21.10.x (master)

## Checklist

- [ ] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have made corresponding changes to the **documentation**.
- [ ] I have **rebased** my development branch on the base branch (master, maintenance).

2021-09-16 07:36 UTC, adr-mo requested changes

2021-09-16 07:36 UTC, adr-mo commented on lang/fr_FR.UTF-8/LC_MESSAGES/help.po
> -"Si l'option n'est pas activée l'utilisation de la nouvelle page de Monitoring Resource Status sera pleinement activée"
This part should not be deleted as it is part of something else (feature flipping)

2021-09-16 07:36 UTC, adr-mo commented on www/include/Administration/myAccount/formMyAccount.php
> +/* ------------------------ Topoogy ---------------------------- */
```suggestion
/* ------------------------ Topology ---------------------------- */
```

2021-09-16 07:47 UTC, adr-mo approved these changes

2021-09-20 07:02 UTC, kduret approved these changes

2021-09-20 07:28 UTC, merged