feat(Product Adoption): revert commit
centreon-archive/centreon-archived pull request #10136
Opened 2021-09-15 20:07 UTC by jeremyjaouen

## Description

This reverts commit ba44c89c2fd8dc4ec5d0c83130b6675a0d9d9a46.
**Fixes** #MON-10927

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [ ] 20.04.x
- [ ] 20.10.x
- [ ] 21.04.x
- [x] 21.10.x (master)

## Checklist

- [ ] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have made corresponding changes to the **documentation**.
- [ ] I have **rebased** my development branch on the base branch (master, maintenance).

2021-09-16 07:34 UTC, adr-mo requested changes

2021-09-16 07:34 UTC, adr-mo commented on lang/fr_FR.UTF-8/LC_MESSAGES/help.po
> -"Si l'option n'est pas activée l'utilisation de la nouvelle page de Monitoring Resource Status sera pleinement activée"
Careful this part should not be deleted as it is part of something else (feature flipping)

2021-09-16 07:46 UTC, adr-mo submitted a review, later dismissed

2021-09-17 09:12 UTC, adr-mo approved these changes, later dismissed

2021-09-17 09:13 UTC, kduret approved these changes

2021-09-17 09:13 UTC, adr-mo approved these changes

2021-09-17 09:27 UTC, merged