fix(conf) check if contact's notifications are enabled when exporting…
centreon-archive/centreon-archived pull request #10161
Opened 2021-09-23 10:54 UTC by a-launois

## Description
When you create a contact that should not receive mail, but is in a contact group where other users should receive notifications, the generation process blocks with an error.

## Type of change

- [X] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [ ] 20.04.x
- [X] 20.10.x
- [X] 21.04.x
- [X] 21.10.x (master)

<h2> How this pull request can be tested ? </h2>

1. Create a contact with “Enable Notifications” set to “No” and without notification commands,
2. Add this user as a “Notification receivers” for a service or a host,
3. (Or create a contact group, add this user to this contact group, and add this group as a “Notification receivers” for a service or a host
4. Generate the configuration of the Poller from which the service or host is monitoring.
5. Configuration files should generate without error

## Checklist

- [X] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have made corresponding changes to the **documentation**.
- [X] I have **rebased** my development branch on the base branch (master, maintenance).

2021-09-23 12:03 UTC, jeremyjaouen submitted a review, later dismissed

2021-09-24 08:58 UTC, callapa requested changes

2021-09-24 08:58 UTC, callapa commented on www/class/config-generate/contact.class.php
> +        if ($this->contacts[$contactId]['enable_notifications'] == '1') {
Please use a constant instead to be more readable
```suggestion
        if ($this->contacts[$contactId]['enable_notifications'] == self::.....) {
```

2021-09-24 08:58 UTC, callapa commented on www/class/config-generate/contact.class.php
> +            && $this->contacts[$contactId]['enable_notifications'] == '2'
Same remark as above

2021-09-24 15:02 UTC, callapa approved these changes

2021-09-29 08:50 UTC, adr-mo approved these changes

2021-09-29 09:41 UTC, merged