enh(UI): Add new tile with the last ok status
centreon-archive/centreon-archived pull request #10213
Opened 2021-09-29 09:37 UTC by Jordan91

## Description

As a user, I want to know for a resource not OK when was the last time it was OK.

**Fixes** # (issue)

A new tiles will be displayed for service in not OK state, nothing for resources in OK state.

<img width="539" alt="Capture d’écran 2021-09-29 à 10 27 17" src="https://user-images.githubusercontent.com/16045498/135243362-849e3928-15fc-4658-b8c4-66a9729c1bc2.png">
## Type of change

- [x] New functionality (non-breaking change)

## Target serie

- [x] 21.10.x (master)

<h2> How this pull request can be tested ? </h2>

Go to ressource status and selected resource with a non OK status, you can see now the new tile with informations about the last ok status for this resource.

2021-09-29 12:14 UTC, bdauria commented on www/front_src/src/Resources/Details/index.test.tsx
> +    expect(getByText(labelLastCheckWithOkStatus)).toBeInTheDocument();
```suggestion
```

This is already stated below

2021-09-30 07:52 UTC, bdauria submitted a review, later dismissed

2021-09-30 07:59 UTC, Thebarda approved these changes, later dismissed

2021-09-30 08:33 UTC, callapa requested changes

2021-09-30 08:33 UTC, callapa commented on config/packages/serializer/Centreon/Monitoring.Resource.yml
> +              lastTimeWithNoIssue:
```suggestion
        lastTimeWithNoIssue:
```

2021-09-30 08:37 UTC, bdauria submitted a review, later dismissed

2021-09-30 08:38 UTC, Thebarda submitted a review, later dismissed

2021-09-30 08:38 UTC, kduret requested changes

2021-09-30 08:38 UTC, kduret commented on src/Centreon/Infrastructure/Monitoring/Resource/Provider/HostProvider.php
>              h.notify AS `notification_enabled`
```suggestion
            h.notify AS `notification_enabled`,
```

2021-09-30 08:38 UTC, kduret commented on src/Centreon/Infrastructure/Monitoring/Resource/Provider/MetaServiceProvider.php
>              s.notify AS `notification_enabled`
```suggestion
            s.notify AS `notification_enabled`,
```

2021-09-30 08:38 UTC, kduret commented on src/Centreon/Infrastructure/Monitoring/Resource/Provider/ServiceProvider.php
>              s.notify AS `notification_enabled`
```suggestion
            s.notify AS `notification_enabled`,
```

2021-09-30 09:34 UTC, kduret approved these changes

2021-09-30 09:38 UTC, callapa approved these changes

2021-09-30 09:40 UTC, Thebarda approved these changes

2021-09-30 09:41 UTC, merged