Mon 7391 fix forbidden actions on remote server
centreon-archive/centreon-archived pull request #10211
Opened 2021-09-29 07:35 UTC by a-launois

## Description

On a remote server’s WUI, the poller config menu show all actions buttons (export conf, duplicate, delete ...) and icon buttons (enable/disable, edit monitoring engine conf).
Following page are accessible: 
The following topology pages are accessible : 
- p=60903 (engine configuration)
- p=60902 (config export)
- p=60901&o=c&server_id=x (poller configuration)
- p=60909 (broker configuration)

## Type of change

- [x] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [ ] 20.04.x
- [ ] 20.10.x
- [ ] 21.04.x
- [x] 21.10.x (master)

<h2> How this pull request can be tested ? </h2>
When on a remote server’s WUI:

1. in configuation > pollers list : no action should be possible, the link on a poller name should redirect to a page that show the poller conf detail in read only mode
2. following pages should be inaccessible:
- p=60903 (engine configuration)
- p=60902 (config export)
- p=60901&o=c&server_id=x (poller configuration edition)
- p=60909 (broker configuration)

## Checklist

- [x] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have made corresponding changes to the **documentation**.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2021-09-29 11:54 UTC, callapa requested changes

2021-09-29 11:54 UTC, callapa commented on www/include/configuration/configCentreonBroker/centreon-broker.php
> +/**
DRY !

2021-09-29 11:55 UTC, callapa requested changes

2021-09-29 11:55 UTC, callapa commented on www/include/configuration/configCentreonBroker/centreon-broker.php
> +
DRY !

2021-10-01 07:31 UTC, kduret approved these changes

2021-10-04 07:23 UTC, callapa approved these changes

2021-10-04 07:39 UTC, merged