Removed animation effect option in account parameters
centreon-archive/centreon-archived pull request #10329
Opened 2021-10-19 13:44 UTC by AssanDiomande

## Description

Fixes MON-11359

Removed animation effect option in account parameters

Commented line 140 of file www/include/Administration/myAccount/formMyAccount.php

## Type of change

- [x] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [ ] 20.04.x
- [ ] 20.10.x
- [ ] 21.04.x
- [x] 21.10.x (master)

<h2> How this pull request can be tested ? </h2>

* Create a downtime for a service who start immediatly
* Go to Monitoring > Status details > Services
* Move the cursor on the downtime icon
* Check if the animation is good or not

2021-10-19 13:57 UTC, callapa requested changes

2021-10-19 15:27 UTC, callapa requested changes
You need to create an upgrade SQL script that will remove the contact_js_effects column.

2021-10-19 17:11 UTC, kduret requested changes

2021-10-20 07:26 UTC, callapa requested changes

2021-10-20 15:34 UTC, callapa submitted a review, later dismissed

2021-10-21 07:14 UTC, kduret requested changes

2021-10-21 07:20 UTC, kduret approved these changes

2021-10-21 07:57 UTC, a-launois approved these changes

2021-10-21 08:01 UTC, merged