fix(login): Fixed quotation mark
centreon-archive/centreon-archived pull request #10347
Opened 2021-10-21 10:03 UTC by AssanDiomande

## Description

**Fixes** MON-11075

Fixed quotation mark

## Type of change

- [x] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [ ] 20.04.x
- [x] 20.10.x
- [x] 21.04.x
- [x] 21.10.x (master)

<h2> How this pull request can be tested ? </h2>

* create or update a ldap user whit a quote
* import this user in centreon
* try to connect to centreon with this user

2021-10-21 15:42 UTC, lpinsivy requested changes

2021-10-22 07:21 UTC, a-launois submitted a review, later dismissed

2021-10-22 07:25 UTC, lpinsivy submitted a review, later dismissed

2021-11-03 09:00 UTC, sc979 requested changes

2021-11-03 15:51 UTC, sc979 commented on www/include/configuration/configObject/contact/DB-Func.php
>              case 'contact_comment':
```suggestion
            case 'contact_comment':
            case 'contact_ldap_dn':
```

2021-11-03 15:51 UTC, sc979 commented on www/include/configuration/configObject/contact/DB-Func.php
> +            case 'contact_ldap_dn':
```suggestion
```

2021-11-04 09:23 UTC, sc979 approved these changes

2021-11-04 10:23 UTC, lpinsivy approved these changes

2021-11-05 08:59 UTC, adr-mo approved these changes

2021-11-05 09:00 UTC, merged