chore(deps): upgrade to symfony 5 and fosrestbundle 3
centreon-archive/centreon-archived pull request #10491
Opened 2021-12-14 12:39 UTC by kduret

## Description

upgrade to symfony 5 and fosrestbundle 3

**Fixes** MON-6124

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [x] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [ ] 20.10.x
- [ ] 21.04.x
- [ ] 21.10.x
- [x] 22.04.x (master)

<h2> How this pull request can be tested ? </h2>

Check CI

2021-12-21 08:44 UTC, kduret commented on src/Centreon/Domain/Contact/Contact.php
> +     * {@inheritDoc}
```suggestion
     * @inheritDoc
```

2021-12-21 13:50 UTC, callapa requested changes

2021-12-21 13:50 UTC, callapa commented on src/Security/SessionAPIAuthenticator.php
> +            throw new UserNotFoundException();
It is not the user that is not found but the session.

2021-12-21 13:50 UTC, callapa commented on src/Security/SessionAPIAuthenticator.php
> +        if (!$contact->isActive()) {
=== false is more readable

2021-12-21 13:50 UTC, callapa commented on src/Security/TokenAPIAuthenticator.php
> +        LocalProvider $localProvider
please complete PHPDoc

2021-12-21 13:52 UTC, callapa commented on src/Security/SessionAPIAuthenticator.php
> +            throw new UserNotFoundException();
You can separate, first try to find the session and then the user

2021-12-30 08:41 UTC, adr-mo approved these changes, later dismissed

2021-12-30 09:21 UTC, AssanDiomande submitted a review, later dismissed

2022-01-03 09:03 UTC, kduret commented on src/Centreon/Domain/Authentication/UseCase/Authenticate.php
> +        $_SESSION['centreon'] = &$legacySession;
```suggestion
        $_SESSION['centreon'] = $legacySession;
```

2022-01-03 09:59 UTC, callapa requested changes

2022-01-03 09:59 UTC, callapa commented on config/packages/Centreon.yaml
> +    debug_level: "%env(string:DEBUG_LEVEL)%"
```suggestion
    debug_level: "%env(int:DEBUG_LEVEL)%"
```

2022-01-03 09:59 UTC, callapa commented on src/Centreon/Domain/Authentication/UseCase/Authenticate.php
> +     * @param RequestStack $session
```suggestion
     * @param RequestStack $requestStack
```

2022-01-03 12:27 UTC, callapa submitted a review, later dismissed

2022-01-03 12:35 UTC, adr-mo approved these changes, later dismissed

2022-01-03 13:02 UTC, callapa approved these changes

2022-01-03 14:26 UTC, adr-mo approved these changes

2022-01-03 14:55 UTC, merged