Mon 11920 update composer
centreon-archive/centreon-archived pull request #10511
Opened 2021-12-22 13:45 UTC by AssanDiomande

## Description

Please include a short resume of the changes and what is the purpose of PR. Any relevant information should be added to help:
* **QA Team** (Quality Assurance) with tests.
* **reviewers** to understand what are the stakes of the pull request.

**Fixes** # (issue)

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [ ] 20.10.x
- [ ] 21.04.x
- [ ] 21.10.x
- [ ] 22.04.x (master)

<h2> How this pull request can be tested ? </h2>

Please describe the **procedure** to verify that the goal of the PR is matched. Provide clear instructions so that it can be **correctly tested**.

Any **relevant details** of the configuration to perform the test should be added.

## Checklist

- [ ] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have made corresponding changes to the **documentation**.
- [ ] I have **rebased** my development branch on the base branch (master, maintenance).

2021-12-22 15:04 UTC, callapa requested changes
Attention, you have downgraded the version of the library monolog/monolog.

2021-12-22 15:11 UTC, AssanDiomande commented
> Attention, you have downgraded the version of the library monolog/monolog.

I compared the version between this branch and develop and I got the same version (1.26.1)

2021-12-22 17:00 UTC, callapa requested changes

2021-12-22 17:00 UTC, callapa commented on composer.lock
> +            "version": "v3.3.1",
Please do not downgrade the version.

2021-12-23 09:53 UTC, kduret reviewed
Please set this PR as draft until it is not ready for review

2021-12-23 13:56 UTC, closed without merging