enh(autologin): verify that autologin is different than password
centreon-archive/centreon-archived pull request #10565
Opened 2022-01-14 13:50 UTC by jeremyjaouen

## Description

This PR intends to verify that autologin is different than password
**Fixes** # MON-12050

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [x] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [ ] 20.10.x
- [ ] 21.04.x
- [ ] 21.10.x
- [x] 22.04.x (master)

## Checklist

- [x] I have followed the **coding style guidelines** provided by Centreon
- [x] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [x] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have made corresponding changes to the **documentation**.
- [ ] I have **rebased** my development branch on the base branch (master, maintenance).

2022-01-14 14:21 UTC, kduret commented on www/include/Administration/myAccount/DB-Func.php
> +            && !empty($fields['contact_passwd'])
```suggestion
            ($result = $statement->fetch(\PDO::FETCH_ASSOC))
            && !empty($fields['contact_passwd'])
            && password_verify($fields['contact_autologin_key'], $result['password'])
```

2022-01-14 14:21 UTC, kduret commented on lib/Centreon/Object/Contact/Contact.php
> +                throw new \Exception('Your autologin key should be different than your current password');
```suggestion
                throw new \Exception(_('Your autologin key should be different than your current password'));
```

2022-01-14 14:21 UTC, kduret commented on www/include/Administration/myAccount/DB-Func.php
> +            $errors['contact_autologin_key'] = _($errorMessage);
```suggestion
            $errorMessage = _('Your new password and autologin key should be different');
            $errors['contact_passwd'] = $errorMessage;
            $errors['contact_autologin_key'] = $errorMessage;
```

2022-01-14 14:21 UTC, kduret commented on www/include/configuration/configObject/contact/DB-Func.php
> + * @return mixed
```suggestion
 * @return array<string,string>|bool
```

2022-01-14 14:21 UTC, kduret commented on www/include/Administration/myAccount/DB-Func.php
> + * @param array $fields
```suggestion
 * @param array $fields
 * @return array<string,string>|bool
```

2022-01-14 16:15 UTC, callapa requested changes

2022-01-14 16:15 UTC, callapa commented on www/include/Administration/myAccount/DB-Func.php
> +            empty($fields['contact_passwd'])
```suggestion
            !empty($fields['contact_passwd'])
```

2022-01-17 07:25 UTC, callapa requested changes

2022-01-17 07:25 UTC, callapa commented on www/include/Administration/myAccount/DB-Func.php
> +    return count($errors) > 0 ? $errors : true;
You cannot return an array or a Boolean value, you must make a choice.

2022-01-17 07:25 UTC, callapa commented on www/include/configuration/configObject/contact/DB-Func.php
> +    return count($errors) > 0 ? $errors : true;
You cannot return an array or a Boolean value, you must make a choice.

2022-01-17 07:33 UTC, kduret commented on www/include/Administration/myAccount/DB-Func.php
> +            && !empty($fields['contact_passwd'])
ueless comment :)

2022-01-17 07:56 UTC, callapa approved these changes

2022-01-17 07:59 UTC, adr-mo commented on lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgid "Your autologin key should be different than your current password"
Simple comment here, but I guess the "should" implies that it is not possible to set an autologin key = password. Therefore "should" could be replaced by "must" as it is a requirement

2022-01-17 08:01 UTC, adr-mo commented on www/include/Administration/myAccount/DB-Func.php
> + * @param array $fields
Could it be more precise that array ?

2022-01-17 08:01 UTC, adr-mo commented on www/include/configuration/configObject/contact/DB-Func.php
> + * @param array $fields
Could it be more precise that array ?

2022-01-17 08:10 UTC, adr-mo approved these changes

2022-01-17 08:28 UTC, kduret approved these changes

2022-01-17 08:44 UTC, merged