fix(reporting): sanitize inputs on init
centreon-archive/centreon-archived pull request #10594
Opened 2022-01-26 14:36 UTC by adr-mo

## Description

Sanitize inputs on initReport

**Fixes** # (issue)

## Type of change

- [x] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [x] 20.10.x
- [x] 21.04.x
- [x] 21.10.x
- [x] 22.04.x (master)

<h2> How this pull request can be tested ? </h2>

jira details

## Checklist

- [ ] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have made corresponding changes to the **documentation**.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2022-01-31 08:26 UTC, a-launois approved these changes, later dismissed

2022-01-31 09:09 UTC, AssanDiomande approved these changes, later dismissed

2022-02-01 09:33 UTC, a-launois submitted a review, later dismissed

2022-02-01 09:47 UTC, AssanDiomande submitted a review, later dismissed

2022-02-01 09:47 UTC, kduret commented on www/include/reporting/dashboard/initReport.php
> +}
```suggestion
$period = filter_var(
    $_POST['period'] ?? $_GET['period'] ?? '',
    FILTER_SANITIZE_STRING
);
```

2022-02-01 09:47 UTC, kduret commented on www/include/reporting/dashboard/initReport.php
> +if (isset($_POST['StartDate'])) {
same as above

2022-02-01 09:47 UTC, kduret commented on www/include/reporting/dashboard/initReport.php
> +if (isset($_POST['EndDate'])) {
same as above

2022-02-01 09:47 UTC, kduret commented on www/include/reporting/dashboard/initReport.php
> +    : "preset";
```suggestion
$period_choice = filter_var(
    $_POST["period_choice"] ?? 'preset',
    FILTER_SANITIZE_STRING
);
```

2022-02-01 16:43 UTC, adr-mo commented
@kduret all your feedbacks were applied 👍  thanks 💯

2022-02-02 07:51 UTC, kduret commented on www/include/reporting/dashboard/initReport.php
> +);
```suggestion
$period = filter_var(
    $_POST['period'] ?? $_GET['period'] ?? '',
    FILTER_SANITIZE_STRING
);
```

2022-02-02 07:51 UTC, kduret commented on www/include/reporting/dashboard/initReport.php
> +);
```suggestion
$get_date_start = filter_var(
    $_POST['StartDate'] ?? $_GET['StartDate'] ?? '',
    FILTER_SANITIZE_STRING
);
```

2022-02-02 07:51 UTC, kduret commented on www/include/reporting/dashboard/initReport.php
> +);
```suggestion
$get_date_start = filter_var(
    $_POST['EndDate'] ?? $_GET['EndDate'] ?? '',
    FILTER_SANITIZE_STRING
);
```

2022-02-02 12:58 UTC, callapa requested changes

2022-02-02 12:58 UTC, callapa commented on www/include/reporting/dashboard/initReport.php
> +);
```suggestion
$get_date_start = filter_var(
    $_GET['start'] ?? $_POST['StartDate'] ?? '',
    FILTER_SANITIZE_STRING
);
```

2022-02-02 15:08 UTC, adr-mo commented on www/include/reporting/dashboard/initReport.php
> +);
Done ✅  thanks (there was also a bad copy/paste on the variable name)

2022-02-02 16:03 UTC, kduret submitted a review, later dismissed

2022-02-02 16:27 UTC, callapa submitted a review, later dismissed

2022-02-07 09:58 UTC, kduret approved these changes

2022-02-07 10:13 UTC, AssanDiomande approved these changes

2022-02-07 13:06 UTC, merged