enh(host) handle templates in host update
centreon-archive/centreon-archived pull request #10603
Opened 2022-01-31 15:21 UTC by a-launois

## Description

Handle the addition of template in HD automatic analysis

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [x] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [ ] 20.10.x
- [ ] 21.04.x
- [ ] 21.10.x
- [x] 22.04.x (master)

## Checklist

- [x] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have made corresponding changes to the **documentation**.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2022-02-01 07:38 UTC, callapa requested changes

2022-02-01 07:38 UTC, callapa commented on src/Centreon/Infrastructure/HostConfiguration/Repository/HostConfigurationRepositoryRDB.php
> +        $existingTemplates = array_column($existingTemplates, 'host_name', 'host_tpl_id');
This is business code, it should not be in the repository

2022-02-07 14:29 UTC, callapa requested changes

2022-02-07 14:29 UTC, callapa commented on src/Centreon/Infrastructure/HostConfiguration/Repository/HostConfigurationRepositoryRDB.php
> +            throw new RepositoryException(sprintf(_('Template with id %d not found'), $templateId));
The problem can also come from the host_id

2022-02-07 14:29 UTC, callapa commented on src/Centreon/Infrastructure/HostConfiguration/Repository/HostConfigurationRepositoryRDB.php
> +            throw new RepositoryException(sprintf(_('Template %s not found'), $templateName));
The problem can also come from the host_id

2022-02-07 17:20 UTC, callapa approved these changes

2022-02-11 13:46 UTC, kduret approved these changes

2022-02-14 10:12 UTC, merged