add selected theme to user informations endpoint
centreon-archive/centreon-archived pull request #10641
Opened 2022-02-01 14:53 UTC by hyahiaoui-ext

## Description
This PR intends to add selected theme property to the user infomations endpoint.

**Fixes** # MON-12164

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [x] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [ ] 20.10.x
- [ ] 21.04.x
- [ ] 21.10.x
- [x] 22.04.x (master)

## Checklist

- [x] I have followed the **coding style guidelines** provided by Centreon
- [x] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have made corresponding changes to the **documentation**.
- [ ] I have **rebased** my development branch on the base branch (master, maintenance).

2022-02-02 16:27 UTC, kduret reviewed
could you update api documentation in https://github.com/centreon/centreon/blob/MON-11932-dark-mode/doc/API/centreon-api-v22.04.yaml#L708

2022-02-02 17:04 UTC, hyahiaoui-ext commented
> could you update api documentation in https://github.com/centreon/centreon/blob/MON-11932-dark-mode/doc/API/centreon-api-v22.04.yaml#L708

It's done :) !

2022-02-02 17:25 UTC, kduret approved these changes

2022-02-03 09:54 UTC, callapa requested changes

2022-02-03 09:54 UTC, callapa commented on src/Centreon/Domain/Contact/Contact.php
> +     * @var string
```suggestion
     * @var string|null
```

2022-02-03 09:54 UTC, callapa commented on src/Centreon/Domain/Contact/Contact.php
> +     * @return string
```suggestion
     * @return string|null
```

2022-02-03 09:54 UTC, callapa commented on src/Centreon/Domain/Contact/Contact.php
> +    public function getTheme(): string
```suggestion
    public function getTheme(): ?string
```

2022-02-08 12:32 UTC, callapa approved these changes

2022-02-11 10:54 UTC, merged