Mon 12058
centreon-archive/centreon-archived pull request #10671
Opened 2022-02-07 09:08 UTC by ataghzout

## Description

Exportation of all color variables to centralise style to make it easier to add a new theme and maintain it. 

**Fixes** # MON-12058

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [x] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [ ] 20.10.x
- [ ] 21.04.x
- [ ] 21.10.x
- [x] 22.04.x (master)

<h2> How this pull request can be tested ? </h2>

Please describe the **procedure** to verify that the goal of the PR is matched. Provide clear instructions so that it can be **correctly tested**.

Any **relevant details** of the configuration to perform the test should be added.

## Checklist

- [x] I have followed the **coding style guidelines** provided by Centreon
- [x] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [x] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have made corresponding changes to the **documentation**.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2022-02-08 16:45 UTC, callapa requested changes

2022-02-08 16:45 UTC, callapa commented on www/Themes/Centreon-Light/Variables-css/variables.css
> +    --ui-selectable-helper-border-color: #black;
wrong value: black or #000, not #black

2022-02-11 09:59 UTC, callapa approved these changes

2022-02-18 13:17 UTC, kduret reviewed
need consistency around `:` (ex: space before and after

2022-02-18 13:17 UTC, kduret commented on www/Themes/Centreon-Light/Variables-css/color-variables.css
> +    --color-persian-green : #00a499 ;
```suggestion
    --color-persian-green : #00a499;
```

2022-02-18 13:28 UTC, jeremyjaouen approved these changes

2022-02-24 08:41 UTC, merged