enh(log) improve session management
centreon-archive/centreon-archived pull request #10687
Opened 2022-02-08 11:00 UTC by AssanDiomande

## Description

**Fixes** MON-12197

Avoid deadlocks by improving session management in code

## Type of change

- [x] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [ ] 20.10.x
- [ ] 21.04.x
- [x] 21.10.x
- [x] 22.04.x (master)

<h2> How this pull request can be tested ? </h2>

See how to test section in [jira ticket](https://centreon.atlassian.net/jira/software/c/projects/MON/boards/113?modal=detail&selectedIssue=MON-12197&sprint=654)

2022-02-08 11:25 UTC, AssanDiomande commented on www/class/centreonSession.class.php
> -    }
to be discussed

2022-02-08 11:40 UTC, kduret commented on www/class/centreonSession.class.php
> -    }
can be removed

2022-02-08 11:58 UTC, AssanDiomande commented on www/class/centreonSession.class.php
> -    }
done

2022-02-08 12:02 UTC, kduret commented on www/class/centreonSession.class.php
> +        return !empty($session) ? true : false;
```suggestion
        return $prepare->fetch(\PDO::FETCH_ASSOC) !== false;
```

2022-02-08 15:36 UTC, kduret approved these changes, later dismissed

2022-02-14 12:40 UTC, a-launois requested changes

2022-02-14 12:40 UTC, a-launois commented on www/class/centreonSession.class.php
> +            return false;
docblock still says method should return an integer

2022-02-14 17:19 UTC, a-launois approved these changes

2022-02-15 09:22 UTC, kduret approved these changes

2022-02-15 09:26 UTC, merged