adabt tables and border to dark mode
centreon-archive/centreon-archived pull request #10802
Opened 2022-02-28 09:45 UTC by yayassssine

## Description

adabt tables and border to dark mode
Centreon Dark mode Configuration and Admin listings

**Fixes** #MON-11994

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [x] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [ ] 20.10.x
- [ ] 21.04.x
- [ ] 21.10.x
- [x] 22.04.x (master)

<h2> How this pull request can be tested ? </h2>

Please describe the **procedure** to verify that the goal of the PR is matched. Provide clear instructions so that it can be **correctly tested**.

Any **relevant details** of the configuration to perform the test should be added.

## Checklist

- [x] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have made corresponding changes to the **documentation**.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2022-02-28 09:55 UTC, kduret commented on www/Themes/Generic-theme/style.css
> +color:#fff}
I guess there is already a variable for `#fff`
```suggestion
.service_ok,.host_up, .success  {
    background-color: var(--service-ok-host-up-success-background-color);
    color: #fff;
}
```

2022-02-28 09:55 UTC, kduret commented on www/Themes/Generic-theme/color.css
> +.ListTable, .ListTableMedium, .ListTableSmall {border-color: var(--list-table-border-color); border-radius: 5px}
```suggestion
.ListTable, .ListTableMedium, .ListTableSmall {
    border-color: var(--list-table-border-color);
    border-radius: 5px;
}
```

2022-02-28 16:17 UTC, callapa requested changes

2022-02-28 16:17 UTC, callapa commented on www/Themes/Generic-theme/style.css
> +color:var(--color-white)}
do not set a specific colour in the generic theme

2022-03-02 14:50 UTC, callapa approved these changes

2022-03-02 14:50 UTC, merged