fix(conf/export) allow export script files to be required multiple times
centreon-archive/centreon-archived pull request #10822
Opened 2022-03-07 13:58 UTC by a-launois

## Description

As includeFile() is called in a loop, we need to be able to require the same file multiple times

printDebug() was moved to prevent function redeclarations errors

## Type of change

- [x] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [ ] 20.10.x
- [ ] 21.04.x
- [ ] 21.10.x
- [x] 22.04.x (master)

## Checklist

- [x] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have made corresponding changes to the **documentation**.
- [ ] I have **rebased** my development branch on the base branch (master, maintenance).

2022-03-08 07:01 UTC, callapa requested changes

2022-03-08 07:01 UTC, callapa commented on src/Centreon/Infrastructure/HostConfiguration/Repository/HostConfigurationRepositoryRDB.php
> +        $request = $this->translateDbName("DELETE FROM `:db`.ns_host_relation WHERE host_host_id = :host_id");
I prefer that you leave the previous relationship

2022-03-09 08:50 UTC, jeremyjaouen commented on www/include/configuration/configGenerate/common-Func.php
> +    $nagios_bin = $DBRESULT_Servers->fetch();
```suggestion
    $nagios_bin = $DBRESULT_Servers->fetch();
```
I know it's a copy paste but could you handle variables in camelCase :pray:

2022-03-09 09:05 UTC, callapa approved these changes

2022-03-09 09:29 UTC, jeremyjaouen approved these changes

2022-03-09 12:49 UTC, merged