enh(conf/broker) new unified_sql output in broker configuration
centreon-archive/centreon-archived pull request #10838
Opened 2022-03-09 14:33 UTC by a-launois

## Description

Deprecate broker outputs:
- SQL - Broker SQL database
- Storage - Perfdata Generator (Centreon Storage) 

Create broker output : 
- Storage - Unified SQL

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [x] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [ ] 20.10.x
- [ ] 21.04.x
- [ ] 21.10.x
- [x] 22.04.x (master)

## Checklist

- [x] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have made corresponding changes to the **documentation**.
- [ ] I have **rebased** my development branch on the base branch (master, maintenance).

2022-03-14 08:53 UTC, jeremyjaouen requested changes

2022-03-14 08:53 UTC, jeremyjaouen commented on www/install/php/Update-22.04.0-beta.1.php
> +    );
```suggestion
    $pearDB->query(
        "UPDATE `cb_type` set type_name = 'Perfdata Generator (Centreon Storage) - DEPRECATED'
            WHERE type_shortname = 'storage'"
    );
    $pearDB->query(
        "UPDATE `cb_type` set type_name = 'Broker SQL database - DEPRECATED'
            WHERE type_shortname = 'sql'"
    );
```
No need to store your query in a variable as you don't do anything with it

2022-03-14 08:53 UTC, jeremyjaouen commented on www/install/php/Update-22.04.0-beta.1.php
> +    $statement = $pearDB->query(
```suggestion
    $pearDB->query(
```

2022-03-14 08:53 UTC, jeremyjaouen commented on www/install/php/Update-22.04.0-beta.1.php
> +    $statement = $pearDB->query(
```suggestion
    $pearDB->query(
```

2022-03-14 08:53 UTC, jeremyjaouen commented on www/install/php/Update-22.04.0-beta.1.php
> +    $statement = $pearDB->query("INSERT INTO options VALUES ('unified_sql_db_type', 'mysql')");
```suggestion
    $pearDB->query("INSERT INTO options VALUES ('unified_sql_db_type', 'mysql')");
```

2022-03-14 08:53 UTC, jeremyjaouen commented on www/install/php/Update-22.04.0-beta.1.php
> +    $statement = $pearDB->query(
```suggestion
    $pearDB->query(
```

2022-03-14 12:40 UTC, jeremyjaouen commented on www/install/php/Update-22.04.0-beta.1.php
> + * @return void
```suggestion
```

2022-03-14 12:40 UTC, jeremyjaouen submitted a review, later dismissed

2022-03-15 07:02 UTC, jeremyjaouen approved these changes, later dismissed

2022-03-15 07:25 UTC, kduret submitted a review, later dismissed

2022-03-16 16:17 UTC, kduret submitted a review, later dismissed

2022-03-16 16:40 UTC, kduret approved these changes, later dismissed

2022-03-16 16:43 UTC, callapa requested changes

2022-03-16 16:43 UTC, callapa commented on www/install/php/Update-22.04.0-beta.1.php
> +    }
Please to use the prepare method with the bindParam instead

2022-03-17 08:14 UTC, jeremyjaouen approved these changes, later dismissed

2022-03-17 08:42 UTC, AssanDiomande approved these changes, later dismissed

2022-03-17 17:15 UTC, kduret approved these changes

2022-03-17 17:17 UTC, AssanDiomande approved these changes

2022-03-17 17:18 UTC, callapa approved these changes

2022-03-17 17:20 UTC, merged