changing icons from png/gif to svg
centreon-archive/centreon-archived pull request #10847
Opened 2022-03-10 09:37 UTC by yayassssine

## Description

changing all icons from format png to new files svg

**Fixes** #MON-12612

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [x] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [ ] 20.10.x
- [ ] 21.04.x
- [ ] 21.10.x
- [x] 22.04.x (master)

<h2> How this pull request can be tested ? </h2>

Please describe the **procedure** to verify that the goal of the PR is matched. Provide clear instructions so that it can be **correctly tested**.

Any **relevant details** of the configuration to perform the test should be added.

## Checklist

- [x] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have made corresponding changes to the **documentation**.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2022-03-11 15:40 UTC, kduret commented on www/Themes/Generic-theme/Variables-css/variables.css
> +    --ico-16-all-services:var(--color-primary-dark);
move it after `--ico-14-fill-color` to make it consistent with light theme

2022-03-11 15:40 UTC, kduret commented on www/include/common/templates/cloneHost.ihtml
> +            <path d="M3 17.25V21h3.75L17.81 9.94l-3.75-3.75L3 17.25zM20.71 7.04c.39-.39.39-1.02 0-1.41l-2.34-2.34c-.39-.39-1.02-.39-1.41 0l-1.83 1.83 3.75 3.75 1.83-1.83z"/>
```suggestion
                <path d="M0 0h24v24H0z" fill="none"/>
                <path d="M3 17.25V21h3.75L17.81 9.94l-3.75-3.75L3 17.25zM20.71 7.04c.39-.39.39-1.02 0-1.41l-2.34-2.34c-.39-.39-1.02-.39-1.41 0l-1.83 1.83 3.75 3.75 1.83-1.83z"/>
```

2022-03-11 15:40 UTC, kduret commented on www/include/common/templates/cloneMacro.ihtml
> +                                        </svg>
fix indent

2022-03-11 15:40 UTC, kduret commented on www/include/configuration/configObject/host/listHost.ihtml
> +</g></g></svg>                </a>
fix indent

2022-03-11 15:40 UTC, kduret commented on www/include/configuration/configObject/service/formService.ihtml
> +                                </svg>
fix indent

2022-03-11 15:40 UTC, kduret commented on www/include/home/customViews/index.ihtml
>      </div>
fix indent

2022-03-11 15:40 UTC, kduret commented on www/include/monitoring/status/HostGroups/templates/hostGroup.ihtml
> +                    </span>
fix indent

2022-03-15 08:40 UTC, kduret commented on www/include/common/javascript/jquery/plugins/select2/js/select2.min.js
> +/*! Select2 4.0.3 | https://github.com/select2/select2/blob/master/LICENSE.md */
js file is not minified anymore

2022-03-25 08:56 UTC, callapa requested changes
Use the SVG file instead wherever possible

2022-03-25 08:56 UTC, callapa commented on www/include/common/javascript/centreon/brokerConfig.js
> +        var svg = jQuery('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"  class="ico-14-circle-cross">\n' +
Use the SVG file instead

2022-03-25 08:56 UTC, callapa commented on www/include/common/javascript/centreon/centreon-select2-optgroup.js
> +              '</svg>'
Use the SVG file instead

2022-03-25 08:56 UTC, callapa commented on www/include/common/javascript/centreon/centreon-select2-optgroup.js
> +              '                </svg>');
Use the SVG file instead

2022-03-25 08:56 UTC, callapa commented on www/include/common/javascript/centreon/centreon-select2.js
> +              '</svg>');
Use the SVG file instead

2022-03-25 08:56 UTC, callapa commented on www/include/common/javascript/centreon/centreon-select2.js
> +              '                </svg>');
Use the SVG file instead

2022-03-25 08:56 UTC, callapa commented on www/include/common/javascript/centreon/popin.js
> +            '                </svg></a>'),
Use the SVG file instead

2022-03-25 08:56 UTC, callapa commented on www/include/common/templates/clone.ihtml
> +                </svg>
Use the SVG file instead

2022-04-15 09:53 UTC, closed without merging