fix(poller): Fixed SQL and added access rights checking
centreon-archive/centreon-archived pull request #10841
Opened 2022-03-09 16:16 UTC by callapa

## Description

Fixed SQL and added access rights checking

## Type of change

- [x] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [x] 20.10.x
- [x] 21.04.x
- [ ] 21.10.x
- [ ] 22.04.x (master)

## Checklist

- [x] I have followed the **coding style guidelines** provided by Centreon
- [x] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [x] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have made corresponding changes to the **documentation**.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2022-03-09 21:36 UTC, Nohzoh approved these changes

2022-03-10 09:21 UTC, kduret approved these changes

2022-03-15 14:02 UTC, sc979 requested changes

2022-03-15 14:02 UTC, sc979 commented on Jenkinsfile
> -
Kindly restore this mandatory part. As you can see, the pipeline failures are not related to this step

2022-03-17 09:28 UTC, sc979 approved these changes

2022-03-21 12:06 UTC, merged