feat(api): list authentication provider configurations
centreon-archive/centreon-archived pull request #10852
Opened 2022-03-11 08:49 UTC by kduret

## Description

list authentication provider configurations

**Fixes** MON-12527

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [x] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [ ] 20.10.x
- [ ] 21.04.x
- [ ] 21.10.x
- [x] 22.04.x (master)

2022-03-11 09:38 UTC, jeremyjaouen requested changes

2022-03-11 09:38 UTC, jeremyjaouen commented on doc/API/centreon-api-v22.04.yaml
> +                      example: "/centreon"
still returned ?

2022-03-11 09:38 UTC, jeremyjaouen commented on src/Core/Application/Security/UseCase/FindProviderConfigurations/FindProviderConfigurations.php
> +        }
manage translation

2022-03-11 09:38 UTC, jeremyjaouen commented on src/Core/Application/Security/UseCase/FindProviderConfigurations/ProviderResponse/LocalProviderResponse.php
> +        return 'local';
```suggestion
        return LocalProvider::NAME;
```

2022-03-11 09:38 UTC, jeremyjaouen commented on src/Core/Application/Security/UseCase/FindProviderConfigurations/ProviderResponse/OpenIdProviderResponse.php
> +        return 'openid';
```suggestion
        return OpenIdConfiguration::NAME;
```

2022-03-11 09:38 UTC, jeremyjaouen commented on src/Core/Application/Security/UseCase/FindProviderConfigurations/ProviderResponse/OpenIdProviderResponse.php
> +
```suggestion
```
not needed in response

2022-03-11 09:38 UTC, jeremyjaouen commented on src/Core/Application/Security/UseCase/FindProviderConfigurations/ProviderResponse/OpenIdProviderResponse.php
> +    public ?string $loginClaim;
```suggestion
```

not needed in response

2022-03-11 09:38 UTC, jeremyjaouen commented on src/Core/Application/Security/UseCase/FindProviderConfigurations/ProviderResponse/OpenIdProviderResponse.php
> +
```suggestion
```
not needed in response

2022-03-11 12:57 UTC, kduret reviewed
check authentication issue when session is expired

2022-03-11 12:57 UTC, kduret commented on config/packages/Centreon.yaml
> +            tags: ['authentication.presenters']
```suggestion
            tags: ['authentication.provider.presenters']
```

2022-03-11 12:57 UTC, kduret commented on config/packages/Centreon.yaml
> +        arguments: [!tagged_iterator 'authentication.presenters']
```suggestion
        arguments: [!tagged_iterator 'authentication.provider.presenters']
```

2022-03-11 12:57 UTC, kduret commented on src/Core/Application/Security/UseCase/FindProviderConfigurations/FindProviderConfigurations.php
> +        }
split in privzte method and describe in phpdoc

2022-03-11 12:57 UTC, kduret commented on src/Core/Application/Security/UseCase/FindProviderConfigurations/FindProviderConfigurations.php
> +        }
or just comment block

2022-03-11 12:57 UTC, kduret commented on src/Core/Domain/Security/ProviderConfiguration/OpenId/Model/OpenIdConfiguration.php
> +    private ?int $id;
Suggestion but not mandatory here : Create NewOpenIdConfiguration model which does not contain `id` property

2022-03-11 12:57 UTC, kduret commented on src/Core/Infrastructure/Security/Api/FindProviderConfigurations/ProviderPresenter/LocalProviderPresenter.php
> +    public function __construct(private UrlGeneratorInterface $router)
add phpdoc

2022-03-11 12:57 UTC, kduret commented on src/Core/Infrastructure/Security/Api/FindProviderConfigurations/ProviderPresenter/OpenIdProviderPresenter.php
> +    public function __construct(private UrlGeneratorInterface $router)
add phpdoc

2022-03-11 12:57 UTC, kduret commented on src/Core/Infrastructure/Security/ProviderConfiguration/Local/Repository/DbConfigurationFactory.php
> +        $localConfiguration =  (new Configuration($securityPolicy))
```suggestion
        $localConfiguration = (new Configuration($securityPolicy))
```

2022-03-11 12:57 UTC, kduret commented on tests/php/Core/Application/Security/UseCase/LoginSession/LoginSessionTest.php
> +        $this->expectExceptionMessage('Provider configuration (local) not found');
call static method

2022-03-11 12:57 UTC, kduret commented on tests/php/Security/Domain/Authentication/ProviderServiceTest.php
> +        $this->expectExceptionMessage("Error while searching provider configuration: 'local'");
call static exception method

2022-03-11 15:19 UTC, kduret commented on tests/php/Core/Application/Security/UseCase/FindProviderConfigurations/FindProviderConfigurationsTest.php
> +        ->willThrowException(New \Exception($errorMessage));
```suggestion
        ->willThrowException(new \Exception($errorMessage));
```

2022-03-11 20:13 UTC, jeremyjaouen commented on src/Security/SessionAPIAuthenticator.php
> +        $this->sessionRepository->deleteExpiredSession();
this should be after isValidToken as isValidToken will check token validity and refresh it if possible (if the expired token is deleted we cannot refresh it)

2022-03-14 09:10 UTC, callapa approved these changes

2022-03-14 09:29 UTC, a-launois approved these changes

2022-03-14 09:30 UTC, merged