retrieve sql update files from dev-21.10.x
centreon-archive/centreon-archived pull request #10859
Opened 2022-03-14 08:29 UTC by a-launois

## Description

Add missing upgrade scripts for 21.10.x in develop

## Type of change

- [x] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [ ] 20.10.x
- [ ] 21.04.x
- [ ] 21.10.x
- [x] 22.04.x (master)

## Checklist

- [ ] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have made corresponding changes to the **documentation**.
- [ ] I have **rebased** my development branch on the base branch (master, maintenance).

2022-03-15 17:01 UTC, AssanDiomande approved these changes, later dismissed

2022-03-16 07:34 UTC, kduret submitted a review, later dismissed

2022-03-16 13:07 UTC, a-launois commented on www/install/php/Update-21.10.2.php
> +    $errorMessage = 'Unable to delete logger entry in cb_tag';
Delete this part

2022-03-16 13:11 UTC, a-launois commented on www/install/php/Update-21.10.2.php
> +    ");
Delete

2022-03-16 13:14 UTC, a-launois commented on www/install/php/Update-21.10.4.php
> +        SET `description` = 'Time in seconds to wait between each connection attempt. The default value is 30s.'
Time in seconds to wait between each connection attempt (Default value: 30s).
```suggestion
        SET `description` = 'Time in seconds to wait between each connection attempt (Default value: 30s).'
```

2022-03-16 13:18 UTC, a-launois commented on www/install/php/Update-21.10.4.php
> +    $statement = $pearDB->query("DELETE FROM cb_tag WHERE tagname = 'logger'");
```suggestion
```

2022-03-16 14:09 UTC, AssanDiomande submitted a review, later dismissed

2022-03-16 15:02 UTC, kduret commented on www/install/php/Update-21.10.2.php
> +
```suggestion
```

2022-03-16 15:03 UTC, kduret submitted a review, later dismissed

2022-03-16 15:15 UTC, a-launois commented on www/install/php/Update-21.10.2.php
> +
```suggestion
```

2022-03-17 17:22 UTC, callapa requested changes, later dismissed

2022-03-17 17:22 UTC, callapa commented on www/install/php/Update-21.10.4.php
> +    $pearDB->commit();
As there was only one rollback, you only need to use one commit and one transaction.
```suggestion
```

2022-03-17 17:22 UTC, callapa commented on www/install/php/Update-21.10.4.php
> +    $pearDB->beginTransaction();
```suggestion
```

2022-03-25 06:34 UTC, jeremyjaouen approved these changes

2022-03-25 08:54 UTC, AssanDiomande approved these changes

2022-03-25 11:06 UTC, merged