enh(api): implements infrastructure and model validation for update websso configuration use case
centreon-archive/centreon-archived pull request #10870
Opened 2022-03-16 13:40 UTC by jeremyjaouen

## Description

This PR intends to implements infrastructure and model validation for update websso configuration use case 
**Fixes** # MON-12647

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [x] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [ ] 20.10.x
- [ ] 21.04.x
- [ ] 21.10.x
- [x] 22.04.x (master)

## Checklist

- [x] I have followed the **coding style guidelines** provided by Centreon
- [x] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [x] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have made corresponding changes to the **documentation**.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2022-03-16 16:12 UTC, callapa requested changes

2022-03-16 16:12 UTC, callapa commented on tests/php/Core/Application/Security/ProviderConfiguration/WebSSO/UpdateWebSSOConfiguration/UseCase/UpdateWebSSOConfigurationTest.php
> +    $updateWebSSOConfigurationRequest->trustedClientAddresses = ["abcd_.@"];
```suggestion
    $badIpAddress = "abcd_.@";
    $updateWebSSOConfigurationRequest->trustedClientAddresses = [$badIpAddress];
```

2022-03-16 16:12 UTC, callapa commented on tests/php/Core/Application/Security/ProviderConfiguration/WebSSO/UpdateWebSSOConfiguration/UseCase/UpdateWebSSOConfigurationTest.php
> +                "abcd_.@",
```suggestion
                $badIpAddress,
```

2022-03-16 16:12 UTC, callapa commented on www/install/php/Update-22.04.0-beta.1.php
> +    $pearDB->beginTransaction();
Do not put the transaction in this function and include other previous SQL queries that may be transactional.

2022-03-17 09:27 UTC, kduret approved these changes

2022-03-17 12:13 UTC, kduret approved these changes

2022-03-17 14:23 UTC, AssanDiomande approved these changes

2022-03-28 09:34 UTC, callapa approved these changes

2022-03-28 09:58 UTC, merged