fix(UI): Centreon is slowed down
centreon-archive/centreon-archived pull request #10902
Opened 2022-03-25 11:32 UTC by Thebarda

## Description

This fixes Pendo initialization requests flood when the browser is offline.
This also reworks the pendo script to handle it in a React environment 

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [x] 20.10.x
- [x] 21.04.x
- [x] 21.10.x
- [x] 22.04.x (master)

<h2> How this pull request can be tested ? </h2>

- -> Pendo should send data as before
- Turn off your wifi
- -> Centreon pages are displayed as normal (not slowed down)

## Checklist

- [x] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have made corresponding changes to the **documentation**.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2022-03-25 11:58 UTC, bdauria commented on www/front_src/src/App/usePendo.ts
> +const oneDay = 24 * 60 * 60 * 1000;
```suggestion
const oneDayInMs = 24 * 60 * 60 * 1000;
```

2022-03-25 13:55 UTC, bdauria approved these changes

2022-03-31 08:18 UTC, bdauria approved these changes, later dismissed

2022-03-31 08:37 UTC, jdelpierre approved these changes, later dismissed

2022-04-05 10:33 UTC, lpinsivy requested changes
Pendo needs to be loaded in footerPart.php too due to iframe!

2022-04-07 15:49 UTC, bdauria commented on www/front_src/src/App/usePendo.ts
> +  const offline = (): void => {
function names should be verb (goOnline / goOffline would do for instance)

2022-04-07 15:58 UTC, bdauria approved these changes

2022-04-07 15:58 UTC, bdauria commented on www/front_src/src/App/usePendo.ts
> +  const offline = (): void => {
function names should be verb (goOnline / goOffline would do for instance)

2022-04-07 16:25 UTC, jdelpierre approved these changes

2022-04-12 11:27 UTC, lpinsivy approved these changes

2022-04-12 11:27 UTC, merged