fix(sec): avoid sql injection in virtual metric form
centreon-archive/centreon-archived pull request #10997
Opened 2022-04-20 08:23 UTC by kduret

## Description

avoid sql injection in virtual metric form

**Fixes** MON-12446

## Type of change

- [x] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [x] 20.10.x
- [x] 21.04.x
- [x] 21.10.x
- [x] 22.04.x (master)

2022-04-22 08:00 UTC, callapa requested changes

2022-04-22 08:18 UTC, kduret commented on www/include/views/virtualMetrics/DB-Func.php
> +    $indexId = isset($ret["host_id"]) && $ret["host_id"] !== null
getIndexIdFromHostServiceId expect a string, so we should check if it's not null

2022-04-22 08:19 UTC, kduret commented on www/include/views/virtualMetrics/DB-Func.php
> +        isset($ret["comment"]) && $ret["comment"] != null
htmlentities expects a string, so we should check if it's not null

2022-04-22 08:19 UTC, kduret commented on www/include/views/virtualMetrics/DB-Func.php
> +        isset($ret["vmetric_name"]) && $ret["vmetric_name"] != null
htmlentities expects a string, so we should check if it's not null

2022-04-22 08:20 UTC, kduret commented on www/include/views/virtualMetrics/DB-Func.php
> +        isset($ret["comment"]) && $ret["comment"] != null
htmlentities expects a string, so we should check if it's not null

2022-04-22 08:20 UTC, kduret commented on www/include/views/virtualMetrics/DB-Func.php
> +        isset($ret["vmetric_name"]) && $ret["vmetric_name"] != null
htmlentities expects a string, so we should check if it's not null

2022-04-22 08:20 UTC, kduret commented on www/include/views/virtualMetrics/DB-Func.php
> +        : null;
getIndexIdFromHostServiceId expects a string, so we should check if it's not null

2022-04-25 07:20 UTC, callapa approved these changes

2022-04-25 07:25 UTC, jeremyjaouen approved these changes

2022-04-25 07:28 UTC, merged