enh(conf) handle new centengine logger in configuration
centreon-archive/centreon-archived pull request #11013
Opened 2022-04-21 16:19 UTC by a-launois

## Description
Handle logger V2 in centengine configuration form and export

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [x] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [ ] 20.10.x
- [ ] 21.04.x
- [ ] 21.10.x
- [x] 22.04.x (master)

## Checklist

- [ ] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have made corresponding changes to the **documentation**.
- [ ] I have **rebased** my development branch on the base branch (master, maintenance).

2022-04-28 14:45 UTC, kduret commented on lib/perl/centreon/script/centreonSyncArchives.pm
> +        $data->{log_archive_path} =~ s/(.*)\/.*/$1\/archives\//;
```suggestion
        $data->{log_archive_path} =~ s#(.*)/.*#$1/archives/#;
```

2022-04-28 14:45 UTC, kduret commented on src/CentreonRemote/Domain/Resources/DefaultConfig/CfgNagiosLogger.php
> +
missing license header

2022-04-28 14:45 UTC, kduret commented on src/CentreonRemote/Domain/Resources/RemoteConfig/CfgNagiosLogger.php
> +
missing license header

2022-04-28 14:45 UTC, kduret commented on www/class/centreon-clapi/centreonEngineCfg.class.php
> +            } elseif ($params[1] === 'logger_version' && $params['2'] === 'log_v2_enabled') {
```suggestion
            } elseif ($params[1] === 'logger_version' && $params[2] === 'log_v2_enabled') {
```

2022-04-28 14:45 UTC, kduret commented on www/class/config-generate/engine.class.php
> +     *  If log Vé enabled, set logger V2 configuration and unset logger legacy elements
```suggestion
     *  If log V2 enabled, set logger V2 configuration and unset logger legacy elements
```

2022-04-28 14:45 UTC, kduret commented on www/include/configuration/configNagios/formNagios.php
> +$nagios_log_v2 = [];
use camelcase

2022-04-28 14:45 UTC, kduret commented on www/include/configuration/configNagios/formNagios.php
> +        $nagios_log_v2 = $statement->fetch();
need to check if fetch returns false

2022-04-29 08:27 UTC, a-launois commented on lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +
Add translation for other languages

2022-04-29 08:27 UTC, a-launois commented on src/CentreonRemote/Domain/Resources/RemoteConfig/CfgNagiosLogger.php
> + *
use Default CfgNagiosLogger

2022-04-29 08:38 UTC, a-launois commented on www/class/centreon-clapi/centreonEngineCfg.class.php
> +    public function insertRelations(int $nagiosId): void
```suggestion
    /**
     * This method is automatically called from centreonObject
     * @param int $nagiosId
     */
    public function insertRelations(int $nagiosId): void
```

2022-04-29 08:39 UTC, a-launois commented on www/class/centreon-clapi/centreonEngineCfg.class.php
> +            $statement->execute();
```suggestion
                "UPDATE cfg_nagios_logger SET `{$params[1]}` = :paramValue WHERE cfg_nagios_id = :cfgNagiosId"
            );
            $statement->bindValue(':paramValue', $params[2], \PDO::PARAM_STR);
            $statement->bindValue(':cfgNagiosId', $nagiosId, \PDO::PARAM_INT);
            $statement->execute();
```

2022-04-29 08:48 UTC, a-launois commented on www/install/php/Update-22.04.0-beta.1.php
> +        "CREATE TABLE IF NOT EXISTS `cfg_nagios_logger` (
Move create in sql file

2022-04-29 08:49 UTC, a-launois commented on www/include/configuration/configNagios/DB-Func.php
> +function insertLoggerV2Cfg(CentreonDB $pearDB, array $ret, int $nagiosId): void
change $ret for $data when possible for more clarity

2022-04-29 09:21 UTC, a-launois commented on www/class/centreon-clapi/centreonEngineCfg.class.php
> +            $setUpdateParams = true;
```suggestion
            $canUpdateParams = true;
```

2022-04-29 12:30 UTC, callapa requested changes

2022-04-29 12:37 UTC, callapa submitted a review, later dismissed

2022-05-02 09:04 UTC, a-launois commented on www/install/php/Update-22.04.0-beta.1.php
> +    // Add custom_configuration to provider configurations
```suggestion
```

2022-05-03 14:41 UTC, a-launois commented on www/install/createTables.sql
> +  `log_level_external_command` enum('trace', 'debug', 'info', 'warning', 'err', 'critical', 'off') DEFAULT 'err',
```suggestion
  `log_level_external_command` enum('trace', 'debug', 'info', 'warning', 'err', 'critical', 'off') DEFAULT 'info',
```

2022-05-03 14:41 UTC, a-launois commented on www/install/sql/centreon/Update-DB-22.04.0-beta.1.sql
> +    `log_level_external_command` enum('trace', 'debug', 'info', 'warning', 'err', 'critical', 'off') DEFAULT 'err',
```suggestion
    `log_level_external_command` enum('trace', 'debug', 'info', 'warning', 'err', 'critical', 'off') DEFAULT 'info',
```

2022-05-03 14:41 UTC, a-launois commented on www/install/var/baseconf/centreon-engine.sql
> +(1, 'file', 'err', 'info', 'info', 'info', 'err', 'err', 'err', 'err', 'err', 'err', 'err', 'info', 'err');
```suggestion
(1, 'file', 'err', 'info', 'info', 'info', 'err', 'info', 'err', 'err', 'err', 'err', 'err', 'info', 'err');
```

2022-05-03 14:41 UTC, a-launois commented on src/CentreonRemote/Domain/Resources/DefaultConfig/CfgNagiosLogger.php
> +            'log_level_external_command' => 'err',
```suggestion
            'log_level_external_command' => 'info',
```

2022-05-03 14:41 UTC, a-launois commented on tests/clapi_export/clapi-configuration.txt
> +ENGINECFG;setparam;Centreon Engine Central;log_level_external_command;err
```suggestion
ENGINECFG;setparam;Centreon Engine Central;log_level_external_command;info
```

2022-05-03 14:41 UTC, a-launois commented on www/class/centreon-config/centreonMainCfg.class.php
> +        'log_level_external_command' => 'err',
```suggestion
        'log_level_external_command' => 'info',
```

2022-05-05 14:07 UTC, adr-mo approved these changes, later dismissed

2022-05-06 06:41 UTC, kduret commented on www/class/centreon-config/centreonMainCfg.class.php
> +    /** @var string[] */
```suggestion
    /** @var array<string,string> */
```

2022-05-06 06:41 UTC, kduret commented on www/class/centreon-config/centreonMainCfg.class.php
> +     * @param string[]
```suggestion
     * @param array<string,string>
```

2022-05-06 06:41 UTC, kduret commented on www/include/configuration/configNagios/formNagios.ihtml
> +      <tr class="list_one logger_v2_option">
```suggestion
      <tr class="list_two logger_v2_option">
```

2022-05-06 06:41 UTC, kduret commented on www/include/configuration/configNagios/formNagios.ihtml
> +      <tr class="list_one logger_v2_option">
```suggestion
      <tr class="list_two logger_v2_option">
```

2022-05-06 06:41 UTC, kduret commented on www/include/configuration/configNagios/formNagios.ihtml
> +      <tr class="list_one logger_v2_option">
```suggestion
      <tr class="list_two logger_v2_option">
```

2022-05-06 06:41 UTC, kduret commented on www/include/configuration/configNagios/formNagios.ihtml
> +      <tr class="list_one logger_v2_option">
```suggestion
      <tr class="list_two logger_v2_option">
```

2022-05-06 06:41 UTC, kduret commented on www/include/configuration/configNagios/formNagios.ihtml
> +      <tr class="list_one logger_v2_option">
```suggestion
      <tr class="list_two logger_v2_option">
```

2022-05-06 06:41 UTC, kduret commented on www/include/configuration/configNagios/formNagios.ihtml
> +      <tr class="list_one logger_v2_option">
```suggestion
      <tr class="list_two logger_v2_option">
```

2022-05-06 06:41 UTC, kduret commented on www/include/configuration/configNagios/formNagios.ihtml
> +      <tr class="list_one logger_v2_option">
```suggestion
      <tr class="list_two logger_v2_option">
```

2022-05-06 06:41 UTC, kduret commented on www/include/configuration/configNagios/formNagios.php
> +    }
```suggestion
    $debugCheck[] = $form->createElement(
        'checkbox',
        $key,
        '&nbsp;',
        $val,
        [
            "id" => "debug" . $key,
            "onClick" => in_array($key, ['-1', '0'], true)
                ? "unCheckOthers('debug-level', this.name);"
                : "unCheckAllAndNaught('debug-level');",
            'class' => 'debug-level'
        ]
    );
```

2022-05-06 06:41 UTC, kduret commented on www/include/configuration/configNagios/help.php
> -    "This is the rotation method that you would like Monitoring Engine to use for your log file."
remove it from translation file

2022-05-06 06:41 UTC, kduret commented on www/include/configuration/configNagios/help.php
> -    . "This option is ignored if you choose to not use the log rotation functionality."
remove it from translation file

2022-05-06 06:41 UTC, kduret commented on www/include/configuration/configNagios/help.php
> -    "sufficient disk space for these dumps (ulimit). This option is discarded when using Centreon Engine."
remove it from translation file

2022-05-06 08:26 UTC, kduret commented on src/CentreonRemote/Domain/Service/ConfigurationWizard/ServerConnectionConfigurationService.php
> +        $this->insertWithAdapter('cfg_nagios_logger', CfgNagiosLogger::getConfiguration($configID));
```suggestion
        $this->insertWithAdapter('cfg_nagios_logger', new (CfgNagiosLogger($configID)));
```

2022-05-06 08:26 UTC, kduret commented on src/CentreonRemote/Domain/Resources/RemoteConfig/CfgNagiosLogger.php
> +{
add construct with id

2022-05-06 13:14 UTC, callapa submitted a review, later dismissed

2022-05-06 14:19 UTC, callapa approved these changes

2022-05-06 14:48 UTC, kduret approved these changes

2022-05-06 14:48 UTC, merged