fix(poller): configure broker loggers with wizard
centreon-archive/centreon-archived pull request #11049
Opened 2022-04-29 13:40 UTC by kduret

## Description

configure broker loggers with wizard

**Fixes** MON-13159

## Type of change

- [x] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [ ] 20.10.x
- [ ] 21.04.x
- [ ] 21.10.x
- [x] 22.04

2022-05-02 13:35 UTC, lpinsivy approved these changes, later dismissed

2022-05-02 14:48 UTC, lpinsivy submitted a review, later dismissed

2022-05-03 08:03 UTC, callapa requested changes

2022-05-03 08:03 UTC, callapa commented on src/CentreonRemote/Domain/Resources/DefaultConfig/CfgCentreonBrokerLog.php
> +    ];
Ids should be take from database

2022-05-03 11:36 UTC, callapa approved these changes

2022-05-03 11:40 UTC, jeremyjaouen approved these changes

2022-05-03 11:56 UTC, merged