enh(conf) add find host template by id
centreon-archive/centreon-archived pull request #11117
Opened 2022-05-13 14:18 UTC by a-launois

## Description

Add findHostTemplateById method in HostConfigurationService

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [x] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [ ] 20.10.x
- [ ] 21.04.x
- [ ] 21.10.x
- [x] 22.04.x (master)

## Checklist

- [x] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have made corresponding changes to the **documentation**.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2022-05-13 14:21 UTC, kduret commented on src/Centreon/Infrastructure/HostConfiguration/Repository/HostConfigurationRepositoryRDB.php
> +        $statement->bindValue(':host_id', $hostTemplateId, \PDO::PARAM_STR);
```suggestion
        $statement->bindValue(':host_id', $hostTemplateId, \PDO::PARAM_INT);
```

2022-05-13 14:21 UTC, kduret commented on src/Centreon/Infrastructure/HostConfiguration/Repository/HostConfigurationRepositoryRDB.php
> +                );
```suggestion
                Host::class,
                $record
            );
```

2022-05-13 14:21 UTC, kduret commented on src/Centreon/Domain/HostConfiguration/HostConfigurationService.php
> +     * @inheritDoc
```suggestion
     * {@inheritDoc}
```

2022-05-16 07:38 UTC, jeremyjaouen requested changes

2022-05-16 07:38 UTC, jeremyjaouen commented on src/Centreon/Domain/HostConfiguration/HostConfigurationService.php
> +    public function findHostTemplateById(int $hostTemplateId): ?Host
```suggestion
    public function findHostTemplate(int $hostTemplateId): ?Host
```
While not precising "By..." it is implicitly ById

2022-05-16 07:38 UTC, jeremyjaouen commented on src/Centreon/Domain/HostConfiguration/Interfaces/HostConfigurationReadRepositoryInterface.php
> +    public function findHostTemplateById(int $hostTemplateId): ?Host;
```suggestion
    public function findHostTemplate(int $hostTemplateId): ?Host;
```

2022-05-16 07:38 UTC, jeremyjaouen commented on src/Centreon/Domain/HostConfiguration/Interfaces/HostConfigurationServiceInterface.php
> +    public function findHostTemplateById(int $hostTemplateId): ?Host;
```suggestion
    public function findHostTemplate(int $hostTemplateId): ?Host;
```

2022-05-16 07:38 UTC, jeremyjaouen commented on src/Centreon/Infrastructure/HostConfiguration/Repository/HostConfigurationRepositoryRDB.php
> +    public function findHostTemplateById(int $hostTemplateId): ?Host
```suggestion
    public function findHostTemplate(int $hostTemplateId): ?Host
```

2022-05-16 08:00 UTC, jeremyjaouen approved these changes, later dismissed

2022-05-16 08:54 UTC, kduret submitted a review, later dismissed

2022-05-19 07:12 UTC, kduret submitted a review, later dismissed

2022-05-20 07:18 UTC, jeremyjaouen requested changes

2022-05-20 07:18 UTC, jeremyjaouen commented on src/Centreon/Domain/HostConfiguration/HostConfigurationService.php
> +                )
```suggestion
                sprintf(
                    _('Error while searching for the host template %d'),
                    $hostTemplateId
                ),
                [$ex->getMessage()]
```

2022-05-20 07:18 UTC, jeremyjaouen commented on lang/es_ES.UTF-8/LC_MESSAGES/messages.po
> +#  msgid "Error while searching for the host template"
```suggestion
#  msgid "Error while searching for the host template %d"
```

2022-05-24 11:18 UTC, callapa approved these changes

2022-05-24 11:29 UTC, jeremyjaouen approved these changes

2022-05-24 13:01 UTC, merged