Sanitize and bind "hosts" queries
centreon-archive/centreon-archived pull request #11127
Opened 2022-05-17 01:02 UTC by hyahiaoui-ext

## Description

Sanitizing and binding hosts queries to avoid and sql injection attack.

Preview:
![image](https://user-images.githubusercontent.com/97593234/168706154-103e6bff-0d1c-47a1-98da-e2a125eed736.png)

PS: The 1 error left that is seen on the picture is XSS related.

**Fixes** # MON-12875

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [x] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [ ] 20.10.x
- [x] 21.04.x
- [x] 21.10.x
- [x] 22.04.x (master)

## Checklist

- [x] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have made corresponding changes to the **documentation**.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2022-05-17 05:16 UTC, kduret commented on www/include/configuration/configObject/host/DB-Func.php
> +                VALUES (NULL, NULL, :host_id, NULL, :service_service_id)");
```suggestion
                    $insertStatement = $pearDB->prepare(
                        "INSERT INTO host_service_relation
                        VALUES (NULL, NULL, :host_id, NULL, :service_service_id)"
                    );
```

2022-05-17 05:16 UTC, kduret commented on www/include/configuration/configObject/host/DB-Func.php
> +                    VALUES (NULL, NULL, :host_id, NULL, :service_service_id)");
```suggestion
                        $statement = $pearDB->prepare(
                            "INSERT INTO host_service_relation
                            VALUES (NULL, NULL, :host_id, NULL, :service_service_id)"
                        );
```

2022-05-17 05:16 UTC, kduret commented on www/include/configuration/configObject/host/DB-Func.php
> +                              . ":host_tpl_id, :order)";
```suggestion
                    $mTpRq2 = "INSERT INTO `host_template_relation` (`host_host_id`, `host_tpl_id`, `order`)
                                       VALUES (:host_host_id, :host_tpl_id, :order)";
```

2022-05-17 05:16 UTC, kduret commented on www/include/configuration/configObject/host/DB-Func.php
> +                        . ":host_macro_value, :is_password)";
```suggestion
                    $mTpRq2 = "INSERT INTO `on_demand_macro_host`
                                  (`host_host_id`, `host_macro_name`, `host_macro_value`, `is_password`)
                                   VALUES  (:host_host_id, :host_macro_name, :host_macro_value, :is_password)";
```

2022-05-17 05:16 UTC, kduret commented on www/include/configuration/configObject/host/DB-Func.php
> +                $statement->bindValue(':order', (int) $j, \PDO::PARAM_INT);
```suggestion
                $statement->bindValue(':order', $j, \PDO::PARAM_INT);
```

2022-05-17 05:16 UTC, kduret commented on www/include/configuration/configObject/host/DB-Func.php
> +                    $statement->bindValue(':macro_order', (int) $i, \PDO::PARAM_INT);
do not always cast please :)
```suggestion
                    $statement->bindValue(':macro_order', $i, \PDO::PARAM_INT);
```

2022-05-17 05:16 UTC, kduret commented on www/include/configuration/configObject/host/DB-Func.php
> +                                        WHERE service_service_id = :service_service_id"
```suggestion
        "SELECT DISTINCT servicegroup_sg_id
        FROM servicegroup_relation
        WHERE service_service_id = :service_service_id"
```

2022-05-17 10:40 UTC, hyahiaoui-ext commented on www/include/configuration/configObject/host/DB-Func.php
> +                    $statement->bindValue(':macro_order', (int) $i, \PDO::PARAM_INT);
@kduret Yes my bad :)

2022-05-17 10:54 UTC, kduret approved these changes, later dismissed

2022-05-20 05:58 UTC, jeremyjaouen submitted a review, later dismissed

2022-05-23 08:36 UTC, jeremyjaouen approved these changes, later dismissed

2022-05-23 10:04 UTC, callapa requested changes

2022-05-23 10:04 UTC, callapa commented on www/include/configuration/configObject/host/DB-Func.php
> +                ':service_template_model_stm_id',
```suggestion
                ':host_host_id',
```

2022-05-23 10:04 UTC, callapa commented on www/include/configuration/configObject/host/DB-Func.php
> +        "AND hsr.host_host_id = :service_template_model_stm_id";
```suggestion
        "AND hsr.host_host_id = :host_host_id";
```

2022-05-25 07:16 UTC, jeremyjaouen requested changes

2022-05-25 10:52 UTC, hyahiaoui-ext commented on www/include/configuration/configObject/host/DB-Func.php
> +    }
@jeremyjaouen You're right @jeremyjaouen, i thought putting a variable inside the $rq, snyk would auto ignore it and flag it but this works :D.

2022-06-02 07:29 UTC, callapa approved these changes, later dismissed

2022-06-03 12:38 UTC, kduret commented on www/include/configuration/configObject/host/DB-Func.php
> +                                       VALUES (:host_host_id, :host_tpl_id, :order)";
weird indentation

2022-06-03 12:38 UTC, kduret commented on www/include/configuration/configObject/host/DB-Func.php
> +                        VALUES (:host_host_id, :host_tpl_id, :order)";
weird indentation

2022-06-03 12:38 UTC, kduret commented on www/include/configuration/configObject/host/DB-Func.php
> +                           VALUES (:host_macro_name, :host_macro_value, :host_host_id, :macro_order)";
weird indentation

2022-06-03 12:38 UTC, kduret commented on www/include/configuration/configObject/host/DB-Func.php
> +                                VALUES (:hostcategories_hc_id, :host_host_id)"
weird indentation

2022-06-03 20:43 UTC, callapa approved these changes

2022-06-10 07:05 UTC, callapa approved these changes

2022-06-10 07:10 UTC, jeremyjaouen approved these changes

2022-06-10 10:33 UTC, merged