Sanitize and bind "service" related queries
centreon-archive/centreon-archived pull request #11156
Opened 2022-05-24 08:27 UTC by ataghzout

## Description

Sanitize and bind "service" related queries to avoid sql injections in the future.

**Fixes** # MON-12837

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [x] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [ ] 20.10.x
- [x] 21.04.x
- [x] 21.10.x
- [x] 22.04.x (master)

## Checklist

- [x] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have made corresponding changes to the **documentation**.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2022-05-27 07:46 UTC, kduret commented on www/include/configuration/configObject/service/DB-Func.php
> +                            $query = "INSERT INTO host_service_relation VALUES (NULL, :hostgroup_hg_id,
Duplicated variable declaration

2022-06-03 06:50 UTC, callapa requested changes

2022-06-03 06:50 UTC, callapa commented on www/include/configuration/configObject/service/DB-Func.php
> +        $statement->bindValue(':service_service_id', $pearDB->escape($serviceId));
```suggestion
        $statement->bindValue(':sc_id', $criticalityId, \PDO::PARAM_INT);
        $statement->bindValue(':service_service_id', $serviceId, \PDO::PARAM_INT);
```

2022-06-03 06:50 UTC, callapa commented on www/include/configuration/configObject/service/DB-Func.php
> +    $statement->bindValue(':service_service_id', $pearDB->escape($serviceId));
```suggestion
    $statement->bindValue(':service_service_id', $serviceId, \PDO::PARAM_INT);
```

2022-06-03 06:50 UTC, callapa commented on www/include/configuration/configObject/service/DB-Func.php
> +                            $statement->bindValue(':is_password', $pearDB->escape($sv["is_password"]));
```suggestion
                            $statement->bindValue(':svc_macro_name', $macName);
                            $statement->bindValue(':svc_macro_value', $macVal);
                            $statement->bindValue(':is_password', $sv["is_password"]);
```

2022-06-03 09:03 UTC, callapa requested changes

2022-06-10 07:40 UTC, callapa requested changes

2022-06-10 07:40 UTC, callapa commented on www/include/configuration/configObject/service/DB-Func.php
> +                $statement->bindValue(':host_host_id', (int) $ret1[0], \PDO::PARAM_INT);
Where is the :host_host_id value in your query ?

2022-06-13 09:56 UTC, callapa requested changes

2022-06-17 11:30 UTC, kduret submitted a review, later dismissed

2022-06-20 13:15 UTC, a-launois commented on www/include/configuration/configObject/service/DB-Func.php
> +                                    $value2 != null
```suggestion
                                        $value2 != null
```

2022-06-20 13:17 UTC, callapa approved these changes, later dismissed

2022-06-20 13:17 UTC, a-launois submitted a review, later dismissed

2022-06-23 05:29 UTC, jeremyjaouen commented on www/include/configuration/configObject/service/DB-Func.php
> +                                $host_id ? \PDO::PARAM_INT : \PDO::PARAM_NULL
I think you could set \PDO::PARAM_INT in both case (int or null)

2022-06-23 05:30 UTC, jeremyjaouen approved these changes

2022-06-24 06:23 UTC, jeremyjaouen submitted a review, later dismissed

2022-06-24 16:03 UTC, a-launois requested changes

2022-06-24 16:03 UTC, a-launois commented on www/include/configuration/configObject/service/DB-Func.php
> +                            $statement = $pearDB->prepare($query);
Can you move the query and prepare statement outside the while loop like you did for previous ones ?

2022-06-24 16:03 UTC, a-launois commented on www/include/configuration/configObject/service/DB-Func.php
> +                            $statement = $pearDB->prepare($query);
Can you move the query and prepare statement outside the while loop like you did for previous ones ?

2022-06-24 16:03 UTC, a-launois commented on www/include/configuration/configObject/service/DB-Func.php
> +                                $Sg["host_host_id"] ? $host_id = $Sg["host_host_id"] : $host_id = null;
```suggestion
                                $host_id = $Sg["host_host_id"] ? $Sg["host_host_id"] : null;
```

2022-06-24 16:03 UTC, a-launois commented on www/include/configuration/configObject/service/DB-Func.php
> +                                $Sg["hostgroup_hg_id"] ? $hg_id = $Sg["hostgroup_hg_id"] : $hg_id = null;
```suggestion
                                $hg_id = $Sg["hostgroup_hg_id"] ? $Sg["hostgroup_hg_id"] : null;
```

2022-07-01 08:34 UTC, ataghzout commented on www/include/configuration/configObject/service/DB-Func.php
> +                                $host_id ? \PDO::PARAM_INT : \PDO::PARAM_NULL
i already tested but still dosen't work  \PDO::PARAM_INT

2022-07-01 14:34 UTC, kduret commented on www/include/configuration/configObject/service/DB-Func.php
> +                                $host_id ? \PDO::PARAM_INT : \PDO::PARAM_NULL
The issue is that you always cast $host_id, so if $host_id is null, you will insert `0`
```suggestion
                                $host_id,
                                \PDO::PARAM_INT
```

2022-07-05 08:34 UTC, callapa approved these changes

2022-07-06 14:50 UTC, kduret approved these changes

2022-07-07 14:26 UTC, a-launois approved these changes

2022-07-08 07:38 UTC, merged