enh(api): add endpoint to find access groups
centreon-archive/centreon-archived pull request #11192
Opened 2022-06-02 11:36 UTC by jeremyjaouen

## Description

This PR intends to add endpoint find access groups use case.

For a user admin return all the access groups.
![image](https://user-images.githubusercontent.com/61694165/171620658-9120dc8c-f7a1-46b7-abee-e714fd045fc1.png)

For a user submitted to ACL, return the access groups where he is member of.
![image](https://user-images.githubusercontent.com/61694165/171620443-9e2d4fd7-a30d-4739-8689-bcf7413cb0ec.png)

**Fixes** # MON-13478

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [x] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [x] Updating documentation (missing information, typo...)

## Target serie

- [ ] 20.10.x
- [ ] 21.04.x
- [ ] 21.10.x
- [x] 22.04.x (master)

Any **relevant details** of the configuration to perform the test should be added.

## Checklist

- [x] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have made corresponding changes to the **documentation**.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2022-06-02 12:53 UTC, callapa commented on src/Core/Security/Application/UseCase/FindUserAccessGroups/FindUserAccessGroupsResponse.php
> +            fn (AccessGroup $accessGroup) => [
Why not include the other fields (alias, activated, group_changed) ?

2022-06-03 07:47 UTC, TamazC commented on src/Core/Security/Infrastructure/Repository/DbReadAccessGroupRepository.php
> +            $type = key($data);
are you sure about using of key function into the loop ?
https://www.php.net/manual/fr/function.key.php#114905

2022-06-03 07:48 UTC, TamazC commented on src/Core/Security/Infrastructure/Repository/DbReadAccessGroupRepository.php
> +                $type = key($data);
same here

2022-06-03 09:26 UTC, callapa requested changes

2022-06-03 09:26 UTC, callapa commented on src/Core/Security/Infrastructure/Api/FindUserAccessGroups/FindUserAccessGroupsController.php
> +        $request = new FindUserAccessGroupsRequest($this->getUser());
You can't put an object in a DTO, only scalar values are allowed.

2022-06-03 12:32 UTC, kduret commented on src/Core/Security/Application/UseCase/FindUserAccessGroups/FindUserAccessGroupsRequest.php
> +    public bool $isUserAdmin = false;
move property before construct

2022-06-03 12:32 UTC, kduret commented on src/Core/Security/Application/Repository/ReadAccessGroupRepositoryInterface.php
> +    public function findByContactWithFilter(int $userId): array;
`WithFilter` means using query search parameter ?
if yes, it's not consistent with `findAll` which also use query search parameter

2022-06-03 13:30 UTC, callapa approved these changes

2022-06-06 05:51 UTC, kduret approved these changes

2022-06-06 05:53 UTC, merged