Sanitize and bind "timeperiod" configuration queries
centreon-archive/centreon-archived pull request #11233
Opened 2022-06-14 00:07 UTC by hyahiaoui-ext

## Description

Sanitizing and binding timeperiod queries to avoid any sql injections attacks in the future + cleaning up legacy code.

**Fixes** # MON-13314

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [x] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [x] 21.04.x
- [x] 21.10.x
- [x] 22.04.x
- [x] 22.10.x (master)

## Checklist

#### Community contributors & Centreon team

- [x] I have followed the **coding style guidelines** provided by Centreon
- [x] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2022-06-17 06:38 UTC, jeremyjaouen requested changes

2022-06-17 06:38 UTC, jeremyjaouen commented on www/include/configuration/configObject/timeperiod/DB-Func.php
> +    $pearDB->query("INSERT INTO timeperiod VALUES (" . $params['values'] . ")");
this query should also be sanitized

2022-06-17 06:38 UTC, jeremyjaouen commented on www/include/configuration/configObject/timeperiod/DB-Func.php
> +    return $pearDB->lastInsertId();
```suggestion
    return (int) $pearDB->lastInsertId();
```

If you cast here, you don't have to cast (int) $params['tp_id'] in your other following methods,
then your @return int in your phpdoc will be correct :), as lastInsertId() return a string

2022-06-17 06:38 UTC, jeremyjaouen commented on www/include/configuration/configObject/timeperiod/DB-Func.php
> + * @return void
```suggestion
```

2022-06-17 06:38 UTC, jeremyjaouen commented on www/include/configuration/configObject/timeperiod/DB-Func.php
> + * @return void
```suggestion
```

2022-06-17 06:38 UTC, jeremyjaouen commented on www/include/configuration/configObject/timeperiod/DB-Func.php
> + * @return void
```suggestion
```

2022-06-20 05:20 UTC, kduret commented on www/include/configuration/configObject/timeperiod/DB-Func.php
> +function notConvertNullToString(string $value)
```suggestion
function convertNullStringToNull(string $value)
```

2022-06-20 05:20 UTC, kduret commented on www/include/configuration/configObject/timeperiod/DB-Func.php
> +    $valuesExploded = array_map('notConvertNullToString', explode(', ', $params['values']));
```suggestion
    $valuesExploded = array_map('convertNullStringToNull', explode(', ', $params['values']));
```

2022-06-20 05:26 UTC, kduret reviewed
I think it is a better approach to replace `"NULL"` by `null` directly on variable assignment, it will avoid to create `convertNullStringToNull`

2022-06-20 12:49 UTC, hyahiaoui-ext commented
> I think it is a better approach to replace `"NULL"` by `null` directly on variable assignment, it will avoid to create `convertNullStringToNull`

@kduret i know it's just here a bit complicated because it's mixed with strings and when you assign null directly to the string it's replaced by voids and then the query doesn't understand them ^^.

2022-06-20 13:08 UTC, kduret commented on www/include/configuration/configObject/timeperiod/DB-Func.php
>      } #Duplicate entry
```suggestion
```

2022-06-20 13:08 UTC, kduret commented on www/include/configuration/configObject/timeperiod/DB-Func.php
> +    elseif ($statement->rowCount() >= 1 && $tp["tp_id"] != $id) {
```suggestion
    } elseif ($statement->rowCount() >= 1 && $tp["tp_id"] != $id) { #Duplicate entry
```

2022-06-22 05:41 UTC, jeremyjaouen approved these changes

2022-06-22 08:45 UTC, kduret approved these changes

2022-06-22 16:15 UTC, merged