Mon 6585 export event logs
centreon-archive/centreon-archived pull request #11253
Opened 2022-06-17 14:58 UTC by TamazC

## Description

This PR aims to fix event logs extraction issue

**Fixes** 
# MON-6585

## Type of change

- [x] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 21.04.x
- [ ] 21.10.x
- [ ] 22.04.x
- [x] 22.10.x (master)

<h2> How this pull request can be tested ? </h2>

On the event log page click to "export csv" button.
Export should be work even with the huge data

## Checklist

#### Community contributors & Centreon team

- [x] I have followed the **coding style guidelines** provided by Centreon
- [x] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [x] I have commented my code, especially **hard-to-understand areas** of the PR.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2022-06-20 13:38 UTC, a-launois submitted a review, later dismissed

2022-06-22 06:06 UTC, jeremyjaouen requested changes

2022-06-22 06:06 UTC, jeremyjaouen commented on www/include/eventLogs/export/Request.php
> +     * @param array $lca
type of array should be specified

2022-06-22 06:06 UTC, jeremyjaouen commented on www/include/eventLogs/export/Formatter.php
> +            usleep(300);
is usleep still needed ?

2022-06-22 06:43 UTC, kduret commented on www/include/eventLogs/export/QueryGenerator.php
> +                $req .= " AND logs.host_name NOT LIKE '_Module_BAM%' ";
```suggestion
                $req .= " AND logs.host_name NOT LIKE '\\_Module\\_BAM%' ";

```

2022-06-22 07:44 UTC, TamazC commented on www/include/eventLogs/export/Request.php
> +     * @param array $lca
there is no typed object in this array.

2022-06-22 07:49 UTC, TamazC commented on www/include/eventLogs/export/Request.php
> +    private function dateStringToTimestamp(string $dateString): int
👍

2022-06-23 08:16 UTC, kduret submitted a review, later dismissed

2022-06-23 08:19 UTC, jeremyjaouen commented on www/include/eventLogs/export/Formatter.php
> +     * @return void
no need to specify @return void in phpdoc

2022-06-23 08:19 UTC, jeremyjaouen commented on www/include/eventLogs/export/Formatter.php
> +     * @param array $hosts
```suggestion
     * @param array $hosts
```
specify the type of data in the array

2022-06-23 08:20 UTC, jeremyjaouen commented on www/include/eventLogs/export/Formatter.php
> +    private array $hosts = [];
specifiy the type of data in the array

2022-06-23 15:15 UTC, TamazC commented on www/include/eventLogs/export/Formatter.php
> +    private array $hosts = [];
done

2022-06-24 07:16 UTC, jeremyjaouen approved these changes

2022-06-24 07:32 UTC, callapa approved these changes

2022-06-24 15:55 UTC, merged