Sanitize and bind queries in virtual metrics configuration
centreon-archive/centreon-archived pull request #11257
Opened 2022-06-21 00:19 UTC by hyahiaoui-ext

## Description

Sanitizing and binding virtual metrics queries to avoid any sql injections attacks in the future and cleaning legacy code.

Preview:
![image](https://user-images.githubusercontent.com/97593234/174691605-101e40d0-4d63-4bda-a845-db27293c73d4.png)

**Fixes** # MON-13944

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [x] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [x] 21.04.x
- [x] 21.10.x
- [x] 22.04.x
- [x] 22.10.x (master)

## Checklist

#### Community contributors & Centreon team

- [x] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2022-06-21 07:39 UTC, a-launois submitted a review, later dismissed

2022-06-22 05:40 UTC, jeremyjaouen requested changes

2022-06-22 05:40 UTC, jeremyjaouen commented on www/include/views/virtualMetrics/DB-Func.php
> +        "SELECT index_id, vmetric_name FROM `virtual_metrics` WHERE `vmetric_id`=:vmetric_id$l_where;"
```suggestion
        "SELECT index_id, vmetric_name FROM `virtual_metrics` WHERE `vmetric_id`=:vmetric_id$l_where"
```

2022-06-22 05:40 UTC, jeremyjaouen commented on www/include/views/virtualMetrics/DB-Func.php
> +            '(^|,)' . str_replace($repA, $repB, $vmetric["vmetric_name"]) . '(,|$)',
I think you need to check that str_replace doesnt return an array before binding it.

2022-06-23 05:26 UTC, jeremyjaouen approved these changes

2022-06-24 12:57 UTC, a-launois approved these changes

2022-06-28 08:08 UTC, callapa approved these changes

2022-06-28 08:26 UTC, merged