[Snyk] Sanitize and bind "common/common-Func" queries
centreon-archive/centreon-archived pull request #11256
Opened 2022-06-20 12:51 UTC by ataghzout

## Description
Sanitize and bind "common/common-Func" related queries to avoid sql injections in the future.

**Fixes** # MON-12873

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [x] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [x] 21.04.x
- [x] 21.10.x
- [x] 22.04.x
- [] 22.10.x (master)

<h2> How this pull request can be tested ? </h2>

Please describe the **procedure** to verify that the goal of the PR is matched. Provide clear instructions so that it can be **correctly tested**.

Any **relevant details** of the configuration to perform the test should be added.

## Checklist

#### Community contributors & Centreon team

- [x] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2022-06-20 13:34 UTC, callapa requested changes

2022-06-20 13:34 UTC, callapa commented on www/include/common/common-Func.php
> +        $statement->bindValue(':field', $field, \PDO::PARAM_STR);
Use bindColumn instead

2022-06-24 06:13 UTC, jeremyjaouen requested changes

2022-06-24 06:13 UTC, jeremyjaouen commented on www/include/common/common-Func.php
> -}
Please restore this method as it is still used 

```
2022-06-23T17:56:54.350068273Z [23-Jun-2022 19:56:54 Europe/Paris] PHP Fatal error:  Uncaught Error: Call to undefined function isNotEmptyAfterStringSanitize() in /usr/share/centreon/vendor/openpsa/quickform/lib/HTML/QuickForm/Rule/Callback.php:57
```

2022-07-01 14:35 UTC, kduret reviewed
@ataghzout you need to resolve conflicts

2022-07-08 09:13 UTC, callapa requested changes

2022-07-08 09:13 UTC, callapa commented on www/include/common/common-Func.php
> -function getCentreonVersion($pearDB)
Do not delete this function, it is still in use

2022-07-19 08:04 UTC, jeremyjaouen requested changes

2022-07-19 08:04 UTC, jeremyjaouen commented on www/include/common/common-Func.php
> -function getCentreonVersion($pearDB)
this method should not be deleted

2022-07-20 08:30 UTC, jeremyjaouen approved these changes

2022-07-22 06:50 UTC, jeremyjaouen submitted a review, later dismissed

2022-07-25 07:48 UTC, kduret requested changes

2022-07-25 07:48 UTC, kduret commented on www/include/common/common-Func.php
> +        $rq2 = "SELECT ehi." . ":field" .
I think it's not possible to do this

2022-07-25 07:48 UTC, kduret commented on www/include/common/common-Func.php
> +        $statement2 = $pearDB->prepare("SELECT :field  FROM host WHERE host_id = :host_tpl_id");
I think it's not possible to bind `:field`

2022-07-25 07:48 UTC, kduret commented on www/include/common/common-Func.php
> +    $rq = "SELECT ehi." . ":field" . " " .
I think it's not possible to do this

2022-07-25 07:48 UTC, kduret commented on www/include/common/common-Func.php
> +        $rq = "SELECT :field " .
I think it's not possible to do this

2022-07-25 07:48 UTC, kduret commented on www/include/common/common-Func.php
> +        $rq2 = "SELECT :field " .
I think it's not possible to do this

2022-07-27 21:06 UTC, Thebarda commented
293 files changes. I hope this is a failed merge

2022-07-28 10:18 UTC, emabassi-ext commented
> 293 files changes. I hope this is a failed merge

Fixed !

2022-07-28 15:30 UTC, callapa commented on www/include/common/common-Func.php
> -function slash($elem = null)
This function is used in this file `www/include/Administration/parameters/general/form.php`

2022-08-05 13:56 UTC, callapa submitted a review, later dismissed

2022-08-22 11:25 UTC, jeremyjaouen approved these changes, later dismissed

2022-08-23 07:39 UTC, TamazC commented on www/include/common/common-Func.php
>      global $pearDB, $oreon;
```suggestion
    global $pearDB;
```

2022-08-23 07:40 UTC, TamazC commented on www/include/common/common-Func.php
>      global $pearDB, $oreon;
$oreon is never used

2022-08-23 07:43 UTC, TamazC commented on www/include/common/common-Func.php
>      global $pearDB, $oreon;
```suggestion
    global $pearDB,;
```
$oreon is never used

2022-08-23 07:48 UTC, TamazC commented on www/include/common/common-Func.php
>          $field_result = $row[$field];
```suggestion

```
unused variable $field_result

2022-08-23 07:52 UTC, TamazC commented on www/include/common/common-Func.php
> -function getMyServiceExtendedInfoImage($service_id, $field)
This funcion is still used in :
- www\include\configuration\configObject\service\listServiceByHost.php:346
- www\include\configuration\configObject\service\listServiceByHostGroup.php:313
- www\include\configuration\configObject\service_template_model\listServiceTemplateModel.php:219
- www\include\monitoring\objectDetails\serviceDetails.php:872
- www\include\monitoring\objectDetails\serviceDetails.php:877

2022-08-23 08:12 UTC, TamazC commented on www/include/common/common-Func.php
>  function getDefaultGraph($service_id = null, $rrdType = null)
The function "getDefaultGraph" is unused, so you could remove it.

2022-08-23 08:15 UTC, TamazC commented on www/include/common/common-Func.php
```suggestion
 */

```

2022-08-23 08:22 UTC, TamazC approved these changes, later dismissed

2022-08-24 11:00 UTC, jeremyjaouen submitted a review, later dismissed

2022-08-29 08:09 UTC, kduret commented on www/include/common/common-Func.php
> +            "WHERE service_id = :service_id LIMIT 1") ;
```suggestion
            "WHERE service_id = :service_id LIMIT 1");
```

2022-08-29 08:10 UTC, kduret commented on www/include/common/common-Func.php
> +            "FROM service WHERE service_id = :service_id LIMIT 1") ;
```suggestion
            "FROM service WHERE service_id = :service_id LIMIT 1");
```

2022-08-29 08:10 UTC, kduret commented on www/include/common/common-Func.php
> +            " WHERE service_id = :service_id LIMIT 1") ;
```suggestion
            " WHERE service_id = :service_id LIMIT 1");
```

2022-08-29 08:10 UTC, kduret commented on www/include/common/common-Func.php
> +            "WHERE service_id = :service_id LIMIT 1") ;
```suggestion
            "WHERE service_id = :service_id LIMIT 1");
```

2022-08-29 08:10 UTC, kduret commented on www/include/common/common-Func.php
> +            "WHERE service_id = :service_id AND esi.service_service_id = service_id LIMIT 1") ;
```suggestion
            "WHERE service_id = :service_id AND esi.service_service_id = service_id LIMIT 1");
```

2022-08-29 08:10 UTC, kduret commented on www/include/common/common-Func.php
> +        . " AND s.host_id = :host_id LIMIT 1") ;
```suggestion
        . " AND s.host_id = :host_id LIMIT 1");
```

2022-08-29 08:11 UTC, kduret approved these changes

2022-08-30 11:09 UTC, callapa approved these changes

2022-09-05 07:28 UTC, merged