Add categories cards in Panel and enabled filter with categories
centreon-archive/centreon-archived pull request #11255
Opened 2022-06-20 10:13 UTC by adr-mo

## Description

**PLEASE MAKE SURE THAT THE BRANCH PR INCLUDES JIRA TICKET ID** (_for centreon-internal_)

Please include a short resume of the changes and what is the purpose of PR. Any relevant information should be added to help:
* **QA Team** (Quality Assurance) with tests.
* **reviewers** to understand what are the stakes of the pull request.

**Fixes** # (issue)

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 21.04.x
- [ ] 21.10.x
- [ ] 22.04.x
- [ ] 22.10.x (master)

<h2> How this pull request can be tested ? </h2>

Please describe the **procedure** to verify that the goal of the PR is matched. Provide clear instructions so that it can be **correctly tested**.

Any **relevant details** of the configuration to perform the test should be added.

## Checklist

#### Community contributors & Centreon team

- [ ] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have **rebased** my development branch on the base branch (master, maintenance).

2022-06-20 12:10 UTC, Jordan91 approved these changes

2022-06-20 12:19 UTC, Thebarda reviewed
Don't forget to add translations on new labels

2022-06-20 12:19 UTC, Thebarda commented on www/front_src/src/Resources/Details/tabs/Details/DetailsCard/DetailsChips.tsx
> +        return <DetailsChip group={group} key={group.id} type={getType()} />;
You can extract it to a variable

2022-06-20 13:02 UTC, cg-tw requested changes

2022-06-20 13:02 UTC, cg-tw commented on lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "Catégories d'hôte"
```suggestion
msgstr "Catégories d'hôtes"
```

2022-06-20 14:48 UTC, bdauria requested changes

2022-06-20 14:48 UTC, bdauria commented on www/front_src/src/Resources/Filter/Criterias/searchQueryLanguage/index.test.ts
> +    isOptimizedModeEnabled: true,
This property shouldn't be here in my opinion. Instead, we should have a mapping somewhere indicating which criteria should be displayed in optimized mode and be queried whenever needed before the actual display

2022-06-22 15:32 UTC, adr-mo commented
Closing this PR, final review will be done on the final PR

2022-06-22 15:32 UTC, closed without merging