fix(conf) add warning when max length is exceeded for url, url action or notes
centreon-archive/centreon-archived pull request #11262
Opened 2022-06-21 16:38 UTC by a-launois

## Description

 Display a warning message when max length of input url, action url or notes are exceeded in host configuration form and limit data length at save
<img width="800" alt="image" src="https://user-images.githubusercontent.com/88387848/174771522-f75aeb11-5364-4a69-9e49-81838d34d710.png">

## Type of change

- [x] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 21.04.x
- [x] 21.10.x
- [x] 22.04.x
- [x] 22.10.x (master)

## Checklist

#### Community contributors & Centreon team

- [x] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2022-06-21 17:06 UTC, cg-tw requested changes

2022-06-21 17:06 UTC, cg-tw commented on lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "Attention, taille maximale dépassées pour le champ #input#, il sera tronqué à l'enregistrement."
```suggestion
msgstr "Attention, taille maximale dépassée pour le champ #input#, il sera tronqué à l'enregistrement."
```

2022-06-22 05:26 UTC, jeremyjaouen requested changes, later dismissed

2022-06-22 05:26 UTC, jeremyjaouen commented on www/include/common/common-Func.php
> +function limitNotesLength($value)
missing phpdoc

2022-06-22 05:26 UTC, jeremyjaouen commented on www/include/common/common-Func.php
> +function limitUrlLength($value)
missing phpdoc

2022-06-23 09:50 UTC, cg-tw commented on lang/es_ES.UTF-8/LC_MESSAGES/messages.po
> +#  msgid "Warning, maximum size exceeded for input #input#, it will be be truncated upon saving."
```suggestion
#  msgid "Warning, maximum size exceeded for input #input#, it will be truncated upon saving."
```

2022-06-23 09:50 UTC, cg-tw commented on lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
> +#  msgid "Warning, maximum size exceeded for input #input#, it will be be truncated upon saving."
```suggestion
#  msgid "Warning, maximum size exceeded for input #input#, it will be truncated upon saving."
```

2022-06-23 09:50 UTC, cg-tw commented on lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
> +#  msgid "Warning, maximum size exceeded for input #input#, it will be be truncated upon saving."
```suggestion
#  msgid "Warning, maximum size exceeded for input #input#, it will be truncated upon saving."
```

2022-06-23 09:50 UTC, cg-tw commented on www/include/configuration/configObject/host/formHost.php
> +    _("Warning, maximum size exceeded for input #input#, it will be be truncated upon saving")
```suggestion
    _("Warning, maximum size exceeded for input #input#, it will be truncated upon saving")
```

2022-06-23 09:50 UTC, cg-tw commented on www/include/configuration/configObject/service/formService.php
> +    _("Warning, maximum size exceeded for input #input#, it will be be truncated upon saving")
```suggestion
    _("Warning, maximum size exceeded for input #input#, it will be truncated upon saving")
```

2022-06-27 08:26 UTC, cg-tw approved these changes, later dismissed

2022-06-27 09:04 UTC, adr-mo submitted a review, later dismissed

2022-06-27 12:23 UTC, callapa approved these changes

2022-06-27 12:25 UTC, cg-tw approved these changes

2022-06-27 12:26 UTC, adr-mo approved these changes

2022-06-27 13:54 UTC, merged