fix(topology) fix wizard poller access
centreon-archive/centreon-archived pull request #11272
Opened 2022-06-22 17:25 UTC by a-launois

## Description

Removing poller wizard steps from topology table result in the poller wizard page being inaccessible ('you are not allowed to see this page')
When user has read/write access on the poller page, the necessary data to allow access the poller wizard page is added to the response of the 'getNavigationList' API call.

## Type of change

- [x] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 21.04.x
- [ ] 21.10.x
- [x] 22.04.x
- [x] 22.10.x (master)

## Checklist

#### Community contributors & Centreon team

- [x] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2022-06-22 17:57 UTC, jeremyjaouen requested changes

2022-06-22 17:57 UTC, jeremyjaouen commented on src/Centreon/Application/Webservice/TopologyWebservice.php
> +        $topology->setTopologyParent('60901');
```suggestion
        $topology->setTopologyParent(60901);
```
setTopologyParent takes ?int as parameter

2022-06-22 17:57 UTC, jeremyjaouen commented on src/Centreon/Application/Webservice/TopologyWebservice.php
> +        $topology->setTopologyParent('60901');
I think you also could store 60901 in a variable as it is used 3 time in the method

2022-06-23 10:30 UTC, callapa requested changes

2022-06-23 10:30 UTC, callapa commented on src/Centreon/Application/Webservice/TopologyWebservice.php
> +    private function determinePollerWizardAccess(\CentreonUser $user): ?Topology
The name of the method does not reflect what it does.
Use two methods: one to determine and one to create

2022-06-23 13:20 UTC, jeremyjaouen submitted a review, later dismissed

2022-06-24 07:23 UTC, a-launois commented on src/Centreon/Application/Webservice/TopologyWebservice.php
> +        return false;
return condition result

2022-06-24 07:26 UTC, TamazC approved these changes

2022-06-24 07:29 UTC, jeremyjaouen approved these changes

2022-06-24 07:31 UTC, callapa approved these changes

2022-06-24 08:23 UTC, merged