fix(platform) : Issue with cross databases query when the name contains some characters
centreon-archive/centreon-archived pull request #11321
Opened 2022-07-03 21:31 UTC by hyahiaoui-ext

## Description

In Centreon Web and some modules, there are some cross databases queries. If a database name contains some characters like dash the query is on error. This database name needs to be surrounded by backquoted.

**Fixes** # MON-13829

## Type of change

- [x] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 21.04.x
- [ ] 21.10.x
- [x] 22.04.x
- [x] 22.10.x (master)

## Checklist

#### Community contributors & Centreon team

- [x] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2022-07-04 04:07 UTC, kduret requested changes

2022-07-04 04:07 UTC, kduret commented on www/include/configuration/configServers/DB-Func.php
> +        FROM `{$conf_centreon['db']}`.ns_host_relation`
```suggestion
        FROM `{$conf_centreon['db']}`.ns_host_relation
```

2022-07-04 10:22 UTC, hyahiaoui-ext commented on www/include/configuration/configServers/DB-Func.php
> +        FROM `{$conf_centreon['db']}`.ns_host_relation`
@kduret done :)

2022-07-04 18:13 UTC, callapa approved these changes

2022-07-05 05:14 UTC, jeremyjaouen approved these changes

2022-07-05 13:00 UTC, kduret approved these changes

2022-07-05 13:18 UTC, merged