Clean(platform): Clean appKey method and usage
centreon-archive/centreon-archived pull request #11336
Opened 2022-07-05 14:03 UTC by hyahiaoui-ext

## Description

AppKey was introduced (18.10) to give an unique ID to a platform (but we use uuid now)
It is not used anymore and could be removed.

**Fixes** # MON-12739

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [x] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 21.04.x
- [ ] 21.10.x
- [x] 22.04.x
- [x] 22.10.x (master)

## Checklist

#### Community contributors & Centreon team

- [x] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2022-07-06 08:58 UTC, jeremyjaouen submitted a review, later dismissed

2022-07-07 07:11 UTC, jeremyjaouen approved these changes, later dismissed

2022-07-08 10:20 UTC, callapa requested changes
You forgot to clean up this file: src/CentreonRemote/Application/Webservice/CentreonRemoteServer.php

2022-07-08 13:05 UTC, hyahiaoui-ext commented
> You forgot to clean up this file: src/CentreonRemote/Application/Webservice/CentreonRemoteServer.php

Done :) @callapa

2022-07-11 07:03 UTC, kduret commented on www/install/php/Update-22.10.0-beta.1.php
> +    $pearDB->query("DELETE FROM `informations` WHERE `key` = 'appKey'");
please add a related error message

2022-07-11 07:38 UTC, kduret reviewed
remove `remote_servers.app_key` column from fresh install and upgrade

2022-07-12 09:49 UTC, hyahiaoui-ext commented on www/install/php/Update-22.10.0-beta.1.php
> +    $pearDB->query("DELETE FROM `informations` WHERE `key` = 'appKey'");
@kduret done !

2022-07-12 09:50 UTC, hyahiaoui-ext commented
> remove `remote_servers.app_key` column from fresh install and upgrade

I've made changes now you can check ^^

2022-07-12 14:23 UTC, kduret commented on www/install/sql/centreon/Update-DB-22.10.0-beta.1.sql
> +ALTER TABLE remote_servers DROP COLUMN IF EXISTS `app_key`;
`DROP COLUMN IF EXISTS` does not work for `MySQL`
```suggestion
ALTER TABLE remote_servers DROP COLUMN `app_key`;
```

2022-07-12 14:23 UTC, kduret commented on www/install/php/Update-22.10.0-beta.1.php
> +    $errorMessage = "Unable to delete 'appKey' option from database";
```suggestion

    $errorMessage = "Unable to delete 'appKey' option from database";
```

2022-07-12 14:28 UTC, kduret commented on www/install/sql/centreon/Update-DB-22.10.0-beta.1.sql
> +ALTER TABLE remote_servers DROP COLUMN IF EXISTS `app_key`;
I will create a ticket to fix query about `enable_one_click_export` (cc @a-launois )

2022-07-13 11:41 UTC, kduret approved these changes

2022-07-18 06:40 UTC, jeremyjaouen approved these changes

2022-07-28 15:24 UTC, callapa approved these changes

2022-07-28 15:33 UTC, merged