enh(conf) flag pollers as updated when changing host/hostgroup/service/servicegroup configuration
centreon-archive/centreon-archived pull request #11346
Opened 2022-07-07 16:13 UTC by a-launois

## Description

## Type of change

- [x] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 21.04.x
- [ ] 21.10.x
- [ ] 22.04.x
- [x] 22.10.x (master)

## Checklist

#### Community contributors & Centreon team

- [x] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2022-07-19 07:29 UTC, jeremyjaouen commented on www/class/centreon-clapi/centreonConfiguration.class.php
> +     * Undocumented function
```suggestion
     * Undocumented function
```
document this function

2022-07-19 07:32 UTC, jeremyjaouen commented on www/class/centreon-clapi/centreonHost.class.php
> +     * @param array $parameters
precise type of data

2022-07-19 07:36 UTC, jeremyjaouen commented on www/class/centreon-clapi/centreonService.class.php
> +
```suggestion
```

2022-07-19 07:37 UTC, jeremyjaouen commented on www/class/centreon-clapi/centreonServiceGroup.class.php
> +     * @param array $parameters
```suggestion
add type of data
```

2022-07-19 07:43 UTC, a-launois commented on www/include/configuration/configObject/host/DB-Func.php
> +        $stmt = $pearDB->prepare("SELECT host_name FROM `host` WHERE host_id = :hostId");
place prepare outside foreach, idem for others

2022-07-20 08:28 UTC, callapa commented on www/class/centreon-clapi/centreonConfigurationChange.class.php
> +    ) {}
```suggestion
    ) {
    }
```

2022-07-20 08:52 UTC, callapa approved these changes

2022-07-20 08:53 UTC, jeremyjaouen submitted a review, later dismissed

2022-07-20 08:53 UTC, callapa requested changes

2022-07-20 08:53 UTC, callapa commented on www/include/common/common-Func.php
> +    }
No default option ?

2022-07-26 16:53 UTC, jeremyjaouen approved these changes

2022-07-27 08:17 UTC, callapa approved these changes

2022-07-27 08:18 UTC, merged