enh(update): check platform requirements on updates API call
centreon-archive/centreon-archived pull request #11361
Opened 2022-07-11 13:03 UTC by kduret

## Description

check platform requirements on updates API call

**Fixes** MON-12296

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [x] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 21.04.x
- [ ] 21.10.x
- [ ] 22.04.x
- [x] 22.10.x (master)

<h2> How this pull request can be tested ? </h2>

Check API documentation to make an api call

2022-07-11 14:53 UTC, smau-centreon approved these changes

2022-07-11 15:35 UTC, smau-centreon requested changes

2022-07-11 15:35 UTC, smau-centreon commented on lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "La version PHP %s est requise (%s installée)"
```suggestion
msgstr "La version %s de PHP est requise (%s installée)"
```

2022-07-11 15:35 UTC, smau-centreon commented on lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgid "Error when getting MariaDb version"
```suggestion
msgid "Error when getting MariaDB version"
```

2022-07-11 15:35 UTC, smau-centreon commented on lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "Erreur lors de la récupération de la version MariaDb"
```suggestion
msgstr "Erreur lors de la récupération de la version MariaDB"
```

2022-07-11 15:35 UTC, smau-centreon commented on lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgid "MariaDb version %s required (%s installed)"
```suggestion
msgid "MariaDB version %s required (%s installed)"
```

2022-07-11 15:35 UTC, smau-centreon commented on lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "La version MariaDb %s est requise (%s installée)"
```suggestion
msgstr "La version %s de MariaDB est requise (%s installée)"
```

2022-07-11 15:35 UTC, smau-centreon commented on lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "L'extension PHP %s n'est pas chargée"
```suggestion
msgstr "L'extension %s de PHP n'est pas chargée"
```

2022-07-12 08:03 UTC, kduret reviewed
create validator directory instead of repository
create global database validator with provider for each type : MariaDBValidator, ...

2022-07-12 13:21 UTC, jeremyjaouen approved these changes

2022-07-13 08:08 UTC, smau-centreon approved these changes

2022-07-15 13:07 UTC, merged