feat(api): implement endpoint to update centreon web
centreon-archive/centreon-archived pull request #11391
Opened 2022-07-15 13:09 UTC by kduret

## Description

implement endpoint to update centreon web : `PATCH /api/latest/platform/updates`

**Fixes** MON-12296

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [x] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 21.04.x
- [ ] 21.10.x
- [ ] 22.04.x
- [x] 22.10.x (master)

<h2> How this pull request can be tested ? </h2>

Check API documentation to use endpoint

2022-07-18 06:43 UTC, jeremyjaouen submitted a review, later dismissed

2022-07-18 08:49 UTC, smau-centreon requested changes

2022-07-18 08:49 UTC, smau-centreon commented on lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgid "An error occurred when retrieving current version"
```suggestion
msgid "An error occurred when retrieving the current version"
```

2022-07-18 08:49 UTC, smau-centreon commented on lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgid "Cannot retrieve current version"
```suggestion
msgid "Cannot retrieve the current version"
```

2022-07-18 08:49 UTC, smau-centreon commented on lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "La version actuelle n'a pas pu être trouvée"
```suggestion
msgstr "La version actuelle n'a pas pu être récupérée"
```

2022-07-18 08:49 UTC, smau-centreon commented on lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgid "An error occurred when getting available updates"
```suggestion
msgid "An error occurred when retrieving available updates"
```

2022-07-18 08:49 UTC, smau-centreon commented on lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgid "An error occurred when applying update %s (%s)"
```suggestion
msgid "An error occurred when applying the update %s (%s)"
```

2022-07-18 08:49 UTC, smau-centreon commented on lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgid "Error while locking update process"
```suggestion
msgid "Error while locking the update process"
```

2022-07-18 08:49 UTC, smau-centreon commented on lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgid "Error while unlocking update process"
```suggestion
msgid "Error while unlocking the update process"
```

2022-07-18 08:49 UTC, smau-centreon commented on lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgid "Error when getting database version"
```suggestion
msgid "Error when retrieving the database version"
```

2022-07-18 08:49 UTC, smau-centreon commented on lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgid "Cannot retrieve database version information"
```suggestion
msgid "Cannot retrieve the database version information"
```

2022-07-18 08:49 UTC, smau-centreon commented on lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "Les informations de version de la base de données n'ont pas pu être trouvées"
```suggestion
msgstr "Les informations de version de la base de données n'ont pas pu être récupérées"
```

2022-07-18 09:00 UTC, smau-centreon submitted a review, later dismissed

2022-07-18 14:17 UTC, adr-mo submitted a review, later dismissed

2022-07-18 14:18 UTC, Fxdpt approved these changes, later dismissed

2022-07-18 14:36 UTC, jeremyjaouen submitted a review, later dismissed

2022-07-18 14:39 UTC, smau-centreon submitted a review, later dismissed

2022-07-19 09:34 UTC, jeremyjaouen approved these changes

2022-07-19 09:40 UTC, smau-centreon approved these changes

2022-07-19 09:44 UTC, merged