[fix]MON-13067-install-remove-default-value-for-colors-in-options-table-for-develop
centreon-archive/centreon-archived pull request #11479
Opened 2022-08-01 18:34 UTC by emabassi-ext

## Description

Actually on a fresh install, we insert values for colors in database. (in options table). Those values seems not used anymore and should be removed.
**Fixes** # MON-13067

## Type of change

- [x] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 21.04.x
- [ ] 21.10.x
- [ ] 22.04.x
- [x] 22.10.x (master)

<h2> How this pull request can be tested ? </h2>
Install a new Centreon central server

Execute following request on ‘centreon’ (configuration) database:

SELECT * FROM options WHERE options.key like "color_%"
No result must be found
## Checklist

#### Community contributors & Centreon team

- [x] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2022-08-02 09:38 UTC, jeremyjaouen submitted a review, later dismissed

2022-08-22 11:27 UTC, jeremyjaouen submitted a review, later dismissed

2022-08-24 15:10 UTC, dmyios submitted a review, later dismissed

2022-08-29 08:01 UTC, kduret requested changes
values must be deleted from database in upgrade script to 22.10.0

2022-08-29 08:01 UTC, kduret commented on www/install/sql/centreon/Update-DB-2.8.6.sql
> -UPDATE `options` SET `value` = '#cc99ff' WHERE `key` = 'color_downtime';
this upgrade script must not be touched

2022-08-29 12:42 UTC, emabassi-ext commented on www/install/sql/centreon/Update-DB-2.8.6.sql
> -UPDATE `options` SET `value` = '#cc99ff' WHERE `key` = 'color_downtime';
done!

2022-08-30 07:32 UTC, kduret reviewed
values must be deleted from database in upgrade script to 22.10.0-beta.1

2022-08-30 11:43 UTC, kduret commented on www/install/php/Update-22.10.0-beta.1.php
> +    $pearDB->query("DELETE FROM `options` WHERE `key` = 'oreon_web_path' OR `key` like 'color_%'");
```suggestion
    $pearDB->query("DELETE FROM `options` WHERE `key` = 'oreon_web_path' OR `key` LIKE 'color_%'");
```

2022-08-30 11:43 UTC, kduret commented on www/install/php/Update-22.10.0-beta.1.php
>      $errorMessage = "Unable to delete 'oreon_web_path' option from database";
```suggestion
    $errorMessage = "Unable to delete 'oreon_web_path' and color options from database";
```

2022-08-30 12:08 UTC, kduret approved these changes

2022-09-01 07:16 UTC, wtermellil approved these changes

2022-09-01 07:16 UTC, jeremyjaouen approved these changes

2022-09-05 07:30 UTC, merged