fix(git): resync 21.10.x to dev-21.10.x
centreon-archive/centreon-archived pull request #11502
Opened 2022-08-04 09:10 UTC by chgautier

## Description

resync 21.04.x to dev-21.04.x

## Type of change

- [x] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [x] 21.04.x
- [ ] 21.10.x
- [ ] 22.04.x
- [ ] 22.10.x (master)

2022-08-04 10:12 UTC, a-launois requested changes
There is unresolved conflict in some files  (ex: .github/CODEOWNERS, .github/CODEOWNERS)

2022-08-04 10:12 UTC, kduret requested changes

2022-08-04 10:12 UTC, kduret commented on .github/CODEOWNERS
> +<<<<<<< HEAD
conflict not handled

2022-08-04 12:38 UTC, jdelpierre approved these changes

2022-08-04 12:55 UTC, callapa requested changes

2022-08-04 12:55 UTC, callapa commented on www/class/centreonAuth.SSO.class.php
> +
Already defined
```suggestion
```

2022-08-04 13:24 UTC, callapa approved these changes

2022-08-05 09:57 UTC, chgautier commented
Will remake a new synchro branch

2022-08-05 09:57 UTC, closed without merging