feat(conf) add new bbdo broker stream configurations
centreon-archive/centreon-archived pull request #11507
Opened 2022-08-04 09:32 UTC by a-launois

## Description

Create two new stream types for broker configuration : "BBDO Server" and "BBDO Client" 

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [x] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 21.04.x
- [ ] 21.10.x
- [ ] 22.04.x
- [x] 22.10.x (master)

## Checklist

#### Community contributors & Centreon team

- [x] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2022-08-09 09:48 UTC, smau-centreon approved these changes

2022-08-11 06:05 UTC, kduret commented on lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "Intervalle entre deux tentatives"
```suggestion
msgstr "Intervalle entre deux tentatives (en secondes)"
```

2022-08-11 06:05 UTC, kduret commented on lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "Chemin du certificat de l’autorité de certification"
```suggestion
msgstr "Chemin du certificat de l’autorité de certification (optionnel)"
```

2022-08-11 06:05 UTC, kduret commented on lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "\"Common Name\" du certificat du serveur"
```suggestion
msgstr "\"Common Name\" du certificat du serveur (optionnel)"
```

2022-08-11 06:05 UTC, kduret commented on www/class/config-generate/broker.class.php
> +    private function cleanBbdoStreams(array $object): array
missing phpdoc

2022-08-11 06:05 UTC, kduret commented on www/class/config-generate/broker.class.php
> +                if ($inputCfg['type'] === 'bbdo_server') {
create a constant for `bbdo_server`

2022-08-11 06:05 UTC, kduret commented on www/class/config-generate/broker.class.php
> +                if ($inputCfg['type'] === 'bbdo_client') {
create a constant for `bbdo_client`

2022-08-11 06:05 UTC, kduret commented on www/class/config-generate/broker.class.php
> +                if ($inputCfg['type'] === 'bbdo_server' && $object['output'][$key]['encrypt'] === 'no') {
use constant of `bbdo_server`

2022-08-11 06:05 UTC, kduret commented on www/class/config-generate/broker.class.php
> +                if ($inputCfg['type'] === 'bbdo_client' && $object['output'][$key]['encrypt'] === 'no') {
use constant of `bbdo_client`

2022-08-11 06:05 UTC, kduret commented on www/class/config-generate/broker.class.php
> +    private function cleanBbdoStreams(array $object): array
`$stream` should more appropriate than `$object`

2022-08-11 06:05 UTC, kduret commented on www/install/php/Update-22.10.0-beta.1.php
> +            "optionListId" => 13,
you should not use hardcoded ids, cause some modules can add broker configuration and increment ids
(example : https://github.com/centreon/centreon-bam/blob/develop/www/modules/centreon-bam-server/tools/installBrokerConf.php#L90)

2022-08-11 07:03 UTC, smau-centreon requested changes

2022-08-11 07:03 UTC, smau-centreon commented on lang/es_ES.UTF-8/LC_MESSAGES/messages.po
> +#  msgid "Retry interval (seconds)"
```suggestion
#  msgid "Retry interval (in seconds)"
```

2022-08-11 07:03 UTC, smau-centreon commented on lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgid "Retry interval (seconds)"
```suggestion
msgid "Retry interval (in seconds)"
```

2022-08-11 07:03 UTC, smau-centreon commented on lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "Intervalle entre deux tentatives"
```suggestion
msgstr "Intervalle entre deux tentatives (en secondes)"
```

2022-08-11 07:03 UTC, smau-centreon commented on lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
> +#  msgid "Retry interval (seconds)"
```suggestion
#  msgid "Retry interval (in seconds)"
```

2022-08-11 07:03 UTC, smau-centreon commented on lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
> +#  msgid "Retry interval (seconds)"
```suggestion
#  msgid "Retry interval (in seconds)"
```

2022-08-11 08:21 UTC, TamazC approved these changes, later dismissed

2022-08-11 08:21 UTC, TamazC commented on www/install/php/Update-22.10.0-beta.1.php
> +    $errorMessage = "Impossible to update 'cb_field' table";
It not linked to this PR, but $errorMessage should be found inside the catch block.
We could log messaes like : start to modify description as info and if the error is thrown log file would contain detailed information about the reason.

2022-08-11 12:11 UTC, smau-centreon requested changes

2022-08-11 12:11 UTC, smau-centreon commented on lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgid "Retry interval (en seconds)"
```suggestion
msgid "Retry interval (in seconds)"
```

2022-08-11 12:21 UTC, smau-centreon submitted a review, later dismissed

2022-08-11 13:56 UTC, smau-centreon approved these changes

2022-08-11 14:15 UTC, kduret approved these changes

2022-08-11 14:52 UTC, merged