improve authentication conditions and roles mapping
centreon-archive/centreon-archived pull request #11773
Opened 2022-09-15 17:03 UTC by Med1233

## Description

this one is for updating OpenId authentication form, creating new fields according to API changes

![authentification_conditions](https://user-images.githubusercontent.com/109956462/190464839-37d4e077-8af5-4336-9ff9-337ac36f8673.PNG)

![roles_mapping](https://user-images.githubusercontent.com/109956462/190464924-da542c3b-8bca-4f04-9aef-9a003de839fb.PNG)

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [x] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 21.04.x
- [ ] 21.10.x
- [ ] 22.04.x
- [ ] 22.10.x (master)

<h2> How this pull request can be tested ? </h2>

#### Community contributors & Centreon team

- [x] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have **rebased** my development branch on the base branch (master, maintenance).

2022-09-16 07:54 UTC, jeremyjaouen requested changes

2022-09-16 07:54 UTC, jeremyjaouen commented on www/front_src/src/Authentication/Openid/models.ts
> +  authorization_rules: Array<AuthorizationRelationToAPI> | null;
```suggestion
  authorization_rules: Array<AuthorizationRelationToAPI>;
```
API will only received or return an array (empty or filled) but will not managed null (will throw an error on back end part)

2022-09-16 07:54 UTC, jeremyjaouen commented on www/front_src/src/Authentication/Openid/models.ts
> +  authorized_values: Array<string> | null;
```suggestion
  authorized_values: Array<string>;
```
API will only received or return an array (empty or filled) but will not managed null (will throw an error on back end part)

2022-09-16 07:54 UTC, jeremyjaouen commented on www/front_src/src/Authentication/Openid/models.ts
> +  apply_only_first_role: boolean | null;
```suggestion
  apply_only_first_role: boolean;
```
should always be a boolean

2022-09-16 07:54 UTC, jeremyjaouen commented on www/front_src/src/Authentication/Openid/models.ts
> +  is_enabled: boolean | null;
```suggestion
  is_enabled: boolean;
```
should always be a boolean

2022-09-16 07:54 UTC, jeremyjaouen commented on www/front_src/src/Authentication/Openid/models.ts
> +  is_enabled: boolean | null;
```suggestion
  is_enabled: boolean;
```
should always be a boolean

2022-09-16 07:59 UTC, jeremyjaouen commented
Also you should target the feature branch MON-14870 and not develop

2022-09-19 12:43 UTC, Thebarda commented on package.json
> +    "npm": "^8.19.1",
remove this

2022-09-19 12:43 UTC, Thebarda commented on www/front_src/src/Authentication/translatedLabels.ts
> +export const labelAuthentificationConditions = 'Authentification conditions';
```suggestion
export const labelAuthenticationConditions = 'Authentication conditions';
```

2022-09-19 12:43 UTC, Thebarda commented on www/front_src/src/Authentication/Openid/translatedLabels.tsx
> +export const labelWhichendpointtheConditionsAttributePathComeFrom =
```suggestion
export const labelWhichEndpointTheConditionsAttributePathComeFrom =
```

2022-09-19 12:43 UTC, Thebarda commented on www/front_src/src/Authentication/Openid/translatedLabels.tsx
> +export const labelWhichendpointtheRolesAttributePathComeFrom =
```suggestion
export const labelWhichEndpointTheRolesAttributePathComeFrom =
```

2022-09-19 12:43 UTC, Thebarda commented on www/front_src/src/Authentication/Openid/Form/inputs.ts
> +  labelWhichendpointtheConditionsAttributePathComeFrom,
```suggestion
  labelWhichEndpointTheConditionsAttributePathComeFrom,
```

2022-09-19 12:43 UTC, Thebarda commented on www/front_src/src/Authentication/Openid/Form/inputs.ts
> +  labelWhichendpointtheRolesAttributePathComeFrom,
```suggestion
  labelWhichEndpointtheRolesAttributePathComeFrom,
```

2022-09-19 12:43 UTC, Thebarda commented on www/front_src/src/Authentication/Openid/Form/inputs.ts
> +  labelAuthentificationConditions,
```suggestion
  labelAuthenticationConditions,
```

2022-09-19 12:43 UTC, Thebarda commented on www/front_src/src/Authentication/Openid/Form/inputs.ts
> +    group: labelAuthentificationConditions,
```suggestion
    group: labelAuthenticationConditions,
```

2022-09-19 12:43 UTC, Thebarda commented on www/front_src/src/Authentication/Openid/Form/inputs.ts
> +    group: labelAuthentificationConditions,
```suggestion
    group: labelAuthenticationConditions,
```

2022-09-19 12:43 UTC, Thebarda commented on www/front_src/src/Authentication/Openid/Form/inputs.ts
> +    label: labelWhichendpointtheConditionsAttributePathComeFrom,
```suggestion
    label: labelWhichEndpointtheConditionsAttributePathComeFrom,
```

2022-09-19 12:43 UTC, Thebarda commented on www/front_src/src/Authentication/Openid/Form/inputs.ts
> +          value: 'custom_endpoint',
Use an enum instead for the reusability

2022-09-19 12:43 UTC, Thebarda commented on www/front_src/src/Authentication/Openid/Form/inputs.ts
> +          value: 'custom_endpoint',
Use an enum instead for the reusability

2022-09-19 12:43 UTC, Thebarda commented on www/front_src/src/Authentication/Openid/Form/inputs.ts
> +    fieldName: 'isEnabled',
```suggestion
    fieldName: 'isActive',
```

2022-09-19 12:43 UTC, Thebarda commented on www/front_src/src/Authentication/Openid/models.ts
> +  authentificationConditions: AuthConditions;
```suggestion
  authenticationConditions: AuthConditions;
```

2022-09-19 12:43 UTC, Thebarda commented on www/front_src/src/Authentication/Openid/models.ts
> +  enableConditionsOnIdentityProvider: boolean;
```suggestion
  isEnabled: boolean;
```

2022-09-19 12:43 UTC, Thebarda commented on www/front_src/src/Authentication/Openid/models.ts
> +  conditionsAttributePath: string;
```suggestion
  attributePath: string;
```

2022-09-19 12:43 UTC, Thebarda commented on www/front_src/src/Authentication/Openid/models.ts
> +  conditionsAuthorizedValues: Array<string>;
```suggestion
  authorizedValues: Array<string>;
```

2022-09-19 12:43 UTC, Thebarda commented on www/front_src/src/Authentication/Openid/models.ts
> +  endpointTheConditionsAttributePathComeFrom: Endpoint;
```suggestion
  endpoint: Endpoint;
```

2022-09-19 12:43 UTC, Thebarda commented on www/front_src/src/Authentication/Openid/models.ts
> +  rolesRelations: Array<Relations>;
```suggestion
  applyOnlyFirstRole: boolean;
  attributePath: string;
  endpoint: Endpoint;
  isEnabled: boolean;
  relations: Array<Relations>;
```

2022-09-19 12:43 UTC, Thebarda commented on www/front_src/src/Authentication/Openid/Form/inputs.ts
> +    fieldName: 'enableConditionsOnIdentityProvider',
```suggestion
    fieldName: 'authenticationConditions.isEnabled',
```

2022-09-19 12:43 UTC, Thebarda commented on www/front_src/src/Authentication/Openid/Form/inputs.ts
> +    fieldName: 'conditionsAttributePath',
```suggestion
    fieldName: 'authenticationConditions.attributePath',
```

2022-09-19 12:43 UTC, Thebarda commented on www/front_src/src/Authentication/Openid/Form/inputs.ts
> +    fieldName: 'endpointTheConditionsAttributePathComeFrom',
```suggestion
    fieldName: 'authenticationConditions.endpoint',
```

2022-09-19 12:43 UTC, Thebarda commented on www/front_src/src/Authentication/Openid/Form/inputs.ts
> +    fieldName: 'conditionsAuthorizedValues',
```suggestion
    fieldName: 'authenticationConditions.authorizedValues',
```

2022-09-19 12:43 UTC, Thebarda commented on www/front_src/src/Authentication/Openid/Form/inputs.ts
> +      },
```suggestion
      defaultRowValue: {
        conditionValue: '',
      },
```

2022-09-19 12:43 UTC, Thebarda commented on www/front_src/src/Authentication/Openid/Form/inputs.ts
> +      additionalFieldsToMemoize: ['contactGroup'],
```suggestion
```

2022-09-19 12:43 UTC, Thebarda commented on www/front_src/src/Authentication/Openid/Form/inputs.ts
> +    fieldName: 'rolesIsEnabled',
```suggestion
    fieldName: 'rolesMapping.isEnabled',
```

2022-09-19 12:43 UTC, Thebarda commented on www/front_src/src/Authentication/Openid/Form/inputs.ts
> +    fieldName: 'rolesApplyOnlyFirstRole',
```suggestion
    fieldName: 'rolesMapping.applyOnlyFirstRole',
```

2022-09-19 12:43 UTC, Thebarda commented on www/front_src/src/Authentication/Openid/Form/inputs.ts
> +    fieldName: 'rolesAttributePath',
```suggestion
    fieldName: 'rolesMapping.attributePath',
```

2022-09-19 12:43 UTC, Thebarda commented on www/front_src/src/Authentication/Openid/Form/inputs.ts
> +    fieldName: 'rolesEndpoint',
```suggestion
    fieldName: 'rolesMapping.endpoint',
```

2022-09-19 12:43 UTC, Thebarda commented on www/front_src/src/Authentication/Openid/Form/inputs.ts
> +    fieldName: 'rolesRelations',
```suggestion
    fieldName: 'rolesMapping.relations',
```

2022-09-19 12:43 UTC, Thebarda commented on www/front_src/src/Authentication/Openid/Form/inputs.ts
> +      additionalFieldsToMemoize: ['contactGroup'],
```suggestion
```

2022-09-19 12:43 UTC, Thebarda commented on www/front_src/src/Authentication/Openid/Form/inputs.ts
> +          fieldName: 'roleValue',
```suggestion
          fieldName: 'claimValue',
```

2022-09-19 12:43 UTC, Thebarda commented on www/front_src/src/Authentication/Openid/Form/inputs.ts
> +      },
```suggestion
      defaultRowValue: {
        accessGroup: null,
        claimValue: '',
      },
```

2022-09-21 10:07 UTC, Thebarda commented on www/front_src/src/Authentication/Openid/useValidationSchema.ts
> +  const groupesRelationSchema = Yup.object({
```suggestion
  const groupsRelationSchema = Yup.object({
```

2022-09-21 10:07 UTC, Thebarda commented on www/front_src/src/Authentication/Openid/useValidationSchema.ts
> +      relations: Yup.array().of(groupesRelationSchema),
```suggestion
      relations: Yup.array().of(groupsRelationSchema),
```

2022-09-26 09:19 UTC, Thebarda approved these changes

2022-09-26 09:20 UTC, bdauria approved these changes

2022-09-26 09:23 UTC, merged