Fix: Remove obsolete code in legacy service detail page
centreon-archive/centreon-archived pull request #11848
Opened 2022-09-22 07:57 UTC by emabassi-ext

## Description

Queries should be sanitized (if possible) and bound using PDO statement to reduce attack surface and clean legacy code
 **in** www/include/monitoring/objectDetails/serviceDetails.php

**Line:** 626
**Fixes** # MON-14928

**Remove following block:**

```
$optionsURL = "host_name=" . urlencode($host_name) . "&service_description=" . urlencode($svc_description);

$query = "SELECT id FROM `index_data`, `metrics` WHERE host_name = '" . $pearDBO->escape($host_name) .
    "' AND service_description = '" . $pearDBO->escape($svc_description) . "' AND id = index_id LIMIT 1";
$DBRES = $pearDBO->query($query);
$index_data = 0;
if ($DBRES->rowCount()) {
    $row = $DBRES->fetchRow();
    $index_data = $row['id'];
}
$optionsURL2 = "index=" . $index_data;
```
**As well as:**
```

$tpl->assign("options", $optionsURL);
$tpl->assign("options2", CentreonUtils::escapeSecure($optionsURL2));
```
 

$optionsURL (options) & $optionsURL2 (options2) are no used in /www/include/monitoring/objectDetails/template/serviceDetails.ihtml

## Type of change

- [x] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 21.04.x
- [x] 21.10.x
- [x] 22.04.x
- [x] 22.10.x (master)

<h2> How this pull request can be tested ? </h2>

- Go to “Monitoring > Status Details” and select a service
- Check if no errors appear on page

## Checklist

#### Community contributors & Centreon team

- [x] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2022-09-22 07:59 UTC, kduret submitted a review, later dismissed

2022-09-26 07:11 UTC, jeremyjaouen submitted a review, later dismissed

2022-09-26 07:11 UTC, dmyios submitted a review, later dismissed

2022-09-26 09:19 UTC, callapa requested changes

2022-09-26 09:19 UTC, callapa commented on www/include/monitoring/objectDetails/serviceDetails.php
> -        $index_data = 0;
$index_data is not defined anywhere but is still used on line 864

2022-09-27 08:12 UTC, callapa approved these changes

2022-09-27 08:43 UTC, dmyios approved these changes

2022-09-27 09:56 UTC, merged