(fix) fix custom configuration schema
centreon-archive/centreon-archived pull request #11851
Opened 2022-09-22 11:51 UTC by wtermellil

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 21.04.x
- [ ] 21.10.x
- [ ] 22.04.x
- [ ] 22.10.x (master)

<h2> How this pull request can be tested ? </h2>

Please describe the **procedure** to verify that the goal of the PR is matched. Provide clear instructions so that it can be **correctly tested**.

Any **relevant details** of the configuration to perform the test should be added.

## Checklist

#### Community contributors & Centreon team

- [ ] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have **rebased** my development branch on the base branch (master, maintenance).

2022-09-22 11:52 UTC, Thebarda approved these changes

2022-09-22 13:03 UTC, Thebarda approved these changes

2022-09-22 14:26 UTC, jeremyjaouen approved these changes

2022-09-23 06:23 UTC, jeremyjaouen requested changes
You should also rename the PR as you not only fix the schema but fix the role mapping

2022-09-23 06:23 UTC, jeremyjaouen commented on src/Core/Security/Authentication/Infrastructure/Provider/OpenId.php
> +        /*$userClaims = [];
remove all this code if it is no more used

2022-09-23 06:23 UTC, jeremyjaouen commented on src/Core/Security/ProviderConfiguration/Application/OpenId/UseCase/UpdateOpenIdConfiguration/UpdateOpenIdConfiguration.php
> +            dd($ex->getMessage());
remove dd 
```suggestion
```

2022-09-23 07:07 UTC, closed without merging