FIX: Remove unused AppKey for Remote Server
centreon-archive/centreon-archived pull request #11860
Opened 2022-09-22 21:19 UTC by hyahiaoui-ext

## Description

Removing the following files

src/Centreon/Domain/Service/AppKeyGeneratorService.php

src/Centreon/Tests/AppKeyGeneratorServiceTest.php

**Fixes** # MON-3810

## Type of change

- [x] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 21.04.x
- [ ] 21.10.x
- [x] 22.04.x
- [x] 22.10.x (master)

## Checklist

#### Community contributors & Centreon team

- [x] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2022-09-22 21:23 UTC, kduret approved these changes, later dismissed

2022-09-23 08:14 UTC, wtermellil requested changes
did you test ? it's working fine ?
The class `AppKeyGeneratorService` is called in `ServiceProvider.php`, `register ` method

2022-09-23 08:29 UTC, hyahiaoui-ext commented
> did you test ? it's working fine ? The class `AppKeyGeneratorService` is called in `ServiceProvider.php`, `register ` method

In the ticket was mentionned, no need to because i did already removed appkey usage in another PR, didn't know it was still used.

2022-09-26 07:10 UTC, jeremyjaouen approved these changes

2022-09-26 07:11 UTC, callapa approved these changes

2022-09-26 07:16 UTC, wtermellil approved these changes

2022-09-26 08:33 UTC, merged