FIX: Missing translation(FR, EN, PT, etc.) in OpenId Connect configuration form
centreon-archive/centreon-archived pull request #11929
Opened 2022-10-04 13:10 UTC by emabassi-ext

## Description

Missing translation for new blocs:

- authentication condition

- roles mapping

- groups mapping

- “login attribute path”

![image](https://user-images.githubusercontent.com/108519266/193826481-d6620efc-1168-4225-9023-d3afeffbe96c.png)

**Fixes** # MON-15265

## Type of change

- [x] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 21.04.x
- [ ] 21.10.x
- [ ] 22.04.x
- [x] 22.10.x (master)

<h2> How this pull request can be tested ? </h2>
switch language from english to french and look if translation apears in  _Administration  > authentication > configuration openid connect_

## Checklist

#### Community contributors & Centreon team

- [x] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2022-10-06 12:26 UTC, cg-tw requested changes

2022-10-06 12:26 UTC, cg-tw commented on lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "Adresses de clients de confiance"
```suggestion
msgstr "Adresses des clients de confiance"
```

2022-10-06 12:26 UTC, cg-tw commented on lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "Blacklist d'adresses de clients"
```suggestion
msgstr "Liste noire d'adresses de clients"
```

2022-10-06 12:26 UTC, cg-tw commented on lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "Activer les conditions sur l'identity provider"
```suggestion
msgstr "Activer les conditions sur le fournisseur d'identité"
```

2022-10-06 12:26 UTC, cg-tw commented on lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "Conditions chemin des attributs"
```suggestion
msgstr "Chemin de l'attribut des conditions"
```

2022-10-06 12:26 UTC, cg-tw commented on lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "endpoint d'introspection"
```suggestion
msgstr "Point d'entrée d'introspection"
```

2022-10-06 12:26 UTC, cg-tw commented on lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "Information de l'utilisateur"
```suggestion
msgstr "Informations utilisateur"
```

2022-10-06 12:26 UTC, cg-tw commented on lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "Ne postulez qu'au premier rôle"
```suggestion
msgstr "Appliquer uniquement le premier rôle"
```

2022-10-06 12:26 UTC, cg-tw commented on lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "Chemin d'accès aux attributs de rôles"
```suggestion
msgstr "Chemin d'accès à l'attribut de rôles"
```

2022-10-06 12:26 UTC, cg-tw commented on lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "De quel endpoint provient le chemin d'accès de l'attribut rôles ?"
```suggestion
msgstr "De quel point d'entrée provient le chemin d'accès de l'attribut de rôles ?"
```

2022-10-06 12:26 UTC, cg-tw commented on lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "De quel endpoint provient le chemin de l'attribut des conditions ?"
```suggestion
msgstr "De quel point d'entrée provient le chemin de l'attribut des conditions ?"
```

2022-10-06 12:26 UTC, cg-tw commented on lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "Chemin des attributs de groupes"
```suggestion
msgstr "Chemin de l'attribut de groupes"
```

2022-10-06 12:26 UTC, cg-tw commented on lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "De quel endpoint provient le chemin de l'attribut des groupes ?"
```suggestion
msgstr "De quel point d'entrée provient le chemin de l'attribut des groupes ?"
```

2022-10-06 12:26 UTC, cg-tw commented on lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "Définissez votre endpoint"
```suggestion
msgstr "Définissez votre point d'entrée"
```

2022-10-06 12:26 UTC, cg-tw commented on lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "Chemin de l'attribut de connexion"
```suggestion
msgstr "Chemin de l'attribut d'identifiant"
```

2022-10-07 08:29 UTC, cg-tw approved these changes

2022-10-10 09:20 UTC, lpinsivy approved these changes

2022-10-10 09:20 UTC, merged