fix(Resources/AnomalyDetection/): fixes
centreon-archive/centreon-archived pull request #11959
Opened 2022-10-07 14:25 UTC by Noha-ElAbrouki

adding modal for closing confirmation : 
Closing the modal (click on cross or outside). If the user has confirmed his choice or made no changes, the modal closes without warning. Otherwise, popin “you have unsaved changed, do you want to proceed? cancel, confirm” (wording TBD)

2022-10-08 13:36 UTC, Thebarda commented
There is a component in our design system for that ^^.
UnsavedChangesDialog, our something like that

2022-10-10 07:02 UTC, bdauria commented
@Noha-ElAbrouki can we try to have a rounded badge with the same size in all cases for the slider indicator?

2022-10-12 08:31 UTC, Noha-ElAbrouki commented
> UnsavedChangesDialog

this component contains required props which doesn't fit my needs and it has text msg defined , i think it's dedicated for forms. the component used here is also from centreon-frontend (Dialog)

2022-10-12 11:21 UTC, bdauria commented on www/front_src/src/Resources/Graph/Performance/AnomalyDetection/AnomalyDetectionSlider.tsx
> +          <ResetIcon color={isDefaultValue ? 'disabled' : 'primary'} />
Should be is in start adornment

2022-10-12 11:23 UTC, bdauria commented on www/front_src/src/Resources/Graph/Performance/AnomalyDetection/AnomalyDetectionSlider.tsx
> +  },
Use material default instead, with a non contained variant

2022-10-12 12:16 UTC, Noha-ElAbrouki commented on www/front_src/src/Resources/Graph/Performance/AnomalyDetection/AnomalyDetectionSlider.tsx
> +  },
i used iConButton instead 🤔

2022-10-12 12:17 UTC, Noha-ElAbrouki commented on www/front_src/src/Resources/Graph/Performance/AnomalyDetection/AnomalyDetectionSlider.tsx
> +          <ResetIcon color={isDefaultValue ? 'disabled' : 'primary'} />
i used iConButton instead 🤔

2022-10-12 12:22 UTC, Thebarda commented on lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
> +#  msgstr "confirme"
```suggestion l'
#  msgstr "Confirme"
```

2022-10-12 12:22 UTC, Thebarda commented on lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
> +#  msgstr "confirme"
```suggestion
#  msgstr "Confirme"
```

2022-10-12 12:22 UTC, Thebarda commented on www/front_src/src/Resources/Graph/Performance/AnomalyDetection/AnomalyDetectionSlider.tsx
> +          <ResetIcon color={isDefaultValue ? 'disabled' : 'primary'} />
The prop is starIcon

2022-10-12 12:22 UTC, Thebarda commented on www/front_src/src/Resources/Graph/Performance/AnomalyDetection/AnomalyDetectionSlider.tsx
> +        </IconButton>
First use the Button component then use the startIcon prop: https://mui.com/material-ui/api/button/

2022-10-12 12:51 UTC, smau-centreon requested changes

2022-10-12 12:51 UTC, smau-centreon commented on lang/es_ES.UTF-8/LC_MESSAGES/messages.po
> +msgid "you have unsaved changed, do you want to proceed?"
```suggestion
msgid "You have unsaved changed, do you want to proceed?"
```

2022-10-12 12:51 UTC, smau-centreon commented on lang/es_ES.UTF-8/LC_MESSAGES/messages.po
> +msgstr "no ha guardado los cambios, ¿quiere continuar?"
```suggestion
msgstr "No ha guardado los cambios, ¿quiere continuar?"
```

2022-10-12 12:51 UTC, smau-centreon commented on lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgid "you have unsaved changed, do you want to proceed?"
```suggestion
msgid "You have unsaved changed, do you want to proceed?"
```

2022-10-12 12:51 UTC, smau-centreon commented on lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "vous avez des modifications non enregistrées, voulez-vous continuer?"
```suggestion
msgstr "Vous avez des modifications non enregistrées, voulez-vous continuer?"
```

2022-10-12 12:51 UTC, smau-centreon commented on lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
> +msgid "you have unsaved changed, do you want to proceed?"
```suggestion
msgid "You have unsaved changed, do you want to proceed?"
```

2022-10-12 12:51 UTC, smau-centreon commented on lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "você não salvou as alterações, deseja continuar?"
```suggestion
msgstr "Você não salvou as alterações, deseja continuar?"
```

2022-10-12 12:51 UTC, smau-centreon commented on lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
> +msgid "you have unsaved changed, do you want to proceed?"
```suggestion
msgid "You have unsaved changed, do you want to proceed?"
```

2022-10-12 12:51 UTC, smau-centreon commented on lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
> +msgstr "você não salvou as alterações, deseja continuar?"
```suggestion
msgstr "Você não salvou as alterações, deseja continuar?"
```

2022-10-12 16:18 UTC, bdauria approved these changes

2022-10-13 07:37 UTC, smau-centreon approved these changes

2022-10-13 10:01 UTC, cg-tw requested changes

2022-10-13 10:01 UTC, cg-tw commented on lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgid "You have unsaved changed, do you want to proceed?"
```suggestion
msgid "You have unsaved changes, do you want to proceed?"
```

2022-10-13 10:01 UTC, cg-tw commented on lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
> +msgid "You have unsaved changed, do you want to proceed?"
```suggestion
msgid "You have unsaved changes, do you want to proceed?"
```

2022-10-13 10:01 UTC, cg-tw commented on lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
> +msgid "You have unsaved changed, do you want to proceed?"
```suggestion
msgid "You have unsaved changes, do you want to proceed?"
```

2022-10-13 10:01 UTC, cg-tw commented on www/front_src/src/Resources/translatedLabels.ts
> +  'you have unsaved changed, do you want to proceed?';
```suggestion
  'You have unsaved changes, do you want to proceed?';
```

2022-10-13 10:01 UTC, cg-tw commented on lang/es_ES.UTF-8/LC_MESSAGES/messages.po
> +msgid "You have unsaved changed, do you want to proceed?"
```suggestion
msgid "You have unsaved changes, do you want to proceed?"
```

2022-10-13 12:05 UTC, Thebarda commented on www/front_src/src/Resources/translatedLabels.ts
> +export const labelUseDefaultValue = 'Set to default value';
```suggestion
export const labelSetToDefaultValue = 'Set to default value';
```

2022-10-13 12:17 UTC, cg-tw requested changes

2022-10-13 12:17 UTC, cg-tw commented on www/front_src/src/Resources/translatedLabels.ts
>  export const labelPointsOutsideOfEnvelopeCount = 'points out of envelope';
```suggestion
export const labelPointsOutsideOfEnvelopeCount = 'points outside of the envelope';
```

2022-10-13 12:17 UTC, cg-tw commented on lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "Définir sur la valeur par défaut"
```suggestion
msgstr "Rétablir la valeur par défaut"
```

2022-10-13 12:17 UTC, cg-tw commented on www/front_src/src/Resources/translatedLabels.ts
> +export const labelUseDefaultValue = 'Set to default value';
```suggestion
export const labelUseDefaultValue = 'Reset to default value';
```

2022-10-13 12:17 UTC, cg-tw commented on lang/es_ES.UTF-8/LC_MESSAGES/messages.po
> +msgid "Set to default value"
```suggestion
msgid "Reset to default value"
```

2022-10-13 12:17 UTC, cg-tw commented on lang/es_ES.UTF-8/LC_MESSAGES/messages.po
>  msgid "points out of envelope"
```suggestion
msgid "points outside of the envelope"
```

2022-10-13 12:17 UTC, cg-tw commented on lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgid "Set to default value"
```suggestion
msgid "Reset to default value"
```

2022-10-13 12:17 UTC, cg-tw commented on lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
>  msgid "points out of envelope"
```suggestion
msgid "points outside of the envelope"
```

2022-10-13 12:17 UTC, cg-tw commented on lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
> +msgid "Set to default value"
```suggestion
msgid "Reset to default value"
```

2022-10-13 12:17 UTC, cg-tw commented on lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
>  msgid "points out of envelope"
```suggestion
msgid "points outside of the envelope"
```

2022-10-13 12:17 UTC, cg-tw commented on lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
> +msgid "Set to default value"
```suggestion
msgid "Reset to default value"
```

2022-10-13 12:17 UTC, cg-tw commented on lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
>  msgid "points out of envelope"
```suggestion
msgid "points outside of the envelope"
```

2022-10-13 12:45 UTC, Thebarda approved these changes

2022-10-13 14:36 UTC, cg-tw approved these changes

2022-10-13 15:37 UTC, merged