Mon 15265 fix typo
centreon-archive/centreon-archived pull request #11966
Opened 2022-10-10 12:36 UTC by lpinsivy

## Description

**PLEASE MAKE SURE THAT THE BRANCH PR INCLUDES JIRA TICKET ID** (_for centreon-internal_)

Please include a short resume of the changes and what is the purpose of PR. Any relevant information should be added to help:
* **QA Team** (Quality Assurance) with tests.
* **reviewers** to understand what are the stakes of the pull request.

**Fixes** # (issue)

## Type of change

- [x] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 21.04.x
- [ ] 21.10.x
- [ ] 22.04.x
- [x] 22.10.x (master)

<h2> How this pull request can be tested ? </h2>

Please describe the **procedure** to verify that the goal of the PR is matched. Provide clear instructions so that it can be **correctly tested**.

Any **relevant details** of the configuration to perform the test should be added.

## Checklist

#### Community contributors & Centreon team

- [ ] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have **rebased** my development branch on the base branch (master, maintenance).

2022-10-10 15:34 UTC, smau-centreon requested changes

2022-10-10 15:34 UTC, smau-centreon commented on lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "Adresses de clients sur liste noire"
```suggestion
msgstr "Adresses des clients sur liste noire"
```

2022-10-10 15:34 UTC, smau-centreon commented on lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "Adresses de clients sur liste noire"
```suggestion
msgstr "Adresses des clients sur liste noire"
```

2022-10-10 15:34 UTC, smau-centreon commented on lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "Point d'entrée d'information utilisateur"
```suggestion
msgstr "Point d'entrée d'informations utilisateur"
```

2022-10-11 11:51 UTC, smau-centreon approved these changes

2022-10-13 13:26 UTC, a-launois approved these changes

2022-10-13 14:26 UTC, merged