Mon 15022 improve telemetry authentications
centreon-archive/centreon-archived pull request #11969
Opened 2022-10-10 14:31 UTC by lpinsivy

## Description

**PLEASE MAKE SURE THAT THE BRANCH PR INCLUDES JIRA TICKET ID** (_for centreon-internal_)

Please include a short resume of the changes and what is the purpose of PR. Any relevant information should be added to help:
* **QA Team** (Quality Assurance) with tests.
* **reviewers** to understand what are the stakes of the pull request.

**Fixes** # (issue)

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [x New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 21.04.x
- [ ] 21.10.x
- [ ] 22.04.x
- [x] 22.10.x (master)

<h2> How this pull request can be tested ? </h2>

Please describe the **procedure** to verify that the goal of the PR is matched. Provide clear instructions so that it can be **correctly tested**.

Any **relevant details** of the configuration to perform the test should be added.

## Checklist

#### Community contributors & Centreon team

- [ ] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have **rebased** my development branch on the base branch (master, maintenance).

2022-10-13 12:23 UTC, callapa requested changes
CamelCase only, no snake_case
Don't use the fetchRow method, use fetchColumn instead

2022-10-13 12:53 UTC, callapa requested changes
No snake_case, CamelCase only

2022-10-13 12:53 UTC, callapa commented on www/class/centreonStatistics.class.php
> +            $custom_configuration = json_decode($row['custom_configuration'], true);
No snake_case, CamelCase only
```suggestion
            $custom_configuration = json_decode($row['custom_configuration'], true);
```

2022-10-14 07:15 UTC, wtermellil commented on www/class/centreonStatistics.class.php
> +                            => count($authenticationConditions['trusted_client_addresses']) ?? 0,
this would probably cause a warning

2022-10-14 07:16 UTC, wtermellil commented on www/class/centreonStatistics.class.php
> +                        'authorized_values' => count($authenticationConditions['authorized_values']) ?? 0,
this would probably cause a warning

2022-10-14 07:18 UTC, wtermellil requested changes
this PR would probably cause some warnings

2022-10-18 08:13 UTC, callapa commented on www/class/centreonStatistics.class.php
> +                        => isset($customConfiguration['trusted_client_addresses']) ? count() : 0,
count() ?

2022-10-21 11:37 UTC, wtermellil approved these changes

2022-10-21 11:44 UTC, jeremyjaouen approved these changes

2022-10-21 13:50 UTC, abuathier commented on www/class/centreonStatistics.class.php
> +                        ? count($customConfiguration['trusted_client_addresses']) : 0,
Why not this type of syntax which does not impact performance in php 7+ and seems more readable to me.
👉️ to propagate in other places if you think it useful.
```
=> count($customConfiguration['trusted_client_addresses'] ?? [])
```

2022-10-21 13:50 UTC, abuathier commented on www/class/centreonStatistics.class.php
> +            } elseif ($row['type'] === 'web-sso') {
Prefer switch for readability ? (same performance as strict comparison in php 7+ when all cases are of the same type without any doubt)
```
switch ($row['type']) {
    case 'local': 
        // ...
}
```

2022-10-21 13:50 UTC, abuathier commented on www/class/centreonStatistics.class.php
> +                    'auto_import' => ($customConfiguration['auto_import'] ? true : false)
Same as cast 👉️ propagate in other places of this commit if you change these two lines.
```suggestion
                    'verify_peer' => (bool)$customConfiguration['verify_peer'],
                    'auto_import' => (bool)$customConfiguration['auto_import']
```

2022-10-21 13:50 UTC, abuathier commented on www/class/centreonStatistics.class.php
> +        );
What do you want to do ? (a) adding a LDAP key if not set, or (b) real technical merging ?

If (a), I suggest one of these two syntaxes : 

1) express the logic via a "if"
```
$data = [$this->getNewAuthenticationOptions()][0];
if (!isset($data['LDAP'])) {
    $data['LDAP'] = $this->getLDAPAuthenticationOptions();
}
// FYI, php 8.1 above "if" syntax sugar equivalent we will be able to use one day
// $data['LDAP'] ??= $this->getLDAPAuthenticationOptions();
```

2) use the php `+` for arrays
```
$data = [$this->getNewAuthenticationOptions()][0] 
    + ['LDAP' => $this->getLDAPAuthenticationOptions()];
```

2022-10-21 13:55 UTC, abuathier commented on www/class/centreonStatistics.class.php
> +        );
Note: my proposals implicitly means that calling `$this->getLDAPAuthenticationOptions()` is not mandatory for this function.

If not, this is probably a very bad code pattern and need comments for that.

2022-10-21 15:19 UTC, callapa approved these changes

2022-10-21 15:43 UTC, abuathier commented on www/class/centreonStatistics.class.php
> +            $customConfiguration = json_decode($row['custom_configuration'], true);
@wtermellil C'est quoi la politique autour des json_decode ?
Car là ça peut return `FALSE `et donc péter le code en aval.

2022-10-21 15:48 UTC, ghost commented on www/class/centreonStatistics.class.php
> +            $customConfiguration = json_decode($row['custom_configuration'], true);
I sometime saw when errors are quiet this expression : `$array = json_decode($string, true) ?: [];`

2022-10-21 15:57 UTC, abuathier approved these changes

2022-10-24 14:22 UTC, merged