MON-2988: fix myAccount special characters update
centreon-archive/centreon-archived pull request #8598
Opened 2020-04-14 15:59 UTC by garnier-quentin

## Description

Fix when you have special characters in your name. for example: é

## Type of change

- [X] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [ ] 2.8.x
- [ ] 18.10.x
- [ ] 19.04.x
- [X] 19.10.x
- [X] 20.04.x (master)

<h2> How this pull request can be tested ? </h2>

Create an user with special character (é for example). Connect with that user and edit it (save). You cannot login. 

## Checklist

- [X] I followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have made corresponding changes to the **documentation**.
- [ ] I have **rebased** my development branch on the base branch (master, maintenance).

2020-04-23 09:35 UTC, jeremyjaouen submitted a review, later dismissed

2020-11-03 08:17 UTC, jeremyjaouen commented on www/include/Administration/myAccount/DB-Func.php
>          }
I think this part could be simplified:

if ($encryptType == 2) {
    $password_encrypted = sha1($ret['contact_passwd']);
} else {
    $password_encrypted = md5($ret['contact_passwd']);
}

2020-11-03 08:18 UTC, jeremyjaouen submitted a review, later dismissed

2020-11-03 08:22 UTC, kduret commented on www/include/Administration/myAccount/DB-Func.php
> +    if (isset($ret['contact_passwd']) && $ret['contact_passwd']) {
```suggestion
    if (!empty($ret['contact_passwd'])) {
```

2020-11-03 08:23 UTC, kduret approved these changes, later dismissed

2020-11-03 08:50 UTC, sc979 requested changes

2020-11-03 08:50 UTC, sc979 commented on www/include/Administration/myAccount/DB-Func.php
> +        !empty($ret['contact_email']) ? $ret['contact_email'] : null,
htmlentities is required

2020-11-03 09:22 UTC, sc979 commented on www/include/Administration/myAccount/DB-Func.php
> +        CentreonUtils::ESCAPE_ILLEGAL_CHARS
```suggestion
    $ret['contact_email'] = !empty($ret['contact_email'])
        ? CentreonUtils::escapeSecure($ret['contact_email'], CentreonUtils::ESCAPE_ILLEGAL_CHARS)
        : '';
        
```

2020-11-03 09:22 UTC, sc979 commented on www/include/Administration/myAccount/DB-Func.php
> +        CentreonUtils::ESCAPE_ILLEGAL_CHARS
kindly, could you modify as it's suggested upper ?

2020-11-03 09:31 UTC, sc979 approved these changes

2020-11-03 09:32 UTC, jeremyjaouen approved these changes

2020-11-03 09:40 UTC, kduret approved these changes

2020-11-03 09:56 UTC, merged