fix(security) hide password value
centreon-archive/centreon-archived pull request #8878
Opened 2020-07-28 09:33 UTC by loiclau

## Description

hide password value with inspector

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [ ] 19.04.x
- [ ] 19.10.x
- [ ] 20.04.x
- [ ] 20.10.x (master)

<h2> How this pull request can be tested ? </h2>

inspect input

## Checklist

- [ ] I followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have made corresponding changes to the **documentation**.
- [ ] I have **rebased** my development branch on the base branch (master, maintenance).

2020-07-28 09:36 UTC, loiclau commented on www/include/Administration/parameters/ldap/form.php
> +
```suggestion
```

2020-07-28 15:08 UTC, kduret requested changes

2020-07-28 15:08 UTC, kduret commented on www/class/centreonLDAP.class.php
> +            var_dump($query);
remove debug

2020-07-28 15:08 UTC, kduret commented on www/class/centreonLDAP.class.php
> +        if (isset($gopt["bind_pass"]) && $gopt["bind_pass"] === "******") {
`******` should be a constant to avoid typo issue when it's used

2020-08-03 07:41 UTC, kduret requested changes
Regarding current legacy architecture, you should declare `public const PASSWD_OCCULTATION = '******';` in CentreonAuth.class.php
You could reuse it everywhere by using : `CentreonAuth::PASSWD_OCCULTATION`
So it will be define in a single place and use the power of constants ;)

2020-08-03 07:41 UTC, kduret commented on www/include/Administration/parameters/knowledgeBase/formKnowledgeBase.php
> +const PWS_OCCULTATION = '******';
you'll probably have a notice cause this const is already defined in `www/include/Administration/parameters/general/form.php`

2020-08-05 09:25 UTC, kduret submitted a review, later dismissed

2020-08-05 09:48 UTC, jeremyjaouen commented on www/class/centreonLDAP.class.php
> +WHERE `ari_name` <> 'bind_pass' AND ar_id = " . $this->db->escape($arId);
bad indent

2020-08-07 07:40 UTC, jeremyjaouen approved these changes

2020-08-07 07:48 UTC, kduret approved these changes

2020-08-07 07:49 UTC, merged