feat(api): add resource check endpoint
centreon-archive/centreon-archived pull request #8885
Opened 2020-07-30 13:47 UTC by adr-mo

## Description

This endpoint allows user (and especialy the Event View) to schedule a forced check on a resource.

Endpoint `/monitoring/resources/check`

/!\ Unit tests are missing that is why the PR is in Draft state but it can be already reviewed

**Fixes** None

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [x] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [ ] 19.04.x
- [ ] 19.10.x
- [ ] 20.04.x
- [x] 20.10.x (master)

<h2> How this pull request can be tested ? </h2>

This PR can be tested by calling the endpoint. Example of body content can be found in the documentation

## Checklist

- [x] I followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [x] I have made corresponding changes to the **documentation**.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2020-08-04 10:38 UTC, sc979 commented on tests/php/Centreon/Domain/Check/CheckServiceTest.php
>  }
```suggestion
}

```

2020-08-07 13:00 UTC, jeremyjaouen requested changes

2020-08-07 13:01 UTC, jeremyjaouen submitted a review, later dismissed

2020-08-07 13:03 UTC, jeremyjaouen approved these changes

2020-08-07 13:05 UTC, loiclau approved these changes

2020-08-07 13:41 UTC, merged