fix(host categories): Sanitize inputs
centreon-archive/centreon-archived pull request #8914
Opened 2020-08-13 11:45 UTC by jeremyjaouen

## Description

This PR sanitize the differents input for host categories

**Fixes** MON-5907

## Type of change

- [x] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [x] 19.04.x
- [x] 19.10.x
- [x] 20.04.x
- [x] 20.10.x (master)

## Checklist

- [x] I followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have made corresponding changes to the **documentation**.
- [ ] I have **rebased** my development branch on the base branch (master, maintenance).

2020-08-13 12:29 UTC, lpinsivy submitted a review, later dismissed

2020-08-17 10:19 UTC, sc979 requested changes

2020-08-17 10:19 UTC, sc979 commented on www/include/configuration/configObject/host_categories/DB-Func.php
> +function enableHostCategoriesInDB(?int $hc_id = null, $hc_arr = [])
as $hc_id has a default null value, why add the '?' before int ?

2020-08-17 10:19 UTC, sc979 commented on www/include/configuration/configObject/host_categories/DB-Func.php
> +        $statement = $pearDB->prepare($query);
as $query is used only one time you can merge these two lines

2020-08-17 10:19 UTC, sc979 commented on www/include/configuration/configObject/host_categories/DB-Func.php
> +        $statement2 = $pearDB->prepare($query);
as $query is used only one time you can merge these two lines

2020-08-17 10:19 UTC, sc979 commented on www/include/configuration/configObject/host_categories/DB-Func.php
> +function disableHostCategoriesInDB(?int $hc_id = null, $hc_arr = [])
kindly use camelCase instead

2020-08-17 10:19 UTC, sc979 commented on www/include/configuration/configObject/host_categories/DB-Func.php
> +        $statement = $pearDB->prepare($query);
as $query is used only one time you can merge these two lines

2020-08-17 10:19 UTC, sc979 commented on www/include/configuration/configObject/host_categories/DB-Func.php
> +        $statement2 = $pearDB->prepare($query);
as $query is used only one time you can merge these two lines

2020-08-17 10:19 UTC, sc979 commented on www/include/configuration/configObject/host_categories/DB-Func.php
> +                        $bindParams[':hc_name'] = [\PDO::PARAM_STR => $value2];
JAC :
Why use bindParam instead of bindValue ?

2020-08-17 10:19 UTC, sc979 commented on www/include/configuration/configObject/host_categories/DB-Func.php
> +                $statement = $pearDB->prepare($query);
Are you trying to prepare and bind values on a $query = null (https://github.com/centreon/centreon/pull/8914/files#diff-0bb59ae13ef1e73cccc8b91988afb651R234)?

2020-08-17 10:19 UTC, sc979 commented on www/include/configuration/configObject/host_categories/DB-Func.php
> +function updateHostCategoriesHosts($hc_id, $ret = [])
kindly use camelCase

2020-08-17 10:19 UTC, sc979 commented on www/include/configuration/configObject/host_categories/DB-Func.php
> +function deleteHostCategoriesInDB($hostcategories = [])
kindly use camelCase
$hostcategories -> $hostCategories

2020-08-17 10:19 UTC, sc979 commented on www/include/configuration/configObject/host_categories/DB-Func.php
> +function enableHostCategoriesInDB(?int $hc_id = null, $hc_arr = [])
kindly use camelCase

2020-08-18 07:31 UTC, sc979 requested changes

2020-08-18 07:31 UTC, sc979 commented on www/include/configuration/configObject/host_categories/DB-Func.php
> +function enableHostCategoriesInDB(int $hcId = null, $hc_arr = [])
@jeremyjaouen , you forgot the $hc_arr when you remaned in camelCase the variables

2020-08-18 07:31 UTC, sc979 commented on www/include/configuration/configObject/host_categories/DB-Func.php
> +function disableHostCategoriesInDB(int $hcId = null, $hc_arr = [])
$hc_arr

2020-08-18 07:31 UTC, sc979 commented on www/include/configuration/configObject/host_categories/DB-Func.php
> +        $statement = $pearDB->prepare("SELECT hc_name FROM `hostcategories` WHERE `hc_id` = :hc_id LIMIT 1");
kindly move the prepare statement before the loop on lines 147 and 152

2020-08-18 07:31 UTC, sc979 commented on www/include/configuration/configObject/host_categories/DB-Func.php
> +                    ? $val .= ($value2 != null ? (", '" . $value2 . "'") : ", NULL")
isn't $val always null ? you don't seem to have the usage of $value2 concatenation anymore.
Maybe you could replace line 229 : $val by $value2 instead

2020-08-18 07:31 UTC, sc979 commented on www/include/configuration/configObject/host_categories/DB-Func.php
> +        $statement = $pearDB->prepare("UPDATE hostcategories SET hc_activate = '0' WHERE hc_id = :hc_id");
kindly move the prepare statement before the loop

2020-08-18 07:31 UTC, sc979 commented on www/include/configuration/configObject/host_categories/DB-Func.php
> +        $statement2 = $pearDB->prepare("SELECT hc_name FROM `hostcategories` WHERE `hc_id` = :hc_id LIMIT 1");
kindly move the prepare statement before the loop

2020-08-18 07:31 UTC, sc979 commented on www/include/configuration/configObject/host_categories/DB-Func.php
> +        $statement = $pearDB->prepare("UPDATE hostcategories SET hc_activate = '1' WHERE hc_id = :hc_id");
kindly move the prepare statement before the loop

2020-08-18 07:31 UTC, sc979 commented on www/include/configuration/configObject/host_categories/DB-Func.php
> +        $statement2 = $pearDB->prepare("SELECT hc_name FROM `hostcategories` WHERE `hc_id` = :hc_id LIMIT 1");
kindly move the prepare statement before the loop

2020-08-18 08:38 UTC, sc979 requested changes

2020-08-18 08:38 UTC, sc979 commented on www/include/configuration/configObject/host_categories/DB-Func.php
>                  if($query) {
this check can be concatenated with line 227

2020-08-18 08:38 UTC, sc979 commented on www/include/configuration/configObject/host_categories/DB-Func.php
>                      : $query = null;
PDO won't like a prepare(null)... on empty $bindParams, you should skip the next steps until line 244

2020-08-18 08:51 UTC, sc979 submitted a review, later dismissed

2020-08-18 13:36 UTC, sc979 approved these changes

2020-08-19 08:49 UTC, loiclau approved these changes

2020-08-19 08:51 UTC, merged