fix(servicegroups): Sanitize Inputs
centreon-archive/centreon-archived pull request #8919
Opened 2020-08-14 12:38 UTC by jeremyjaouen

## Description

This PR sanitize the differents input for service group form

**Fixes** MON-5520

## Type of change

- [x] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [x] 19.04.x
- [x] 19.10.x
- [x] 20.04.x
- [x] 20.10.x (master)

## Checklist

- [x] I followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have made corresponding changes to the **documentation**.
- [ ] I have **rebased** my development branch on the base branch (master, maintenance).

2020-08-17 10:45 UTC, sc979 requested changes

2020-08-17 10:45 UTC, sc979 commented on www/include/configuration/configObject/servicegroup/DB-Func.php
> +    if ($statement->rowCount() >= 1 && $sg["sg_id"] != $id) {
couldn't you use strict comparaison ?

2020-08-17 10:45 UTC, sc979 commented on www/include/configuration/configObject/servicegroup/DB-Func.php
> +                $statement = $pearDB->prepare($query);
are you trying to prepare a $query = null ? line 193

2020-08-17 10:45 UTC, sc979 commented on www/include/configuration/configObject/servicegroup/DB-Func.php
> +    $statement = $pearDB->prepare($query);
as $query is used only one time, kindly merge these two lines

2020-08-17 10:45 UTC, sc979 commented on www/include/configuration/configObject/servicegroup/DB-Func.php
> +    $statement = $pearDB->prepare($query);
as $query is used only one time, kindly merge these two lines

2020-08-17 10:45 UTC, sc979 commented on www/include/configuration/configObject/servicegroup/DB-Func.php
> +        $statement = $pearDB->prepare($query);
as $query is used onyl one time, kindly merge these two lines

2020-08-17 10:45 UTC, sc979 commented on www/include/configuration/configObject/servicegroup/DB-Func.php
> +function updateServiceGroupServices($sg_id, $ret = [], $increment = false)
kindly use camelCase

2020-08-17 10:45 UTC, sc979 commented on www/include/configuration/configObject/servicegroup/DB-Func.php
> +function updateServiceGroup($sg_id, $ret = [])
kindly use camelCase

2020-08-17 10:45 UTC, sc979 commented on www/include/configuration/configObject/servicegroup/DB-Func.php
> +                $statement = $pearDB->prepare($query);
kindly merge these two lines

2020-08-17 10:45 UTC, sc979 commented on www/include/configuration/configObject/servicegroup/DB-Func.php
> +                    $statement2 = $pearDB->prepare($query);
kindly merge these two lines

2020-08-17 10:45 UTC, sc979 commented on www/include/configuration/configObject/servicegroup/DB-Func.php
> +            $statement = $pearDB->prepare($query);
kindly merge these two lines

2020-08-17 10:45 UTC, sc979 commented on www/include/configuration/configObject/servicegroup/DB-Func.php
> +                $statement2 = $pearDB->prepare($query);
kindly merge these two lines

2020-08-17 10:45 UTC, sc979 commented on www/include/configuration/configObject/servicegroup/DB-Func.php
>          for ($i = 0; $i < count($retTmp); $i++) {
could you move the prepared statement of lines 479 and 486 before this loop. It will require lesser resources on DB

2020-08-17 10:45 UTC, sc979 commented on www/include/configuration/configObject/servicegroup/DB-Func.php
>      for ($i = 0; $i < count($retTmp); $i++) {
could you move the prepared statement of lines 479 and 486 before this loop. It will require lesser resources on DB

2020-08-17 10:45 UTC, sc979 commented on www/include/configuration/configObject/servicegroup/DB-Func.php
>      for ($i = 0; $i < count($retTmp); $i++) {
could you move the prepared statement of lines 538 and 548 before this loop. It will require lesser resources on DB

2020-08-17 10:45 UTC, sc979 commented on www/include/configuration/configObject/servicegroup/DB-Func.php
> +        $statement = $pearDB->prepare($query);
kindly merge these two lines

2020-08-17 10:45 UTC, sc979 commented on www/include/configuration/configObject/servicegroup/DB-Func.php
> +            $statement2 = $pearDB->prepare($query);
kindly merge these two lines

2020-08-17 10:45 UTC, sc979 commented on www/include/configuration/configObject/servicegroup/serviceGroup.php
>          break; #Add a Servicegroup
If possible, replace perl comment by php one : '#' -> '//'

2020-08-18 08:42 UTC, sc979 requested changes

2020-08-18 08:42 UTC, sc979 commented on www/include/configuration/configObject/servicegroup/DB-Func.php
>      if ($increment == false) {
```suggestion
    if ($increment == false && $sgId !== false) {
```

2020-08-18 08:43 UTC, sc979 submitted a review, later dismissed

2020-08-18 12:57 UTC, loiclau commented on www/include/configuration/configObject/servicegroup/DB-Func.php
> +                if ($query) {
if ($val) {
 $query = ...

2020-08-18 16:32 UTC, sc979 submitted a review, later dismissed

2020-08-19 08:20 UTC, loiclau approved these changes, later dismissed

2020-08-19 11:45 UTC, sc979 approved these changes, later dismissed

2020-08-19 14:08 UTC, sc979 approved these changes

2020-08-20 08:45 UTC, loiclau approved these changes

2020-08-20 08:55 UTC, merged

2020-08-20 08:56 UTC, sc979 requested changes

2020-08-20 08:56 UTC, sc979 commented on www/include/configuration/configObject/servicegroup/DB-Func.php
> +        $statement = $pearDB->prepare("SELECT sg_name FROM `servicegroup` WHERE `sg_id` = :sg_id LIMIT 1");
kindly move the prepare statement out of the loop