enh(host): Allows to create host services according to host templates
centreon-archive/centreon-archived pull request #8941
Opened 2020-08-26 08:34 UTC by callapa

## Description

Added a mechanism to create host services when a host is added.

**Fixes** # (issue)

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [x] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [ ] 19.04.x
- [ ] 19.10.x
- [ ] 20.04.x
- [x] 20.10.x (master)

<h2> How this pull request can be tested ? </h2>

Currently, this PR will only be testable with the centeron-autodiscovery module.

## Checklist

- [x] I followed the **coding style guidelines** provided by Centreon
- [x] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [x] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have made corresponding changes to the **documentation**.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2020-08-26 10:45 UTC, sc979 commented on src/Centreon/Domain/Engine/EngineConfiguration.php
> + * Copyright 2005 - 2019 Centreon (https://www.centreon.com/)
```suggestion
 * Copyright 2005 - 2020 Centreon (https://www.centreon.com/)
```

2020-08-26 10:46 UTC, sc979 commented on src/Centreon/Domain/AccessControlList/Interfaces/AccessControlListRepositoryInterface.php
> + * Copyright 2005 - 2019 Centreon (https://www.centreon.com/)
```suggestion
 * Copyright 2005 - 2020 Centreon (https://www.centreon.com/)
```

2020-08-26 10:49 UTC, sc979 commented on src/Centreon/Domain/Engine/Interfaces/EngineConfigurationRepositoryInterface.php
> + * Copyright 2005 - 2019 Centreon (https://www.centreon.com/)
```suggestion
 * Copyright 2005 - 2020 Centreon (https://www.centreon.com/)
```

2020-08-26 10:50 UTC, sc979 commented on src/Centreon/Domain/Engine/Interfaces/EngineConfigurationServiceInterface.php
> + * Copyright 2005 - 2019 Centreon (https://www.centreon.com/)
```suggestion
 * Copyright 2005 - 2020 Centreon (https://www.centreon.com/)
```

2020-08-26 11:46 UTC, sc979 requested changes

2020-08-26 11:46 UTC, sc979 commented on src/Centreon/Domain/HostConfiguration/Host.php
> +        if ($hostTemplate->getType() !== Host::TYPE_HOST_TEMPLATE) {
Could you translate the thrown exception too ?

2020-08-26 11:46 UTC, sc979 commented on src/Centreon/Domain/ServiceConfiguration/ExtendedService.php
> + * Copyright 2005 - 2019 Centreon (https://www.centreon.com/)
```suggestion
 * Copyright 2005 - 2020 Centreon (https://www.centreon.com/)
```

2020-08-26 11:46 UTC, sc979 commented on src/Centreon/Domain/ServiceConfiguration/HostTemplateService.php
> + * Copyright 2005 - 2019 Centreon (https://www.centreon.com/)
```suggestion
 * Copyright 2005 - 2020 Centreon (https://www.centreon.com/)
```

2020-08-26 11:46 UTC, sc979 commented on src/Centreon/Domain/ServiceConfiguration/HostTemplateService.php
> +            throw new \InvalidArgumentException('This host is not a template');
```suggestion
            throw new \InvalidArgumentException(_('This host is not a template'));
```

2020-08-26 11:46 UTC, sc979 commented on src/Centreon/Domain/ServiceConfiguration/HostTemplateService.php
> +        if ($hostTemplate->getType() !== Host::TYPE_HOST_TEMPLATE) {
Could you add the translation

2020-08-26 11:46 UTC, sc979 commented on src/Centreon/Domain/ServiceConfiguration/HostTemplateService.php
> +        if ($serviceTemplate->getServiceType() !== Service::TYPE_TEMPLATE) {
Could you add the translation

2020-08-26 11:46 UTC, sc979 commented on src/Centreon/Domain/ServiceConfiguration/HostTemplateService.php
> +            throw new \InvalidArgumentException('This service is not a template');
```suggestion
            throw new \InvalidArgumentException(_('This service is not a template'));
```

2020-08-26 11:46 UTC, sc979 commented on src/Centreon/Domain/ServiceConfiguration/ServiceConfigurationService.php
> +            throw new ServiceConfigurationException(_('The host id can not be null'));
```suggestion
            throw new ServiceConfigurationException(_('The host id cannot be null'));
```

2020-08-26 11:46 UTC, sc979 commented on lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgid "The host id can not be null"
```suggestion
msgid "The host id cannot be null"
```

2020-08-26 11:46 UTC, sc979 commented on src/Centreon/Domain/ServiceConfiguration/ServiceConfigurationService.php
> +            throw new ServiceConfigurationException(_('Impossible to find the Engine configuration'));
Was this sentence already translated ?

2020-08-26 11:46 UTC, sc979 commented on src/Centreon/Domain/ServiceConfiguration/ServiceConfigurationService.php
> +         * **We only retrieve templates that are enabled.**
```suggestion
         * **We only retrieve enabled templates.**
```

2020-08-26 11:46 UTC, sc979 commented on src/Centreon/Domain/ServiceConfiguration/ServiceConfigurationService.php
> +        if (!empty($hostTemplateIds)) {
the foreach won't loop if $hostTemplateIds is empty. IMHO, this check is useless as there's no else case

2020-08-26 11:46 UTC, sc979 commented on src/Centreon/Domain/ServiceConfiguration/ServiceConfigurationService.php
> +                        && $illegalObjectNameCharacters !== null
If the field is empty, the query will return null : 
![image](https://user-images.githubusercontent.com/34628915/91298380-39e03500-e7a0-11ea-981c-1467e9ea8620.png)
![image](https://user-images.githubusercontent.com/34628915/91298415-49f81480-e7a0-11ea-83f5-c2e3d2b3c345.png)
This mean that, the $servicesToBeCreated, will remain empty

2020-08-26 11:46 UTC, sc979 commented on src/Centreon/Domain/ServiceConfiguration/ServiceConfigurationService.php
> +            throw new ServiceConfigurationException('', 0, $ex);
Shouldn't a message been throwned ?
If, yes, please add the translation too

2020-08-26 11:46 UTC, sc979 commented on src/Centreon/Infrastructure/HostConfiguration/HostConfigurationRepositoryRDB.php
> +         * Adds a host template by browsing all templates recursively until you find the parent template.
```suggestion
         * Add a host template by browsing all templates recursively until you find the parent template.
```

2020-08-26 11:46 UTC, sc979 commented on src/Centreon/Infrastructure/ServiceConfiguration/ServiceConfigurationRepositoryRDB.php
> +            VALUES (:template_id, :command_id, :description, :alias, :is_locked, :is_activated)'
:is_activated value, is not linked to any column

2020-08-27 08:09 UTC, sc979 approved these changes, later dismissed

2020-08-31 07:01 UTC, jeremyjaouen submitted a review, later dismissed

2020-09-07 08:44 UTC, kduret submitted a review, later dismissed

2020-09-07 08:44 UTC, kduret commented on lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "Erreur lors de la recherche de modèles d'hôtes et de services connexes"
```suggestion
msgstr "Erreur lors de la recherche d'hôtes et de modèles de service liés"
```

2020-09-07 14:20 UTC, loiclau approved these changes, later dismissed

2020-09-07 14:27 UTC, loiclau approved these changes

2020-09-07 14:28 UTC, kduret approved these changes

2020-09-07 15:04 UTC, merged