fix(secu): correct ACL on returned user list
centreon-archive/centreon-archived pull request #8951
Opened 2020-08-31 14:38 UTC by sc979

## Description

Returns only allowed groups list on the internal API, called from the share view feature instead of the whole user list on the platform

**Fixes** # (MON-5530)

## Type of change

- [x] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [x] 19.04.x
- [x] 19.10.x
- [x] 20.04.x
- [x] 20.10.x (master)

<h2> How this pull request can be tested ? </h2>

Please contact me

2020-08-31 14:39 UTC, sc979 commented
PR rebased on https://github.com/centreon/centreon/pull/8948

2020-08-31 15:16 UTC, callapa requested changes

2020-08-31 15:16 UTC, callapa commented on www/class/centreonCustomView.class.php
> +                    $allowedGroupIds .= $groupId;
Please join this two conditions to avoid the following case: ',,'

2020-08-31 15:18 UTC, callapa commented on www/class/centreonCustomView.class.php
> +                    $allowedGroupIds .= $groupId;
It would be best to use an array instead of a string.

2020-09-02 15:54 UTC, callapa approved these changes

2020-09-03 08:41 UTC, loiclau approved these changes

2020-09-03 08:45 UTC, merged