fix(security) fix hotlink on media
centreon-archive/centreon-archived pull request #8958
Opened 2020-09-01 16:01 UTC by loiclau

## Description

protect media

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [ ] 19.04.x
- [ ] 19.10.x
- [ ] 20.04.x
- [ ] 20.10.x (master)

<h2> How this pull request can be tested ? </h2>

## Checklist

- [ ] I followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have made corresponding changes to the **documentation**.
- [ ] I have **rebased** my development branch on the base branch (master, maintenance).

2020-09-03 08:16 UTC, sc979 approved these changes, later dismissed

2020-09-07 08:49 UTC, kduret submitted a review, later dismissed
LGTM
But we'll need to check every possible formats
I don't know if we can import `.PNG` (uppercase)

2020-09-07 12:52 UTC, loiclau commented on www/img/media/.htaccess
> +RewriteRule .*\.(gif|GIF|jpg|JPG|jpeg|bmp|BMP|mpeg|png)$ - [F]
```suggestion
RewriteRule .*\.(jpg|jpeg|png|gif||gd2)$ - [F]
```

2020-09-07 12:54 UTC, loiclau commented on www/img/media/.htaccess
> +RewriteRule .*\.(gif|GIF|jpg|JPG|jpeg|bmp|BMP|mpeg|png)$ - [F]
https://github.com/centreon/centreon/blob/master/www/include/options/media/images/syncDir.php#L66

2020-09-07 12:56 UTC, sc979 approved these changes, later dismissed

2020-09-07 12:57 UTC, kduret requested changes

2020-09-07 12:57 UTC, kduret commented on www/img/media/.htaccess
> +RewriteRule .*\.(jpg|jpeg|png|gif||gd2)$ - [F]
```suggestion
RewriteRule .*\.(jpg|jpeg|png|gif|gd2)$ - [F]
```

2020-09-07 12:59 UTC, kduret approved these changes

2020-09-07 12:59 UTC, sc979 approved these changes

2020-09-10 13:46 UTC, merged