enh(api): refactor resource details endpoints
centreon-archive/centreon-archived pull request #8972
Opened 2020-09-09 13:25 UTC by kduret

## Description

refactor resource details endpoint : 
* do not use monitoring repository to get host & service
* avoid entity mutation
* add property to resource endpoints (mainly `links` subobject)

**Fixes** MON-5216

## Type of change

- [x] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [ ] 19.04.x
- [ ] 19.10.x
- [ ] 20.04.x
- [x] 20.10.x (master)

<h2> How this pull request can be tested ? </h2>

Check api documentation to validate resource endpoints

2020-09-10 07:55 UTC, loiclau approved these changes

2020-09-10 15:38 UTC, bdauria approved these changes

2020-09-10 18:39 UTC, callapa requested changes

2020-09-10 18:39 UTC, callapa commented on src/Centreon/Domain/Monitoring/ResourceFilter.php
> +        $this->hostIds = $hostIds;
How to ensure that the given table contains a list of integers?

2020-09-10 18:39 UTC, callapa commented on src/Centreon/Domain/Monitoring/ResourceFilter.php
> +        $this->serviceIds = $serviceIds;
How to ensure that the given table contains a list of integers?

2020-09-10 18:39 UTC, callapa commented on src/Centreon/Application/Controller/MonitoringResourceController.php
> +    private function providePerformanceGraphEndpoint($resources)
The name of this function does not match its description.
provide performance != Add performance

Missing variable typing

2020-09-11 08:22 UTC, callapa approved these changes

2020-09-11 14:22 UTC, merged