enh(host configuration): Added features to check if a host name has already been used and to change the host status
centreon-archive/centreon-archived pull request #8977
Opened 2020-09-10 15:15 UTC by callapa

## Description

Added features to check if a host name has already been used and to change the host status.

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [x] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [ ] 19.04.x
- [ ] 19.10.x
- [ ] 20.04.x
- [x] 20.10.x (master)

## Checklist

- [x] I followed the **coding style guidelines** provided by Centreon
- [x] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [x] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have made corresponding changes to the **documentation**.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2020-09-11 08:12 UTC, kduret requested changes

2020-09-11 08:12 UTC, kduret commented on src/Centreon/Domain/HostConfiguration/HostConfigurationService.php
> +            throw new HostConfigurationException(_(''));
Missing message

2020-09-11 08:12 UTC, kduret commented on src/Centreon/Domain/HostConfiguration/HostConfigurationService.php
> +            throw new HostConfigurationException(_(''));
Missing message

2020-09-11 08:51 UTC, kduret approved these changes, later dismissed

2020-09-14 12:55 UTC, jeremyjaouen submitted a review, later dismissed

2020-09-14 15:08 UTC, kduret submitted a review, later dismissed

2020-09-14 15:18 UTC, jeremyjaouen approved these changes, later dismissed

2020-09-15 07:27 UTC, jeremyjaouen approved these changes

2020-09-15 07:35 UTC, sc979 approved these changes

2020-09-15 07:36 UTC, kduret approved these changes

2020-09-15 08:11 UTC, merged