Comparing only with value because it seems the data is of a different type
centreon-archive/centreon-archived pull request #8978
Opened 2020-09-10 17:28 UTC by alfredosilvestre-natixis

## Description

When adding a view shared from another user, the preferences are not loaded

**Fixes**
Possible fix for #7875 

## Type of change

- [ X ] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [ X ] 19.04.x
- [ X ] 19.10.x
- [ X ] 20.04.x
- [ X ] 20.10.x (master)

<h2> How this pull request can be tested ? </h2>

1. Create a custom view, set some preferences and share it
2. On another user, add the custom view
3. Preferences are loaded correctly

## Checklist

- [ X ] I followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have made corresponding changes to the **documentation**.
- [ X ] I have **rebased** my development branch on the base branch (master, maintenance).

2020-09-11 09:08 UTC, cgagnaire commented
Hi @alfredosilvestre-natixis,
Thank you for this PR.
I'll let @kduret and @loiclau take a quick look at it as they worked around this code recently.

2020-09-14 07:08 UTC, sc979 approved these changes

2020-09-14 13:11 UTC, jeremyjaouen approved these changes

2020-11-23 08:22 UTC, kduret requested changes
It should be better to apply the patch here : https://github.com/centreon/centreon/blob/master/www/class/centreonDB.class.php#L342
By returning `(int) $number`

2021-02-23 09:40 UTC, alfredosilvestre-natixis commented
I accidentally removed my fork repository while trying to fix it, #9506 replaces this PR

2021-02-23 09:40 UTC, closed without merging