enh(platformstatus) insert topology in new table
centreon-archive/centreon-archived pull request #8997
Opened 2020-09-16 12:01 UTC by loiclau

## Description

Add existing nagios_server & remote_servers entries into the new topology table

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [ ] 19.04.x
- [ ] 19.10.x
- [ ] 20.04.x
- [ ] 20.10.x (master)

<h2> How this pull request can be tested ? </h2>

Please describe the **procedure** to verify that the goal of the PR is matched. Provide clear instructions so that it can be **correctly tested**.

Any **relevant details** of the configuration to perform the test should be added.

## Checklist

- [ ] I followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have made corresponding changes to the **documentation**.
- [ ] I have **rebased** my development branch on the base branch (master, maintenance).

2020-09-16 12:07 UTC, loiclau commented on www/install/php/Update-20.10.0.post.php
> +    $stmt->bindValue(':name', $name, \PDOap::PARAM_STR);
```suggestion
    $stmt->bindValue(':name', $name, \PDO::PARAM_STR);
```

2020-09-16 12:14 UTC, jeremyjaouen submitted a review, later dismissed

2020-09-16 13:05 UTC, callapa approved these changes, later dismissed

2020-09-16 13:21 UTC, kduret commented on www/install/php/Update-20.10.0.post.php
> +    $remoteServerQuery = $pearDB->query("SELECT `id` FROM remote_servers WHERE ip = " . $row['ns_ip_address']);
```suggestion
    $remoteServerQuery = $pearDB->query("SELECT `id` FROM remote_servers WHERE ip = '" . $row['ns_ip_address'] . "'");
```

2020-09-16 13:21 UTC, kduret commented on www/install/php/Update-20.10.0.post.php
> +    $stmt->bindValue(':parent', $parent, \PDO::PARAM_INT);
```suggestion
    $stmt->bindValue(':parent', (int)$parent, \PDO::PARAM_INT);
```

2020-09-16 13:34 UTC, kduret submitted a review, later dismissed

2020-09-16 13:39 UTC, sc979 requested changes

2020-09-16 13:39 UTC, sc979 commented on www/install/php/Update-20.10.0.post.php
> +$localStmt = $pearDB->query("SELECT `id` FROM nagios_server WHERE localhost = '1'");
these queries should be added in the upper transaction commit / rollback block

2020-09-16 15:45 UTC, sc979 approved these changes, later dismissed

2020-09-17 08:08 UTC, jeremyjaouen approved these changes, later dismissed

2020-09-17 08:10 UTC, jeremyjaouen commented on www/install/php/Update-20.10.0.post.php
> +        $stmt->bindValue(':id', (int)$row['id'], \PDO::PARAM_INT);
```suggestion
        $stmt->bindValue(':parent', (int) $parent, \PDO::PARAM_INT);
        $stmt->bindValue(':id', (int) $row['id'], \PDO::PARAM_INT);
```

2020-09-17 13:38 UTC, jeremyjaouen approved these changes

2020-09-17 13:45 UTC, sc979 approved these changes

2020-09-18 07:37 UTC, merged