enh(wizard): Register informations from Wizard into platform_topology table
centreon-archive/centreon-archived pull request #9043
Opened 2020-09-28 07:51 UTC by jeremyjaouen

## Description

This PR allow the Wizard to register informations into platform_topology table. 
Also, the Select Remote Server autocompletion is now made from platform_topology, and an autocompletion for Poller part has been added.

**Fixes** # MON-5866 MON-5867

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [x] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [ ] 19.04.x
- [ ] 19.10.x
- [ ] 20.04.x
- [x] 20.10.x (master)

<h2> How this pull request can be tested ? </h2>

- Create a new poller  / Remote Server into the wizard, you should see it into the platform_topology table.
- Create a new poller / Remote Server using the Radio button "Select a Poller / Remote Server", you should select some pending Remote / Poller.

## Checklist

- [x] I followed the **coding style guidelines** provided by Centreon
- [x] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [x] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have made corresponding changes to the **documentation**.
- [ ] I have **rebased** my development branch on the base branch (master, maintenance).

2020-09-28 07:58 UTC, kduret commented on src/CentreonRemote/Application/Webservice/CentreonConfigurationRemote.php
> +                'type' => 'remote',
use `PlatformTopology::TYPE_REMOTE`

2020-09-28 07:58 UTC, kduret commented on src/CentreonRemote/Application/Webservice/CentreonConfigurationRemote.php
> +                'type' => 'poller',
use `PlatformTopology::TYPE_POLLER`

2020-09-28 07:58 UTC, kduret commented on src/CentreonRemote/Application/Webservice/CentreonConfigurationRemote.php
> +                'type' => 'poller',
use `PlatformTopology::TYPE_POLLER`

2020-09-28 07:58 UTC, kduret commented on www/front_src/src/components/forms/poller/PollerFormStepOne.js
> +      // this.initializeFromRest(true);//set to true of false if abandon the upper case condition
remove comments

2020-09-28 11:04 UTC, kduret submitted a review, later dismissed

2020-09-28 11:20 UTC, callapa commented on src/CentreonRemote/Application/Webservice/CentreonConfigurationRemote.php
> +use Exception;
No need to do this, use this class like this: `\Exception.`

2020-09-28 11:33 UTC, callapa requested changes, later dismissed

2020-09-28 11:33 UTC, callapa commented on src/CentreonRemote/Application/Webservice/CentreonConfigurationRemote.php
> +        $dbAdapter->query('SELECT * FROM `nagios_server` WHERE `ns_ip_address` = ?', [$serverIP]);
Use SELECT COUNT(*) instead.

2020-09-28 11:43 UTC, Thebarda commented on www/front_src/src/components/forms/remoteServer/RemoteServerFormStepOne.js
> +    this.props.change('server_name', platform.server_name);
```suggestion
   const { waitList, change } = this.props;
    const platform = waitList.find((server) => server.ip === value);
    change('server_name', platform.server_name);
```

2020-09-28 12:21 UTC, bdauria approved these changes, later dismissed

2020-09-28 14:01 UTC, sc979 commented on src/CentreonRemote/Application/Webservice/CentreonConfigurationRemote.php
> +            throw new \Exception('This IP Address already exist');
```suggestion
            throw new \Exception(_('This IP Address already exist'));
```

2020-09-29 07:13 UTC, Thebarda approved these changes

2020-09-29 09:17 UTC, sc979 approved these changes

2020-09-29 09:31 UTC, merged