MON-6061: gorgone user can apply cfg + enhance security files
centreon-archive/centreon-archived pull request #9057
Opened 2020-09-30 08:44 UTC by garnier-quentin

## Description

Gorgone user can use clapi command to generate configuration

## Type of change

- [X] Patch fixing an issue (non-breaking change)
- [X] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [ ] 19.04.x
- [ ] 19.10.x
- [ ] 20.04.x
- [X] 20.10.x (master)

<h2> How this pull request can be tested ? </h2>

Gorgone user cannot execute: centreon -u admin -p centreon -a APPLYCFG -v 3

## Checklist

- [X] I followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have made corresponding changes to the **documentation**.
- [ ] I have **rebased** my development branch on the base branch (master, maintenance).

2020-09-30 12:45 UTC, sc979 requested changes
Source installation will not be able to apply: https://github.com/centreon/centreon-build/pull/322/files
Please backport these changes to the installation script too

2020-09-30 14:57 UTC, garnier-quentin commented
My change 

> Source installation will not be able to apply: https://github.com/centreon/centreon-build/pull/322/files
> Please backport these changes to the installation script too



> Source installation will not be able to apply: https://github.com/centreon/centreon-build/pull/322/files
> Please backport these changes to the installation script too

My change is for pollers (not central server). So it's not applicable on source central script.

2020-09-30 15:22 UTC, sc979 approved these changes

2020-10-01 08:46 UTC, kduret approved these changes

2020-10-01 08:47 UTC, merged