feat(api): Get Platform Topology for helios usage
centreon-archive/centreon-archived pull request #9128
Opened 2020-10-15 13:41 UTC by jeremyjaouen

## Description
GET endpoint /platform/topology/helios to retrieve a topology with a JSON Graph Schema Responsse

**Fixes** # MON-5720

## Type of change

- [] Patch fixing an issue (non-breaking change)
- [x] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [ ] 19.04.x
- [ ] 19.10.x
- [ ] 20.04.x
- [x] 20.10.x (master)

<h2> How this pull request can be tested ? </h2>

Please describe the **procedure** to verify that the goal of the PR is matched. Provide clear instructions so that it can be **correctly tested**.

Any **relevant details** of the configuration to perform the test should be added.

## Checklist

- [ ] I followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have made corresponding changes to the **documentation**.
- [ ] I have **rebased** my development branch on the base branch (master, maintenance).

2020-11-03 12:16 UTC, Nohzoh commented
We should avoid references to Helios in the core code.

- This endpoint provides the platform topology in a jsongraph format. There is no need to precise that it is for Helios.
- It might be used for purpose other than Helios.
- And Helios is the name of a service that could be changed further.

In my opinion, this is a bad idea to use the name "Helios" in the whole code of this PR.

2020-11-06 16:18 UTC, sc979 requested changes

2020-11-06 16:18 UTC, sc979 commented on tests/php/Centreon/Domain/PlatformTopology/PlatformTopologyServiceTest.php
> +        $this->expectExceptionMessage("Topology address for parent platform ID: '3' not found");
IMHO : no exceptions should be returned when unconsistent data are found.

2020-11-06 16:18 UTC, sc979 commented on src/Centreon/Application/Controller/PlatformTopologyController.php
> +            $platformTopology = $this->platformTopologyService->getPlatformTopology();
```suggestion
            /*
             * @var Platform[] $platformTopology
             */
            $platformTopology = $this->platformTopologyService->getPlatformTopology();
```

2020-11-06 16:18 UTC, sc979 commented on src/Centreon/Domain/PlatformTopology/PlatformTopologyService.php
> +        }
```suggestion
        if ($PlatformTopology === null) {
            throw new EntityNotFoundException(_('No Platform Topology found'));
        }
```

2020-11-06 16:18 UTC, sc979 commented on src/Centreon/Domain/PlatformTopology/PlatformTopologyService.php
> +        }
Kindly add the french translation too

2020-11-06 16:18 UTC, sc979 commented on src/Centreon/Domain/PlatformTopology/PlatformTopologyService.php
> +        $PlatformTopology = $this->platformTopologyRepository->getPlatformTopology();
$PlatformTopology -> $platformTopology

2020-11-06 16:18 UTC, sc979 commented on src/Centreon/Domain/PlatformTopology/PlatformTopologyService.php
> +            if ($platform->getType() !== Platform::TYPE_CENTRAL) {
kindly check with the PM for the remote top level case

2020-11-06 16:18 UTC, sc979 commented on src/Centreon/Domain/PlatformTopology/PlatformRelation.php
> +    public function setRelation(string $relation): self
JAC : As discussed (https://github.com/centreon/centreon/pull/9128/files#diff-f6f9666fe2d8e90852d098c972983d6314c938d10c2189a1cf44b612da7ecae5R612)

2020-11-10 08:21 UTC, sc979 requested changes

2020-11-10 08:21 UTC, sc979 commented on src/Centreon/Domain/PlatformTopology/Interfaces/PlatformTopologyRepositoryInterface.php
> +    public function findPlatform(int $serverId): ?Platform;
findPlatform -> findPlatformById

2020-11-10 08:21 UTC, sc979 commented on src/Centreon/Domain/PlatformTopology/PlatformTopologyService.php
> +                $platformParent = $this->platformTopologyRepository->findPlatform(
findPlatform -> findPlatformById

2020-11-10 08:21 UTC, sc979 commented on src/Centreon/Domain/PlatformTopology/PlatformTopologyService.php
> +                $platform->setParentAddress($platformParent->getAddress());
what will happen if the endpoint is called from a remote ?
eg: platformParentAddress === null && $platform->getType !== Platform::TYPE_CENTRAL

2020-11-10 08:21 UTC, sc979 commented on src/Centreon/Infrastructure/PlatformTopology/PlatformTopologyRepositoryRDB.php
> +    public function findPlatform(int $serverId): ?Platform
findPlatform -> findPlatformById

2020-11-10 08:21 UTC, sc979 commented on tests/php/Centreon/Domain/PlatformTopology/PlatformTopologyServiceTest.php
> +            ->method('findPlatform')
findPlatform -> findPlatformById

2020-11-10 08:26 UTC, sc979 commented on src/Centreon/Domain/PlatformTopology/Platform.php
> -        if (!in_array($relationType, self::AVAILABLE_RELATIONS)) {
Shouldn't this check be added in the relation's setter entity ?
https://github.com/centreon/centreon/blob/eb7172b987df2e942931007a2f93b6c67ab0ce24/src/Centreon/Domain/PlatformTopology/PlatformRelation.php#L93

2020-11-10 09:59 UTC, sc979 commented on src/Centreon/Domain/PlatformTopology/PlatformRelation.php
> +            throw new \InvalidArgumentException(sprintf(_("The type of relation '%s' is not allowed"), $relation));
IMHO : You shouldn't throw an exception here, and instead set a default value

2020-11-10 10:06 UTC, sc979 approved these changes

2020-11-17 08:39 UTC, kduret approved these changes

2020-11-17 09:11 UTC, merged