check isset macro_filters
centreon-archive/centreon-archived pull request #9192
Opened 2020-11-09 14:25 UTC by jeremyjaouen

## Description

Check if the macro_filters are set before using them into an array_map.

**Fixes** # MON-6297

## Type of change

- [x] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [ ] 19.10.x
- [x] 20.04.x
- [x] 20.10.x
- [x] 21.04.x (master)

<h2> How this pull request can be tested ? </h2>

- Go To Configuration > Pollers > Engine Configuration
- Click on "Add" Button
- Fill the configuration name
- Submit

No Error should appears into PHP Logs

## Checklist

- [x] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have made corresponding changes to the **documentation**.
- [ ] I have **rebased** my development branch on the base branch (master, maintenance).

2020-11-09 14:29 UTC, sc979 requested changes

2020-11-09 14:29 UTC, sc979 commented on www/include/configuration/configNagios/DB-Func.php
> +    if (isset($_REQUEST['macro_filter'])) {
```suggestion
    if (isset($_REQUEST['macros_filter'])) {
```

2020-11-10 08:15 UTC, sc979 approved these changes

2020-11-10 08:48 UTC, loiclau approved these changes

2020-11-10 09:10 UTC, callapa approved these changes

2020-11-10 10:44 UTC, merged