Mon 6362 hostgroup endpoint new
centreon-archive/centreon-archived pull request #9287
Opened 2020-12-10 14:02 UTC by loiclau

## Description

Please include a short resume of the changes and what is the purpose of PR. Any relevant information should be added to help:
* **QA Team** (Quality Assurance) with tests.
* **reviewers** to understand what are the stakes of the pull request.

**Fixes** # (issue)

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [ ] 19.10.x
- [ ] 20.04.x
- [ ] 20.10.x
- [ ] 21.04.x (master)

<h2> How this pull request can be tested ? </h2>

Please describe the **procedure** to verify that the goal of the PR is matched. Provide clear instructions so that it can be **correctly tested**.

Any **relevant details** of the configuration to perform the test should be added.

## Checklist

- [ ] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have made corresponding changes to the **documentation**.
- [ ] I have **rebased** my development branch on the base branch (master, maintenance).

2020-12-11 08:29 UTC, jeremyjaouen commented on src/Centreon/Domain/HostConfiguration/HostGroupService.php
> +            throw new HostGroupException(_('Error while searching for the host group'), 0, $ex);
shouldn't you use HostGroupException::searchHostGroupsException() ?

2021-01-07 10:59 UTC, callapa requested changes
Please to change the date in the copyright also.

2021-01-07 10:59 UTC, callapa commented on doc/API/centreon-api-v2.1.yaml
> +    Media.NullableImage:
Still needed?

2021-01-07 10:59 UTC, callapa commented on config/routes/Centreon/host_group.yaml
> +  condition: "request.attributes.get('version.is_beta') == true"
condition: "request.attributes.get('version') >= 2.1"

2021-01-07 10:59 UTC, callapa commented on src/Centreon/Domain/HostConfiguration/Exception/HostGroupException.php
> + * This class is designed to contain all exceptions for the context of the host template.
Be careful when copying and pasting the code.

2021-01-07 10:59 UTC, callapa commented on src/Centreon/Domain/HostConfiguration/Exception/HostGroupException.php
> +    public static function searchHostGroupsException(\Exception $ex): self
Missing phpdoc

2021-01-07 10:59 UTC, callapa commented on src/Centreon/Domain/HostConfiguration/Exception/HostGroupFactoryException.php
> + * This class is designed to provide all exceptions for the HostTemplate entity factory.
Be careful when copying and pasting the code.

2021-01-07 10:59 UTC, callapa commented on src/Centreon/Domain/HostConfiguration/Interfaces/HostGroupWriteRepositoryInterface.php
> +     * Add a host
```suggestion
     * Add a host group
```

2021-01-07 10:59 UTC, callapa commented on src/Centreon/Domain/HostConfiguration/Model/HostGroup.php
> +        MAX_ALIAS_LENGTH = 200,
keep indentation

2021-01-07 10:59 UTC, callapa commented on src/Centreon/Domain/HostConfiguration/Model/HostGroup.php
> +    public function setId(?int $id): HostGroup
```suggestion
    public function setId(int $id): HostGroup
```

2021-01-07 10:59 UTC, callapa commented on src/Centreon/Domain/HostConfiguration/Model/HostGroup.php
> +        MAX_RRD = 99999999999,
????

2021-01-07 10:59 UTC, callapa commented on src/Centreon/Domain/HostConfiguration/UseCase/V21/FindHostGroups.php
> + * This class is designed to represent a use case to find all host templates
Be careful when copying and pasting the code.

2021-01-07 10:59 UTC, callapa commented on src/Centreon/Domain/HostConfiguration/UseCase/V21/FindHostGroupsResponse.php
> +     * @throws \Exception
?

2021-01-07 10:59 UTC, callapa commented on src/Centreon/Infrastructure/HostConfiguration/Repository/HostGroupRepositoryRDB.php
> +     * Add a host group.
Descriptions must be defined in the interface only.

2021-01-07 10:59 UTC, callapa commented on src/Centreon/Infrastructure/HostConfiguration/Repository/HostGroupRepositoryRDB.php
> + * This class is designed to represent the MariaDb repository to manage host, host group and host template
Are you sure ?

2021-01-07 10:59 UTC, callapa commented on src/Centreon/Infrastructure/HostConfiguration/Repository/HostGroupRepositoryRDB.php
> +        $statement = $this->db->query($request);
Why apply the search parameters if you don't take them into account?

2021-01-07 10:59 UTC, callapa commented on src/Centreon/Infrastructure/HostConfiguration/Repository/HostGroupRepositoryRDB.php
> +        foreach ($hostGroups as $order => $hostGroup) {
$order is never used.

2021-01-07 10:59 UTC, callapa commented on src/Centreon/Infrastructure/HostConfiguration/Repository/HostGroupRepositoryRDB.php
> +                    throw new RepositoryException(sprintf(_('Host Group with id %d not found'), $hostGroup->getId()));
You forgot to use a transaction to cancel previous insertions.

2021-01-07 10:59 UTC, callapa commented on src/Centreon/Infrastructure/HostConfiguration/Repository/Model/HostGroupFactoryRdb.php
> + * This class is designed to provide a way to create the HostTemplate entity from the database.
Be careful when copying and pasting the code.

2021-01-07 10:59 UTC, callapa commented on tests/php/Centreon/Infrastructure/HostConfiguration/Model/HostGroupFactoryRdbTest.php
> +        $this->rdbData = [
rddData or hostGroup ?

2021-01-07 10:59 UTC, callapa commented on src/Centreon/Domain/HostConfiguration/HostGroupService.php
> +<?php
Be careful when copying and pasting the code.
What is the purpose of this class, where do you use it?

2021-01-14 09:25 UTC, jeremyjaouen requested changes

2021-01-14 09:25 UTC, jeremyjaouen commented on src/Centreon/Domain/HostConfiguration/Model/HostGroup.php
> +    public function setId(int $id): HostGroup
```suggestion
    public function setId(?int $id): HostGroup
```
    /**
     * @var int|null
     */
    private $id;

2021-01-14 09:25 UTC, jeremyjaouen commented on src/Centreon/Domain/HostConfiguration/Model/HostGroup.php
> +     * @param int $id
```suggestion
     * @param int|null $id
```

2021-01-14 09:25 UTC, jeremyjaouen commented on src/Centreon/Domain/HostConfiguration/Model/HostGroup.php
> +        }
in method definition $name can't be null , I don't really know if you have to remove this condition, or add string|null to property name (and adequate changes in getter/setter), depending of the needed behaviour.

2021-01-14 09:25 UTC, jeremyjaouen commented on src/Centreon/Domain/HostConfiguration/UseCase/V21/HostGroup/FindHostGroups.php
> +    private $configurationReadRepository;
IMO, i found this naming a little confusing, why not called this  `$hostGroupReadRepository` ?

2021-01-14 09:25 UTC, jeremyjaouen commented on src/Centreon/Infrastructure/HostConfiguration/API/Model/HostGroupV21.php
> +    public $name;
Did the property of the Model should be in adequation with your src/Centreon/Domain/HostConfiguration/Model/HostGroup ? If so those two properties don't match.

2021-01-14 10:29 UTC, closed without merging