feat(api): Add Endpoint to patch Platform Informations
centreon-archive/centreon-archived pull request #9350
Opened 2020-12-30 07:32 UTC by jeremyjaouen

## Description

WIP - Add an Endpoint to PATCH platform informations

TODO:
 - Unit Tests

**Fixes** # MON-6501

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [x] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [ ] 19.10.x
- [ ] 20.04.x
- [x] 20.10.x
- [x] 21.04.x (master)

## Checklist

- [x] I have followed the **coding style guidelines** provided by Centreon
- [x] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [x] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have made corresponding changes to the **documentation**.
- [ ] I have **rebased** my development branch on the base branch (master, maintenance).

2021-01-04 08:22 UTC, callapa requested changes

2021-01-04 08:22 UTC, callapa commented on src/Centreon/Domain/RemoteServer/RemoteServerService.php
> +                    "Your Central is linked to another remote(s), conversion in Remote isn't allowed"
Don't forget the translation

2021-01-04 08:22 UTC, callapa commented on src/Centreon/Domain/RemoteServer/RemoteServerService.php
> +        system(
This operation must be in a repository

2021-01-04 08:22 UTC, callapa commented on src/Centreon/Domain/RemoteServer/RemoteServerService.php
> +        system(
This operation must be in a repository

2021-01-04 08:22 UTC, callapa commented on src/Centreon/Infrastructure/PlatformInformation/PlatformInformationRepositoryRDB.php
> +            $deleteQuery = $this->db->prepare($this->translateDbName('DELETE FROM `:db`.informations'));
Too dangerous in this case of use

2021-01-04 08:22 UTC, callapa commented on tests/php/Centreon/Domain/PlatformInformation/PlatformInformationServiceTest.php
> +    public function testUpdatePlatformToRemoteSuccess()
You omitted to give a small explanation for this test

2021-01-04 08:22 UTC, callapa commented on tests/php/Centreon/Domain/PlatformInformation/PlatformInformationServiceTest.php
> +    public function testUpdatePlatformToCentralSuccess()
You omitted to give a small explanation for this test

2021-01-04 08:22 UTC, callapa commented on src/Centreon/Domain/RemoteServer/RemoteServerService.php
> +    private function updatePlatformTypeParameters(string $type)
You omitted the PhpDoc.

2021-01-04 10:55 UTC, loiclau approved these changes, later dismissed

2021-01-04 12:37 UTC, kduret commented on lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "Votre central est liés a d'autre remote(s), la conversion en Remote n'est pas autorisée"
```suggestion
msgstr "Votre central est lié a d'autre remote(s), la conversion en Remote n'est pas autorisée"
```

2021-01-04 12:37 UTC, kduret commented on src/Centreon/Application/Controller/PlatformController.php
> +        // $platformInformationSchemaToValidate = Validator::arrayToObjectRecursive($platformToAdd);
```suggestion
```

2021-01-04 12:37 UTC, kduret commented on src/Centreon/Application/Controller/PlatformController.php
> +    public function updatePlatform(Request $request): View
missing param phpdoc

2021-01-04 12:37 UTC, kduret commented on doc/API/centreon-api-v2.yaml
> +      summary: "Update a platform informations"
```suggestion
      summary: "Update a platform information"
```

2021-01-04 12:37 UTC, kduret commented on lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgid "Unable to update the platform informations"
```suggestion
msgid "Unable to update the platform information"
```

2021-01-04 12:37 UTC, kduret commented on src/Centreon/Application/Controller/PlatformController.php
> +                ['message' => _('Unable to update the platform informations')],
```suggestion
                ['message' => _('Unable to update the platform information')],
```

2021-01-04 12:37 UTC, kduret commented on src/Centreon/Domain/RemoteServer/RemoteServerService.php
> +        $this->centreonEtcPath = $centreonEtcPath;
```suggestion
        $this->centreonEtcPath = DIRECTORY_SEPARATOR . ltrim($centreonEtcPath, DIRECTORY_SEPARATOR);
```

2021-01-04 12:37 UTC, kduret commented on src/Centreon/Domain/RemoteServer/RemoteServerService.php
> +
```suggestion
```

2021-01-04 12:37 UTC, kduret commented on src/Centreon/Infrastructure/PlatformInformation/PlatformInformationRepositoryRDB.php
> +                    }
```suggestion
                    $row['value'] = $row['value'] === 'yes';
```

2021-01-04 12:37 UTC, kduret commented on src/Centreon/Infrastructure/PlatformInformation/PlatformInformationRepositoryRDB.php
> +    public function updatePlatformInformation(PlatformInformation $platformInformation): void
missing phpdoc

2021-01-04 12:37 UTC, kduret commented on tests/api/features/PlatformInformation.feature
> +    In order to update the platform informations
```suggestion
    In order to update the platform information
```

2021-01-04 12:37 UTC, kduret commented on tests/api/features/PlatformInformation.feature
> +    I want to update some of the informations
```suggestion
    I want to update some of the information
```

2021-01-04 12:37 UTC, kduret commented on tests/api/features/PlatformInformation.feature
> +        #This step is mandatory, else the platform_topology is empty on the test container.
```suggestion
        # This step is mandatory, otherwise the platform_topology is empty on the test container.
```

2021-01-04 14:21 UTC, kduret submitted a review, later dismissed

2021-01-05 08:16 UTC, callapa requested changes

2021-01-05 08:16 UTC, callapa commented on src/Centreon/Domain/RemoteServer/RemoteServerService.php
> +        $this->remoteServerRepository->updateInstanceMod($this->centreonEtcPath . "conf.pm", "remote");
A repository must remain abstract in its use without revealing the technique used to process the information.
Here you pass a filename, please to inject it into the repository instead.

2021-01-05 08:16 UTC, callapa commented on src/Centreon/Domain/RemoteServer/RemoteServerService.php
> +    private function updatePlatformTypeParameters(string $type)
```suggestion
    private function updatePlatformTypeParameters(string $type): void
```

2021-01-05 08:16 UTC, callapa commented on src/Centreon/Domain/RemoteServer/RemoteServerService.php
> +     * @return void
```suggestion
```

2021-01-05 08:16 UTC, callapa commented on src/Centreon/Infrastructure/PlatformInformation/PlatformInformationRepositoryRDB.php
> +                    "DELETE FROM `:db`.informations WHERE `key` <> 'version' AND `key` <> 'appKey'"
If any data is inserted without being referenced as a property of the PlatformInformation class it will be automatically deleted. Too risky.

2021-01-05 08:16 UTC, callapa commented on src/Centreon/Infrastructure/RemoteServer/RemoteServerRepositoryFile.php
> +    public function updateInstanceMod(string $filePath, string $instanceType): void
No PHPDoc

2021-01-05 08:16 UTC, callapa commented on tests/php/Centreon/Domain/PlatformInformation/PlatformInformationServiceTest.php
> +     * @return void
```suggestion
```

2021-01-05 08:16 UTC, callapa commented on tests/php/Centreon/Domain/PlatformInformation/PlatformInformationServiceTest.php
> +    public function testUpdatePlatformToRemoteSuccess()
```suggestion
    public function testUpdatePlatformToRemoteSuccess(): void
```

2021-01-05 08:16 UTC, callapa commented on tests/php/Centreon/Domain/PlatformInformation/PlatformInformationServiceTest.php
> +     * @return void
```suggestion
```

2021-01-05 08:16 UTC, callapa commented on tests/php/Centreon/Domain/PlatformInformation/PlatformInformationServiceTest.php
> +    public function testUpdatePlatformToCentralSuccess()
```suggestion
    public function testUpdatePlatformToCentralSuccess(): void
```

2021-01-05 08:25 UTC, kduret commented on src/Centreon/Domain/RemoteServer/Interfaces/RemoteServerRepositoryInterface.php
> +    public function updateInstanceMod(string $filePath, string $instanceType): void;
```suggestion
    public function updateInstanceMode(string $filePath, string $instanceType): void;
```

2021-01-05 08:25 UTC, kduret commented on src/Centreon/Domain/RemoteServer/RemoteServerService.php
> +        $this->remoteServerRepository->updateInstanceMod($this->centreonEtcPath . "conf.pm", "remote");
```suggestion
        $this->remoteServerRepository->updateInstanceMode($this->centreonEtcPath . "conf.pm", "remote");
```

2021-01-05 08:25 UTC, kduret commented on src/Centreon/Domain/RemoteServer/RemoteServerService.php
> +        $this->remoteServerRepository->updateInstanceMod($this->centreonEtcPath . "conf.pm", "central");
```suggestion
        $this->remoteServerRepository->updateInstanceMode($this->centreonEtcPath . "conf.pm", "central");
```

2021-01-05 08:25 UTC, kduret commented on src/Centreon/Infrastructure/RemoteServer/RemoteServerRepositoryFile.php
> +    public function updateInstanceMod(string $filePath, string $instanceType): void
```suggestion
    public function updateInstanceMode(string $filePath, string $instanceType): void
```

2021-01-05 14:11 UTC, kduret approved these changes, later dismissed

2021-01-06 08:26 UTC, loiclau approved these changes, later dismissed

2021-01-06 15:48 UTC, callapa approved these changes

2021-01-06 16:21 UTC, kduret approved these changes

2021-01-07 06:34 UTC, merged