fix(CLAPI) save user language encoding in db
centreon-archive/centreon-archived pull request #9361
Opened 2021-01-05 13:52 UTC by loiclau

## Description
CLAPI check language don't take account of encoding indicate on the language directory (ex:fr_FR.UTF-8) when a user is created.

save encoding language in contact table

https://github.com/centreon/centreon/pull/9326

## Type of change

- [x] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [ ] 19.10.x
- [x] 20.04.x
- [x] 20.10.x
- [x] 21.04.x (master)

## Checklist

- [x] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have made corresponding changes to the **documentation**.
- [ ] I have **rebased** my development branch on the base branch (master, maintenance).

2021-01-08 11:22 UTC, callapa reviewed
Are update scripts necessary?

2021-01-12 15:52 UTC, callapa requested changes

2021-01-12 15:52 UTC, callapa commented on www/install/php/Update-20.10.3.php
> +try {
More simple with this SQL request:
`UPDATE contact SET contact_lang = CONCAT(contact_lang, '.UTF-8') WHERE contact_lang NOT LIKE "%.UTF-8";`

2021-01-13 09:12 UTC, sc979 submitted a review, later dismissed

2021-01-13 13:48 UTC, callapa commented on www/class/centreon-clapi/centreonContact.class.php
> +            || empty($params[self::ORDER_LANG])
It would make more sense to put this condition first.

2021-01-13 13:48 UTC, callapa commented on www/class/centreon-clapi/centreonContact.class.php
> +                        || empty($params[2])
It would make more sense to put this condition first.

2021-01-13 13:51 UTC, callapa submitted a review, later dismissed

2021-01-13 14:54 UTC, callapa approved these changes

2021-01-13 14:55 UTC, sc979 approved these changes

2021-01-14 13:19 UTC, merged