Mon 5535 security fixes
centreon-archive/centreon-archived pull request #9363
Opened 2021-01-05 15:07 UTC by adr-mo

This PR intends to:
- Fix several security issues
- Cleaning dozens of coding style errors on files that were edited

For the security issue related to externalcmd an other PR will be made for the 19.10.x and 2.8.x will be made as in previous versions centcore was still used.

**Fixes** # (issue)

## Type of change

- [x] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [ ] 19.10.x
- [x] 20.04.x
- [x] 20.10.x
- [x] 21.04.x (master)

<h2> How this pull request can be tested ? </h2>

Please describe the **procedure** to verify that the goal of the PR is matched. Provide clear instructions so that it can be **correctly tested**.

Any **relevant details** of the configuration to perform the test should be added.

## Checklist

- [ ] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have made corresponding changes to the **documentation**.
- [ ] I have **rebased** my development branch on the base branch (master, maintenance).

2021-01-05 15:08 UTC, sc979 commented
Kindly rename this PR ;)

2021-01-05 15:26 UTC, sc979 requested changes

2021-01-05 15:26 UTC, sc979 commented on www/api/class/centreon_metric.class.php
> +        $isAdmin = $centreon->user->admin;
not really useful, as they're called only one time

2021-01-05 15:26 UTC, sc979 commented on www/api/class/centreon_metric.class.php
> +        $query .= ' ORDER BY CONCAT(h.name," - ", s.description, " - ",  m.metric_name) COLLATE utf8_general_ci ';
could you try with the alias defined at line 144 ?
```suggestion
        $query .= ' ORDER BY fullname COLLATE utf8_general_ci ';
```

2021-01-05 15:26 UTC, sc979 commented on www/api/class/centreon_metric.class.php
> +        $query .= $aclMetrics;
```suggestion
            $query .= ' AND m.index_id = i.id AND i.service_id IN (' .
                $acl->getServicesString('ID', $this->pearDBMonitoring) . ') ';
        }

```

2021-01-05 15:26 UTC, sc979 commented on www/api/class/centreon_metric.class.php
> +            $aclMetrics .= 'AND s.service_id IN (' . $acl->getServicesString('ID', $this->pearDBMonitoring) . ') ';
```suggestion
            $query .= 'AND s.service_id IN (' . $acl->getServicesString('ID', $this->pearDBMonitoring) . ') ';
```

2021-01-05 15:26 UTC, sc979 commented on www/api/class/centreon_monitoring_poller.class.php
> +        $isAdmin = $centreon->user->admin;
used only one time

2021-01-05 15:26 UTC, sc979 commented on www/api/class/centreon_metric.class.php
> +        $aclMetrics = '';
```suggestion
```

2021-01-05 15:26 UTC, sc979 commented on www/api/class/centreon_monitoring_poller.class.php
> +        $aclPollers = '';
```suggestion
```

2021-01-05 15:43 UTC, sc979 approved these changes

2021-01-06 08:11 UTC, jeremyjaouen approved these changes

2021-01-06 08:23 UTC, loiclau approved these changes

2021-01-06 08:27 UTC, callapa commented on www/api/class/centreon_metric.class.php
> +        if (!$centreon->user->admin) {
I think it would have been better to do a private method that you would have called

2021-01-06 16:12 UTC, merged