enh(api): allow user to retrieve only resources with graphs
centreon-archive/centreon-archived pull request #9369
Opened 2021-01-07 16:45 UTC by adr-mo

This PR intends to add the possibility to return ONLY resources that has performance data available when calling `/monitoring/resources` endpoint.

Example

`http://[IP]/centreon/api/beta/monitoring/resources?page=1&limit=30&sort_by={"status_severity_code":"asc"}&types=["service"]&statuses=["OK"]&**only_with_performance_data=true**`

**Fixes** # (issue)

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [x] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [ ] 19.10.x
- [ ] 20.04.x
- [ ] 20.10.x
- [x] 21.04.x (master)

<h2> How this pull request can be tested ? </h2>

See JIRA issue for this

## Checklist

- [x] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [x] I have commented my code, especially **hard-to-understand areas** of the PR.
- [x] I have made corresponding changes to the **documentation**.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2021-01-08 10:12 UTC, callapa requested changes

2021-01-08 10:17 UTC, adr-mo commented
@callapa I'll remove the check of the parameter. No need to do the translation then :+1:

2021-01-08 10:19 UTC, adr-mo commented on src/Centreon/Domain/Monitoring/ResourceFilter.php
> +        if (!is_bool($onlyWithPerformanceData)) {
Done :heavy_check_mark:

2021-01-08 10:19 UTC, adr-mo commented on src/Centreon/Domain/Monitoring/ResourceFilter.php
> +                'Search parameter on resources that has performance data available should be a boolean'
As I've deleted the check no more message error will be thrown so no translation needs to be added.
Done :heavy_check_mark:

2021-01-08 14:15 UTC, callapa approved these changes

2021-01-12 09:42 UTC, loiclau approved these changes

2021-01-12 09:43 UTC, merged