fix(security): Sanitize and refactor contact creation and update request
centreon-archive/centreon-archived pull request #9624
Opened 2021-03-29 13:11 UTC by jeremyjaouen

## Description
This PR fix an issue where the contact forms wasn't sanitize correctly
**Fixes** # MON-6771

## Type of change

- [x] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [x] 2.8.x

## Checklist

- [x] I have followed the **coding style guidelines** provided by Centreon
- [x] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [x] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have made corresponding changes to the **documentation**.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2021-04-02 12:59 UTC, sc979 commented on www/include/configuration/configObject/contact/DB-Func.php
> +    $DBRESULT2 = $pearDB->query("SELECT contact_name FROM `contact` WHERE contact_id='" . intval($contact_id) . "' LIMIT 1");
```suggestion
    $DBRESULT2 = $pearDB->query("SELECT contact_name FROM `contact` WHERE contact_id='" . (int)$contact_id . "' LIMIT 1");
```

2021-04-02 13:00 UTC, sc979 commented on www/include/configuration/configObject/contact/DB-Func.php
> +                        FILTER_SANITIZE_STRING
FILTER_SANITIZE_STRING will return an empty string, not false

2021-04-02 13:00 UTC, sc979 commented on www/include/configuration/configObject/contact/DB-Func.php
> +                    )) === false)
FILTER_SANITIZE_STRING will return an empty string, not false

2021-04-02 13:00 UTC, sc979 commented on www/include/configuration/configObject/contact/DB-Func.php
> +                        (($inputValue = filter_var($inputValue, FILTER_SANITIZE_STRING)) === false)
FILTER_SANITIZE_STRING will return an empty string, not false

2021-04-02 13:00 UTC, sc979 commented on www/include/configuration/configObject/contact/DB-Func.php
> +                        (($inputValue = filter_var($inputValue, FILTER_SANITIZE_STRING)) === false)
FILTER_SANITIZE_STRING will return an empty string, not false

2021-04-02 13:01 UTC, sc979 commented on www/include/configuration/configObject/contact/DB-Func.php
> +            case 'contact_alias':
could these, be empty ?

2021-04-02 13:02 UTC, sc979 commented on www/include/configuration/configObject/contact/DB-Func.php
> +            case 'contact_alias':
https://github.com/centreon/centreon/pull/9624/files#diff-4cfd7b0df58e097781835a57f629acf237f44234e5f7f03db093d83ba7808d24R968

2021-04-02 13:02 UTC, sc979 requested changes
Kindly change the check on FILTER_SANITIZE_STRING

2021-04-02 14:02 UTC, sc979 approved these changes

2021-04-12 14:47 UTC, kduret approved these changes

2021-04-16 11:04 UTC, merged