sec(curveTemplates): secure page
centreon-archive/centreon-archived pull request #9762
Opened 2021-04-30 12:07 UTC by adr-mo

## Description

Secure graph template pages (other PR for 2.8.x)

**Fixes** # (issue)

## Type of change

- [x] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [x] 20.04.x
- [x] 20.10.x
- [x] 21.04.x
- [x] 21.10.x (master)

<h2> How this pull request can be tested ? </h2>

How to test is described in the Jira ticket

## Checklist

- [x] I have followed the **coding style guidelines** provided by Centreon
- [x] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have made corresponding changes to the **documentation**.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2021-04-30 12:22 UTC, kduret commented on www/include/views/componentTemplates/DB-Func.php
> +                        : $inputValue[$inputName]
```suggestion
                        ? $inputValue[$inputName]
                        : '0'
```

2021-04-30 12:22 UTC, kduret commented on www/include/views/componentTemplates/DB-Func.php
> +    $formValues = null;
```suggestion
    $formValues = [];
```

2021-04-30 12:22 UTC, kduret commented on www/include/views/componentTemplates/DB-Func.php
> +                        : $inputValue
```suggestion
                        : (int) $inputValue
```

2021-04-30 12:22 UTC, kduret commented on www/include/views/componentTemplates/DB-Func.php
>      }
```suggestion
    foreach ($bindParams as $token => list($paramType, $value)) {
        $stmt->bindValue($token, $value, $paramType);
    }
```

2021-04-30 12:22 UTC, kduret commented on www/include/views/componentTemplates/DB-Func.php
> +    }
```suggestion
    foreach ($bindParams as $token => list($paramType, $value)) {
        $stmt->bindValue($token, $value, $paramType);
    }
```

2021-04-30 12:22 UTC, kduret commented on www/include/views/componentTemplates/DB-Func.php
>      }
```suggestion
    foreach ($bindParams as $token => list($paramType, $value)) {
        $stmt->bindValue($token, $value, $paramType);
    }
```

2021-05-03 07:14 UTC, jeremyjaouen requested changes

2021-05-03 07:14 UTC, jeremyjaouen commented on www/include/views/componentTemplates/DB-Func.php
> +        : ' AND host_id = :host_id AND service_id = :service_id';
If one of those 2 variables is empty you will go to your else `' AND host_id = :host_id AND service_id = :service_id'` and possibly bind an empty value

2021-05-03 07:14 UTC, jeremyjaouen commented on www/include/views/componentTemplates/DB-Func.php
> +    if ($stmt->rowCount() >= 1 && $compo['compo_id'] == $formValues['compo_id']) {
double equals are needed ? If it's possible could you replace it by triple equals?

2021-05-03 07:14 UTC, jeremyjaouen commented on www/include/views/componentTemplates/DB-Func.php
> +    } elseif ($stmt->rowCount() >= 1 && $compo['compo_id'] != $formValues['compo_id']) {
double equals are needed ? If it's possible could you replace it by triple equals?

2021-05-03 08:13 UTC, jeremyjaouen approved these changes

2021-05-03 09:29 UTC, kduret approved these changes

2021-05-03 12:06 UTC, merged