enh(API): replace code from repository exception to correct exception class
centreon-archive/centreon-archived pull request #9848
Opened 2021-05-20 13:30 UTC by jeremyjaouen

## Description
This PR fix an issue where RepositoryException wasn't used properly. All the methods implemented inside have been moved to a more reliant Exception class. Also the class PlatformTopologyConflictExpcetion has been merged into PlatformTopologyException

## Type of change

- [x] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [ ] 20.04.x
- [x] 20.10.x
- [x] 21.04.x
- [x] 21.10.x (master)

<h2> How this pull request can be tested ? </h2>

Please describe the **procedure** to verify that the goal of the PR is matched. Provide clear instructions so that it can be **correctly tested**.

Any **relevant details** of the configuration to perform the test should be added.

## Checklist

- [x] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have made corresponding changes to the **documentation**.
- [ ] I have **rebased** my development branch on the base branch (master, maintenance).

2021-05-21 07:07 UTC, kduret approved these changes, later dismissed

2021-05-21 07:07 UTC, kduret commented on src/Centreon/Infrastructure/PlatformTopology/Repository/Exception/PlatformTopologyRepositoryException.php
> +        return new self(_("Request to the Central's API failed") . (' : ') . $details);
```suggestion
        return new self(_("Request to the Central's API failed") . ' : ' . $details);
```

2021-05-21 07:07 UTC, kduret commented on src/Centreon/Infrastructure/PlatformTopology/Repository/Exception/PlatformTopologyRepositoryException.php
> +        return new self(_("API calling the Central returned a Client exception") . (' : ') . $details);
```suggestion
        return new self(_("API calling the Central returned a Client exception") . ' : ' . $details);
```

2021-05-21 07:07 UTC, kduret commented on src/Centreon/Infrastructure/PlatformTopology/Repository/Exception/PlatformTopologyRepositoryException.php
> +        return new self(_("API calling the Central returned a Redirection exception") . (' : ') . $details);
```suggestion
        return new self(_("API calling the Central returned a Redirection exception") . ' : ' . $details);
```

2021-05-21 07:07 UTC, kduret commented on src/Centreon/Infrastructure/PlatformTopology/Repository/Exception/PlatformTopologyRepositoryException.php
> +        return new self($message . (' : ') . $details);
```suggestion
        return new self($message . ' : ' . $details);
```

2021-05-21 07:07 UTC, kduret commented on src/Centreon/Infrastructure/PlatformTopology/Repository/Exception/PlatformTopologyRepositoryException.php
> +        return new self(_("Unable to decode Central's API response") . (' : ') . $details);
```suggestion
        return new self(_("Unable to decode Central's API response") . ' : ' . $details);
```

2021-05-21 07:07 UTC, kduret commented on src/Centreon/Infrastructure/PlatformTopology/Repository/Exception/PlatformTopologyRepositoryException.php
> +        return new self(_("Error from Central's register API") . (' : ') . $details);
```suggestion
        return new self(_("Error from Central's register API") . ' : ' . $details);
```

2021-05-21 07:32 UTC, kduret approved these changes, later dismissed

2021-05-21 14:47 UTC, sc979 approved these changes, later dismissed

2021-05-26 11:37 UTC, callapa requested changes

2021-05-26 11:37 UTC, callapa commented on src/Centreon/Domain/PlatformTopology/Interfaces/PlatformTopologyRepositoryExceptionInterface.php
> +interface PlatformTopologyRepositoryExceptionInterface extends RepositoryExceptionInterface
Just keep this interface empty

2021-05-26 11:37 UTC, callapa commented on src/Centreon/Infrastructure/PlatformTopology/Repository/Exception/PlatformTopologyRepositoryException.php
> +class PlatformTopologyRepositoryException extends \Exception implements PlatformTopologyRepositoryExceptionInterface
```suggestion
class PlatformTopologyRepositoryException extends RepositoryException implements PlatformTopologyRepositoryExceptionInterface
```

2021-05-26 11:57 UTC, jeremyjaouen commented on src/Centreon/Application/Controller/PlatformTopologyController.php
> +        } catch (PlatformTopologyException | \Throwable $ex) {
I have  discuss about this with @kduret . I'm agreed that is not necessary but I found it more readable to keep the details of known Exception that could be catch.

2021-05-26 13:46 UTC, callapa approved these changes, later dismissed

2021-05-26 14:09 UTC, kduret approved these changes, later dismissed

2021-05-28 07:28 UTC, kduret approved these changes

2021-05-28 07:31 UTC, adr-mo approved these changes

2021-05-28 08:16 UTC, callapa approved these changes

2021-05-28 08:28 UTC, merged