poc(web): add security acknowledgement
centreon-archive/centreon-archived pull request #9859
Opened 2021-05-24 17:29 UTC by sc979

## Description

Add github wall of fame and security acknowledgements
Add in centreon links refering to the security policy (footer) and wall of fame (about)

**Fixes** # (issue)

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [x] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [x] 20.04.x
- [x] 20.10.x
- [x] 21.04.x
- [x] 21.10.x (master)

2021-06-09 09:54 UTC, sc979 commented on README.md
> +We want to thank all [reporters and pentesters](SECURITY_ACK.md) which help us improve our product each day.
```suggestion
We want to thank all [reporters and pentesters](SECURITY_ACK.md) who help us improve our product each day.
```

2021-06-09 10:00 UTC, sc979 commented on README.md
> +<h4> Security Acknowledgements page </h4>
```suggestion
<h4> Security Acknowledgement page </h4>
```

2021-06-11 08:17 UTC, cg-tw requested changes

2021-06-11 09:48 UTC, cg-tw approved these changes

2021-06-11 10:16 UTC, kduret approved these changes

2021-06-14 09:14 UTC, merged