fix(clapi): insert poller into platform_topology
centreon-archive/centreon-archived pull request #9966
Opened 2021-07-02 15:38 UTC by jeremyjaouen

## Description
This PR fix an issue where when using CLAPI to add a poller, it wasn't created into platform_topology.
**Fixes** # MON-10697

## Type of change

- [x] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [ ] 20.04.x
- [x] 20.10.x
- [x] 21.04.x
- [x] 21.10.x (master)

<h2> How this pull request can be tested ? </h2>

Please describe the **procedure** to verify that the goal of the PR is matched. Provide clear instructions so that it can be **correctly tested**.

Any **relevant details** of the configuration to perform the test should be added.

## Checklist

- [x] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have made corresponding changes to the **documentation**.
- [ ] I have **rebased** my development branch on the base branch (master, maintenance).

2021-07-05 13:24 UTC, callapa requested changes

2021-07-05 13:24 UTC, callapa commented on lib/Centreon/Object/Instance/Instance.php
> +            if ($parentPlatform !== null && $parentPlatform->getType() === 'remote') {
Is there a constant to replace "remote"?

2021-07-05 13:24 UTC, callapa commented on lib/Centreon/Object/Instance/Instance.php
> +        $platformTopology = $this->findPlatformTopologyByAddress($params['ns_ip_address']);
Please test the existence of this 'ns_ip_address' index first.

2021-07-05 13:24 UTC, callapa commented on lib/Centreon/Object/Instance/Instance.php
> +            $this->db->beginTransaction();
Please check that we are not already in a database transaction.

2021-07-06 06:38 UTC, callapa requested changes

2021-07-06 06:38 UTC, callapa commented on lib/Centreon/Object/Instance/Instance.php
> +                $this->db->commit();
If you are already in a database transaction, the commit/rollback process should be handled by whoever started it.
```suggestion
                if (!$isAlreadyInTransaction) {
                    $this->db->commit();
                }
```

2021-07-06 06:38 UTC, callapa commented on lib/Centreon/Object/Instance/Instance.php
> +                $this->db->rollBack();
```suggestion
                if (!$isAlreadyInTransaction) {
                    $this->db->rollBack();
                }
```

2021-07-07 07:26 UTC, kduret commented on lib/Centreon/Object/Instance/Instance.php
> +            "VALUES (:address, :name, 'poller', '0', :parentId, :serverId)"
use a constant for `poller`

2021-07-07 08:17 UTC, kduret submitted a review, later dismissed

2021-07-09 08:48 UTC, callapa requested changes

2021-07-09 08:48 UTC, callapa commented on lib/Centreon/Object/Instance/Instance.php
> +     * @return void
```suggestion
     * @return int
```

2021-07-09 09:00 UTC, callapa approved these changes

2021-07-09 09:49 UTC, kduret approved these changes

2021-07-09 09:59 UTC, merged