enh(codebase): make centreon 20.04 compatible with php 7.3
centreon-archive/centreon-archived pull request #9998
Opened 2021-07-16 14:06 UTC by jeremyjaouen

## Description

Make centreon web compatible with PHP 7.3

**Fixes** # MON-7341

## Type of change

- [x] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [x] 20.04.x

<h2> How this pull request can be tested ? </h2>

Please describe the **procedure** to verify that the goal of the PR is matched. Provide clear instructions so that it can be **correctly tested**.

Any **relevant details** of the configuration to perform the test should be added.

## Checklist

- [ ] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have made corresponding changes to the **documentation**.
- [ ] I have **rebased** my development branch on the base branch (master, maintenance).

2021-07-16 14:12 UTC, kduret approved these changes

2021-07-16 15:29 UTC, callapa requested changes

2021-07-16 15:29 UTC, callapa commented on www/class/config-generate/resource.class.php
> +class Resources extends AbstractObject
Please rename the file to resources.class.php to respect the above conventions.

2021-07-19 09:27 UTC, callapa approved these changes

2021-07-19 12:58 UTC, merged